export const OFFICIAL_POSTAL_SOURCE_CATALOG_VERSION = 'official-postal-source-catalog-v2';

export type PostalSourceAuthority =
  | 'postal-operator'
  | 'government'
  | 'intergovernmental-postal-standard'
  | 'official-open-data'
  | 'official-derived-open-source'
  | 'open-source'
  | 'community'
  | 'commercial-or-restricted'
  | 'unknown';

export type PostalSourceTrustTier =
  | 'authoritative'
  | 'official'
  | 'official-derived'
  | 'open-reference'
  | 'community'
  | 'weak';

export type PostalSourceAvailability =
  | 'public-api'
  | 'auth-required-api'
  | 'bulk-open-data'
  | 'licensed-bulk-data'
  | 'commercial-or-restricted'
  | 'web-search'
  | 'no-normal-postcode'
  | 'unknown';

export type PostalSourceDepth =
  | 'postcode'
  | 'locality'
  | 'street'
  | 'address'
  | 'building'
  | 'delivery-point'
  | 'geo-only'
  | 'legal-framework';

export type PostalSourceValidationReadiness =
  | 'reference-eligible'
  | 'metadata-only';

export type PostalSourceRole =
  | 'postal-reference-data'
  | 'legal-framework-only';

export type OfficialPostalSourceProfile = {
  id: string;
  countryCodes: string[];
  label: string;
  authority: PostalSourceAuthority;
  trustTier: PostalSourceTrustTier;
  availability: PostalSourceAvailability;
  depth: PostalSourceDepth;
  sourceRole?: PostalSourceRole;
  validationReadiness?: PostalSourceValidationReadiness;
  url: string;
  sourceNames: string[];
  openSourceIds: string[];
  requiresCredential: boolean;
  notes: string[];
};

export type PostalSourceClassification = {
  tier: PostalSourceTrustTier;
  strength: 'strong' | 'weak';
  reason: string;
  matches: OfficialPostalSourceProfile[];
};

const GLOBAL_OFFICIAL_POSTAL_SOURCES: OfficialPostalSourceProfile[] = [
  {
    id: 'upu-universal-postcode-database',
    countryCodes: ['*'],
    label: 'UPU Universal POST*CODE Database and Addressing Solutions',
    authority: 'intergovernmental-postal-standard',
    trustTier: 'official',
    availability: 'licensed-bulk-data',
    depth: 'postcode',
    url: 'https://www.upu.int/en/postal-solutions/programmes-services/addressing-solutions?cid=28&csid=20',
    sourceNames: [
      'upu',
      'universal postcode',
      'universal post*code',
      'postal addressing systems',
      'upu addressing solutions',
    ],
    openSourceIds: ['upu-addressing'],
    requiresCredential: true,
    notes: [
      'Official intergovernmental postal addressing and postcode source; use as licensed fallback and prefer national postal-operator APIs or bulk data when available.',
    ],
  },
];

const GLOBAL_OPEN_REFERENCE_SOURCES: OfficialPostalSourceProfile[] = [
  {
    id: 'openaddresses',
    countryCodes: ['*'],
    label: 'OpenAddresses',
    authority: 'open-source',
    trustTier: 'open-reference',
    availability: 'bulk-open-data',
    depth: 'address',
    url: 'https://openaddresses.io/',
    sourceNames: ['openaddresses', 'open addresses'],
    openSourceIds: ['openaddresses'],
    requiresCredential: false,
    notes: ['Open address reference records; coverage and licenses vary by source dataset.'],
  },
  {
    id: 'osm-nominatim',
    countryCodes: ['*'],
    label: 'OpenStreetMap Nominatim',
    authority: 'open-source',
    trustTier: 'open-reference',
    availability: 'public-api',
    depth: 'geo-only',
    url: 'https://nominatim.org/release-docs/latest/api/Overview/',
    sourceNames: ['osm-nominatim', 'nominatim', 'openstreetmap'],
    openSourceIds: ['osm-nominatim', 'osm-overpass'],
    requiresCredential: false,
    notes: ['Use as geocoding/gazetteer fallback, not as postal deliverability proof.'],
  },
  {
    id: 'geonames-postal',
    countryCodes: ['*'],
    label: 'GeoNames postal data',
    authority: 'open-source',
    trustTier: 'community',
    availability: 'bulk-open-data',
    depth: 'locality',
    url: 'https://download.geonames.org/export/zip/',
    sourceNames: ['geonames', 'geonames-postal'],
    openSourceIds: ['geonames-postal'],
    requiresCredential: false,
    notes: [
      'CC BY 4.0 bulk postal files; attribution required.',
      'Useful fallback, but keep postal verification partial unless another strong source agrees.',
    ],
  },
  {
    id: 'zippopotam',
    countryCodes: ['*'],
    label: 'Zippopotam',
    authority: 'community',
    trustTier: 'community',
    availability: 'public-api',
    depth: 'locality',
    url: 'https://api.zippopotam.us/',
    sourceNames: ['zippopotam'],
    openSourceIds: ['zippopotam'],
    requiresCredential: false,
    notes: ['Community fallback for postal-code locality candidates.'],
  },
];

export const OFFICIAL_POSTAL_SOURCE_CATALOG: OfficialPostalSourceProfile[] = [
  {
    id: 'japan-post-digital-address-api',
    countryCodes: ['JP'],
    label: 'Japan Post Postal Code and Digital Address API',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'address',
    url: 'https://lp-api.da.pf.japanpost.jp/',
    sourceNames: ['japan post digital address api', 'japan-post-digital-address-api', 'postal code digital address api'],
    openSourceIds: ['japan-post-digital-address-api'],
    requiresCredential: false,
    notes: ['Official Japan Post API announced as free from May 2025 for postal-code and digital-address lookup.'],
  },
  {
    id: 'japan-post-csv',
    countryCodes: ['JP'],
    label: 'Japan Post postal-code CSV',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'locality',
    url: 'https://www.post.japanpost.jp/service/search/zipcode/download/utf-zip.html',
    sourceNames: ['japan post', 'japan-post', 'japan postcode', 'japan post csv'],
    openSourceIds: ['japan-post-csv'],
    requiresCredential: false,
    notes: [
      'Official postal-code CSV and change notices from Japan Post.',
      'Japan Post states that it asserts no copyright in postal-code data and permits free redistribution.',
    ],
  },
  {
    id: 'zipcloud-jp',
    countryCodes: ['JP'],
    label: 'zipcloud Japan postcode API',
    authority: 'official-derived-open-source',
    trustTier: 'official-derived',
    availability: 'public-api',
    depth: 'locality',
    url: 'https://zipcloud.ibsnet.co.jp/',
    sourceNames: ['zipcloud'],
    openSourceIds: ['zipcloud-jp', 'japan-postcode-api'],
    requiresCredential: false,
    notes: ['Community API derived from Japan Post postal-code data; strong for postcode-to-locality, not delivery-point proof.'],
  },
  {
    id: 'usps-web-tools',
    countryCodes: ['US'],
    label: 'USPS APIs Addresses 3.0 and ZIP lookup APIs',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'auth-required-api',
    depth: 'delivery-point',
    url: 'https://developers.usps.com/apis',
    sourceNames: [
      'usps',
      'usps web tools',
      'usps addresses api',
      'addresses 3.0',
      'zip code lookup api',
      'city state lookup',
      'address standardization api',
      'address information api',
    ],
    openSourceIds: ['usps-web-tools', 'usps-addresses-api'],
    requiresCredential: true,
    notes: [
      'Official USPS API path for domestic address standardization, City/State lookup, ZIP Code lookup, and ZIP+4 delivery-point indicators; credentials and terms are required.',
      'AGID country packs record this as source metadata only and must not store ZIP+4 delivery-point payloads or raw address responses.',
    ],
  },
  {
    id: 'us-census-tiger-line',
    countryCodes: ['US'],
    label: 'U.S. Census Bureau TIGER/Line and TIGERweb geography products',
    authority: 'official-open-data',
    trustTier: 'official',
    availability: 'bulk-open-data',
    depth: 'geo-only',
    url: 'https://www.census.gov/programs-surveys/geography/guidance/tiger-data-products-guide.html',
    sourceNames: ['tiger line', 'tigerweb', 'census tiger', 'tiger/line shapefiles', 'zcta'],
    openSourceIds: ['us-census-tiger-line', 'tigerweb'],
    requiresCredential: false,
    notes: [
      'Official U.S. Census geographic products for state, county, place, road, address-range, water, and ZCTA-style geography references.',
      'ZCTAs are Census statistical approximations and must not be treated as USPS ZIP delivery areas.',
    ],
  },
  {
    id: 'us-census-geocoder',
    countryCodes: ['US'],
    label: 'U.S. Census Geocoding Services API',
    authority: 'government',
    trustTier: 'official',
    availability: 'public-api',
    depth: 'address',
    url: 'https://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.html',
    sourceNames: ['census geocoder', 'u.s. census geocoder', 'maf tiger geocoder', 'geocoding services'],
    openSourceIds: ['us-census-geocoder'],
    requiresCredential: false,
    notes: [
      'Official Census geocoder for address-to-coordinate and geography lookup based on MAF/TIGER benchmarks.',
      'Use as geospatial/geography evidence, not as USPS delivery-point validation.',
    ],
  },
  {
    id: 'hud-usps-zip-crosswalk',
    countryCodes: ['US'],
    label: 'HUD USPS ZIP Code Crosswalk API',
    authority: 'government',
    trustTier: 'official',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://www.huduser.gov/portal/dataset/uspszip-api.html',
    sourceNames: ['hud usps zip', 'usps zip crosswalk'],
    openSourceIds: ['hud-usps-zip-crosswalk'],
    requiresCredential: false,
    notes: ['Government crosswalk for ZIP Code analysis; not delivery-point validation.'],
  },
  {
    id: 'ons-postcode-directory',
    countryCodes: ['GB'],
    label: 'ONS Postcode Directory',
    authority: 'government',
    trustTier: 'official',
    availability: 'bulk-open-data',
    depth: 'postcode',
    url: 'https://www.ons.gov.uk/methodology/geography/geographicalproducts/postcodeproducts',
    sourceNames: ['ons postcode directory', 'ons-pd', 'onspd'],
    openSourceIds: ['ons-postcode-directory'],
    requiresCredential: false,
    notes: [
      'Official UK statistical postcode reference for live and terminated codes; not Royal Mail delivery-point proof or an official postcode boundary.',
      'Northern Ireland BT reuse is subject to separate Land and Property Services terms, including commercial-use restrictions.',
    ],
  },
  {
    id: 'royal-mail-paf',
    countryCodes: ['GB'],
    label: 'Royal Mail Postcode Address File',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'licensed-bulk-data',
    depth: 'delivery-point',
    url: 'https://www.royalmail.com/business/data-quality/address-data',
    sourceNames: ['royal mail', 'paf', 'postcode address file'],
    openSourceIds: ['royal-mail-paf'],
    requiresCredential: true,
    notes: [
      'Official UK delivery-point address and postcode-assignment reference, licensed rather than open.',
      'PAF assignment does not by itself define an official postcode polygon.',
    ],
  },
  {
    id: 'postcodes-io',
    countryCodes: ['GB'],
    label: 'postcodes.io',
    authority: 'official-derived-open-source',
    trustTier: 'official-derived',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://postcodes.io/',
    sourceNames: ['postcodes-io', 'postcodes.io'],
    openSourceIds: ['postcodes-io'],
    requiresCredential: false,
    notes: ['Open API based on UK open postcode datasets; strong postcode reference, not delivery-point proof.'],
  },
  {
    id: 'canada-post-addresscomplete',
    countryCodes: ['CA'],
    label: 'Canada Post AddressComplete',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'auth-required-api',
    depth: 'delivery-point',
    url: 'https://www.canadapost-postescanada.ca/ac/',
    sourceNames: ['canada post', 'addresscomplete'],
    openSourceIds: ['canada-post-addresscomplete'],
    requiresCredential: true,
    notes: ['Official postal operator address lookup product; credentials or commercial terms may apply.'],
  },
  {
    id: 'correos-guatemala-postal-legal-framework',
    countryCodes: ['GT'],
    label: 'Correos de Guatemala postal legal framework',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'legal-framework',
    sourceRole: 'legal-framework-only',
    validationReadiness: 'metadata-only',
    url: 'https://correos.gob.gt/ART10/inciso_1/Normativa.pdf',
    sourceNames: [
      'correos de guatemala',
      'direccion general de correos y telegrafos',
      'codigo postal de la republica de guatemala',
      'guatemala postal code normativa',
    ],
    openSourceIds: ['correos-guatemala-postal-legal-framework'],
    requiresCredential: false,
    notes: [
      'Official Correos de Guatemala transparency material identifies the national postal legal framework.',
      'This entry is a legal-framework reference, not a current postcode-to-locality dataset or postal lookup service.',
      'It does not establish reusable data rights, current nationwide mapping completeness, or delivery-point validity.',
      'Identify a current official postal-reference dataset before recording source version, reuse, coverage, correction, and quality evidence.',
    ],
  },
  {
    id: 'correios-cep-api',
    countryCodes: ['BR'],
    label: 'Correios CEP API',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'auth-required-api',
    depth: 'address',
    url: 'https://www.correios.com.br/atendimento/developers',
    sourceNames: ['correios', 'correios cep api'],
    openSourceIds: ['correios-cep-api'],
    requiresCredential: true,
    notes: ['Official Correios API path for contract clients; public use may require credentials.'],
  },
  {
    id: 'viacep',
    countryCodes: ['BR'],
    label: 'ViaCEP',
    authority: 'community',
    trustTier: 'official-derived',
    availability: 'public-api',
    depth: 'street',
    url: 'https://viacep.com.br/',
    sourceNames: ['viacep'],
    openSourceIds: ['viacep'],
    requiresCredential: false,
    notes: ['Public CEP API commonly used as open fallback; treat as strong candidate evidence, not postal-operator proof.'],
  },
  {
    id: 'brasilapi-cep',
    countryCodes: ['BR'],
    label: 'BrasilAPI CEP',
    authority: 'community',
    trustTier: 'official-derived',
    availability: 'public-api',
    depth: 'street',
    url: 'https://brasilapi.com.br/',
    sourceNames: ['brasilapi'],
    openSourceIds: ['brasilapi'],
    requiresCredential: false,
    notes: ['Open API fallback for Brazilian CEP lookup.'],
  },
  {
    id: 'onemap-sg',
    countryCodes: ['SG'],
    label: 'Singapore OneMap',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'auth-required-api',
    depth: 'building',
    url: 'https://www.onemap.gov.sg/apidocs/',
    sourceNames: ['onemap', 'one map', 'one-map', 'sla onemap'],
    openSourceIds: ['onemap-sg', 'one-map'],
    requiresCredential: true,
    notes: ['Official Singapore Land Authority national map and address search API; token required for Search API.'],
  },
  {
    id: 'la-poste-fr-postal-codes',
    countryCodes: ['FR'],
    label: 'La Poste Base officielle des codes postaux',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'postcode',
    url: 'https://www.data.gouv.fr/datasets/base-officielle-des-codes-postaux',
    sourceNames: ['la poste', 'base officielle des codes postaux', 'laposte hexasmal'],
    openSourceIds: ['data-gouv-fr-postcodes'],
    requiresCredential: false,
    notes: ['Official code-to-INSEE-commune assignments; it does not publish official postal-code boundaries.'],
  },
  {
    id: 'api-adresse-data-gouv-fr',
    countryCodes: ['FR'],
    label: 'API Adresse - Base Adresse Nationale',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'address',
    url: 'https://adresse.data.gouv.fr/outils/api-doc/adresse',
    sourceNames: ['api adresse', 'api-adresse', 'ban', 'base adresse nationale', 'data.gouv', 'data.gouv.fr'],
    openSourceIds: ['api-adresse-data-gouv-fr', 'ban-fr'],
    requiresCredential: false,
    notes: ['Official BAN address reference. The legacy API Adresse endpoint was retired in favor of the Géoplateforme geocoder; BAN address evidence is not postal assignment or building-link proof.'],
  },
  {
    id: 'deutsche-post-plz-server',
    countryCodes: ['DE'],
    label: 'Deutsche Post / Postdirekt postcode search',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://www.postdirekt.de/plzserver/',
    sourceNames: [
      'deutsche post',
      'postdirekt',
      'deutsche post postcode search',
      'postdirekt postcode search',
      'postleitzahlensuche',
      'plz suche',
    ],
    openSourceIds: ['deutsche-post-plz-server'],
    requiresCredential: false,
    notes: [
      'Official Deutsche Post interactive postcode and locality search operated through Postdirekt.',
      'Use as current postcode evidence; automated extraction, bulk redistribution, and address-level deliverability remain separate concerns.',
    ],
  },
  {
    id: 'openplzapi',
    countryCodes: ['DE', 'AT', 'CH', 'LI'],
    label: 'OpenPLZ API',
    authority: 'open-source',
    trustTier: 'open-reference',
    availability: 'public-api',
    depth: 'locality',
    url: 'https://www.openplzapi.org/en/',
    sourceNames: ['openplz', 'openplzapi'],
    openSourceIds: ['openplzapi'],
    requiresCredential: false,
    notes: ['Open postal-code API for German-speaking countries; use as open reference evidence.'],
  },
  {
    id: 'posti-finland-postal-code-services',
    countryCodes: ['FI'],
    label: 'Posti Finland Postal Code Services',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'street',
    url: 'https://www.posti.fi/en/for-businesses/customer-support/postal-code-services',
    sourceNames: [
      'posti',
      'posti finland',
      'posti postal code services',
      'posti postal code search',
      'finland postal code services',
      'postinumero',
    ],
    openSourceIds: ['posti-finland-postal-code-services'],
    requiresCredential: false,
    notes: [
      'Official Posti files provide valid Finnish postcodes and current address data, including a basic address file with street and municipality coverage outside Aland.',
      'The postcode file is updated daily except Sundays and the basic address file weekly; retain separate evidence for delivery-point availability.',
    ],
  },
  {
    id: 'latvijas-pasts-check-address',
    countryCodes: ['LV'],
    label: 'Latvijas Pasts Check address',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'address',
    url: 'https://pasts.lv/en/check-address',
    sourceNames: [
      'latvijas pasts',
      'latvian post',
      'latvijas pasts check address',
      'pasts check address',
      'parbaudit adresi',
    ],
    openSourceIds: ['latvijas-pasts-check-address'],
    requiresCredential: false,
    notes: [
      'Official Latvijas Pasts address checker for validated Latvian address notation, postcode lookup, and service-area checks.',
      'Use as current interactive address and postcode evidence; bulk extraction and redistribution rights remain separate.',
    ],
  },
  {
    id: 'lietuvos-pastas-postcode-search',
    countryCodes: ['LT'],
    label: 'Lietuvos pastas postal code and address search',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'address',
    url: 'https://www.post.lt/pasto-kodu-ir-adresu-paieska',
    sourceNames: [
      'lietuvos pastas',
      'lithuania post',
      'lithuanian post',
      'lietuvos pastas postal code search',
      'pasto kodu ir adresu paieska',
    ],
    openSourceIds: ['lietuvos-pastas-postcode-search'],
    requiresCredential: false,
    notes: [
      'Official Lithuania Post search for postcode-by-address and address-by-postcode lookups.',
      'Use as current interactive address and postcode evidence; automated extraction and bulk redistribution remain separate concerns.',
    ],
  },
  {
    id: 'omniva-estonia-postcodes',
    countryCodes: ['EE'],
    label: 'Omniva Estonia ZIP Codes',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://www.omniva.ee/en/zip-codes/',
    sourceNames: ['omniva', 'eesti post', 'estonia zip codes', 'sihtnumber', 'postiindeks'],
    openSourceIds: ['omniva-estonia-postcodes'],
    requiresCredential: false,
    notes: ['Official operator address-to-postcode search and download; automated caching, redistribution and deliverability remain separately governed.'],
  },
  {
    id: 'estonia-aks-postal-codes',
    countryCodes: ['EE'],
    label: 'Estonia AKS Postal Codes',
    authority: 'official-open-data',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'address',
    url: 'https://geoportaal.maaamet.ee/eng/spatial-data/address-data/postal-codes-p661.html',
    sourceNames: ['aks postal codes', 'ads postal codes', 'estonia postal code extract', 'sihtnumbrid'],
    openSourceIds: ['estonia-aks-postal-codes'],
    requiresCredential: false,
    notes: ['Official monthly address-to-postcode extract and query path based on Omniva-managed zones; preserve ADR_ID, source edition, coordinates and current-only scope.'],
  },
  {
    id: 'estonia-aks-postal-areas',
    countryCodes: ['EE'],
    label: 'Estonia AKS Postal Code Areas',
    authority: 'official-open-data',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://geoportaal.maaamet.ee/eng/services/public-wms-wfs-p346.html',
    sourceNames: ['aks postal areas', 'sihtnumbri alad', 'estonia postcode polygons'],
    openSourceIds: ['estonia-aks-postal-areas'],
    requiresCredential: false,
    notes: ['Official public AKS OGC postal-code-area layer; pin service schema, CRS, retrieval time, attribution and digest independently from assignments.'],
  },
  {
    id: 'estonia-aks-address-objects',
    countryCodes: ['EE'],
    label: 'Estonia AKS/ADS Address Objects',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'address',
    url: 'https://geoportaal.maaamet.ee/eng/spatial-data/address-data-p313.html',
    sourceNames: ['in-aks', 'aks', 'ads', 'estonian address data system', 'estonia address objects'],
    openSourceIds: ['estonia-aks-address-objects'],
    requiresCredential: false,
    notes: [
      'Official open national addresses and address objects for parcels, buildings and building parts with stable ADS_OID and version ADOB_ID.',
      'In-AKS replaced In-ADS from 27 April 2026; legacy ADS SOAP services close at the end of 2026 and must not be hard-coded as the future interface.',
    ],
  },
  {
    id: 'estonia-aks-building-shapes',
    countryCodes: ['EE'],
    label: 'Estonia AKS/ADS Building Shapes',
    authority: 'official-open-data',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'building',
    url: 'https://geoportaal.maaamet.ee/eng/services/public-wms-wfs-p346.html',
    sourceNames: ['aks buildings', 'ads building shape', 'hooned ads', 'estonia building geometry'],
    openSourceIds: ['estonia-aks-building-shapes'],
    requiresCredential: false,
    notes: ['Official ADS building point and polygon layers; exact display requires a coherent ADS_OID/ADOB_ID object path rather than nearest geometry.'],
  },
  {
    id: 'estonia-ehak-admin-boundaries',
    countryCodes: ['EE'],
    label: 'Estonia EHAK Administrative and Settlement Division',
    authority: 'official-open-data',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'geo-only',
    url: 'https://geoportaal.maaamet.ee/eng/Spatial-Data/Administrative-and-Settlement-Division-p312.html',
    sourceNames: ['ehak', 'estonia administrative boundaries', 'estonia settlement division'],
    openSourceIds: ['estonia-ehak-admin-boundaries'],
    requiresCredential: false,
    notes: ['Official monthly county, municipality and settlement geometry with EHAK codes; administrative areas do not assign or delimit postal codes.'],
  },
  {
    id: 'eircode-ecaf-ecad',
    countryCodes: ['IE'],
    label: 'Eircode ECAF and ECAD address products',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'licensed-bulk-data',
    depth: 'address',
    url: 'https://www.eircode.ie/business/products-and-services',
    sourceNames: ['eircode', 'ecaf', 'ecad', 'eircode address file', 'eircode address database'],
    openSourceIds: ['eircode-ecaf', 'eircode-ecad'],
    requiresCredential: true,
    notes: [
      'Official Irish postcode/address data products for all address points; access is licensed and must not be bundled without rights.',
      'Record source metadata only unless a licensed redistribution path is approved.',
    ],
  },
  {
    id: 'poste-italiane-cap',
    countryCodes: ['IT'],
    label: 'Poste Italiane Codice di Avviamento Postale (CAP)',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://www.poste.it/cap',
    sourceNames: ['poste italiane', 'cap', 'codice di avviamento postale', 'italian postcodes'],
    openSourceIds: ['poste-italiane-cap'],
    requiresCredential: false,
    notes: [
      'Official Poste Italiane CAP search and CAP update notices.',
      'Use as official source metadata and interactive verification path; bulk licensing and redistribution remain separate.',
    ],
  },
  {
    id: 'bpost-address-validation',
    countryCodes: ['BE'],
    label: 'bpost address validation web service and widget',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'address',
    url: 'https://www.bpost.be/en/addressing-web-service-widgets-address-validation',
    sourceNames: ['bpost', 'bpost address validation', 'belgian address validation', 'addressing web service'],
    openSourceIds: ['bpost-address-validation'],
    requiresCredential: false,
    notes: [
      'Official Belgian postal-operator web service and widgets for automatic formatting and address validation.',
      'Do not store raw address responses in public fixtures; use synthetic fixtures for tests.',
    ],
  },
  {
    id: 'post-luxembourg-postcode-search',
    countryCodes: ['LU'],
    label: 'POST Luxembourg postcode search',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://www.post.lu/en/particuliers/colis-courrier/rechercher-un-code-postal',
    sourceNames: ['post luxembourg', 'luxembourg postcode', 'find a postcode luxembourg'],
    openSourceIds: ['post-luxembourg-postcode-search'],
    requiresCredential: false,
    notes: [
      'Official POST Luxembourg postcode search from address or town.',
      'Treat as official interactive postcode evidence; bulk/open redistribution must be separately proven.',
    ],
  },
  {
    id: 'ctt-portugal-postal-code-search',
    countryCodes: ['PT'],
    label: 'CTT Portugal postal-code search',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://www.ctt.pt/feapl_2/app/open/postalCodeSearch/postalCodeSearch.jspx?lang=def',
    sourceNames: [
      'ctt',
      'ctt portugal',
      'ctt correios de portugal',
      'ctt postal code search',
      'encontrar codigos postais',
    ],
    openSourceIds: ['ctt-portugal'],
    requiresCredential: false,
    notes: [
      'Official CTT postcode finder for street, locality, and postcode lookup across mainland Portugal, the Azores, and Madeira.',
      'Use as official interactive postcode evidence; bulk redistribution and automated scraping rights remain separate.',
    ],
  },
  {
    id: 'jersey-post-address-finder',
    countryCodes: ['JE'],
    label: 'Jersey Post address and postcode finder',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'address',
    url: 'https://www.jerseypost.com/tools/address-finder/',
    sourceNames: [
      'jersey post',
      'jersey postcode finder',
      'jersey address finder',
      'jersey post address finder',
      'jersey post postcode finder',
    ],
    openSourceIds: ['jersey-post'],
    requiresCredential: false,
    notes: [
      'Official Jersey Post finder for full postal addresses and postcodes across Jersey.',
      'Use as current interactive address and postcode evidence; bulk reuse and automated extraction rights remain separate.',
    ],
  },
  {
    id: 'isle-of-man-post-office-postcode-finder',
    countryCodes: ['IM'],
    label: 'Isle of Man Post Office postcode finder',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'address',
    url: 'https://www.iompost.com/tools-forms/postcode-finder/',
    sourceNames: [
      'isle of man post office',
      'iom post office',
      'isle of man postcode finder',
      'iom postcode finder',
      'isle of man address finder',
    ],
    openSourceIds: ['isle-of-man-post'],
    requiresCredential: false,
    notes: [
      'Official Isle of Man Post Office postcode finder for island address and postcode lookup.',
      'Use as current interactive address and postcode evidence; bulk reuse and automated extraction rights remain separate.',
    ],
  },
  {
    id: 'royal-gibraltar-post-office',
    countryCodes: ['GI'],
    label: 'Royal Gibraltar Post Office',
    authority: 'government',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://www.gibraltar.gov.gi/public-services/post-office',
    sourceNames: [
      'royal gibraltar post office',
      'gibraltar post office',
      'post.gi',
      'gibraltar government post office',
    ],
    openSourceIds: ['royal-gibraltar-post'],
    requiresCredential: false,
    notes: [
      'Official HM Government of Gibraltar postal-service page for the Royal Gibraltar Post Office.',
      'Use as current postcode and routing reference for Gibraltar while delivery-point datasets remain non-public.',
    ],
  },
  {
    id: 'postnord-se-location-apis',
    countryCodes: ['SE'],
    label: 'PostNord Sweden postcode and location APIs',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'auth-required-api',
    depth: 'postcode',
    url: 'https://developer.postnord.com/apis/active?category=location',
    sourceNames: ['postnord', 'postnord sweden', 'sweden postcode', 'postnord location api'],
    openSourceIds: ['postnord-se-location-apis'],
    requiresCredential: true,
    notes: [
      'Official PostNord developer portal includes location APIs for Swedish postal-code and locality use cases.',
      'Record as credentialed source metadata; do not bundle API keys or production responses.',
    ],
  },
  {
    id: 'pdok-bag',
    countryCodes: ['NL'],
    label: 'PDOK BAG API',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'address',
    url: 'https://api.pdok.nl/kadaster/bag/ogc/v2',
    sourceNames: ['pdok', 'bag', 'basisregistratie adressen en gebouwen'],
    openSourceIds: ['pdok-bag'],
    requiresCredential: false,
    notes: ['Official Dutch base registration for addresses and buildings; combine postcode with house number.'],
  },
  {
    id: 'cbs-nl-postcode-areas',
    countryCodes: ['NL'],
    label: 'CBS PC4, PC5, and PC6 postcode areas',
    authority: 'official-derived-open-source',
    trustTier: 'official-derived',
    availability: 'bulk-open-data',
    depth: 'postcode',
    url: 'https://www.cbs.nl/nl-nl/dossier/nederland-regionaal/geografische-data/gegevens-per-postcode',
    sourceNames: ['cbs postcode', 'cbs pc4', 'cbs pc5', 'cbs pc6', 'esri nederland postcode'],
    openSourceIds: ['cbs-nl-postcode-areas'],
    requiresCredential: false,
    notes: ['CBS distributes attributed postcode areas using geometry derived by Esri Nederland from BAG addresses.'],
  },
  {
    id: 'gnaf-au',
    countryCodes: ['AU'],
    label: 'Geocoded National Address File (G-NAF)',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'address',
    url: 'https://data.gov.au/data/dataset/geocoded-national-address-file-g-naf',
    sourceNames: ['g-naf', 'gnaf', 'geocoded national address file'],
    openSourceIds: ['gnaf-au'],
    requiresCredential: false,
    notes: ['Official Australian open address index; postal deliverability needs secondary evidence.'],
  },
  {
    id: 'nz-post-pnf',
    countryCodes: ['NZ'],
    label: 'NZ Post Postcode Network File',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'licensed-bulk-data',
    depth: 'postcode',
    url: 'https://www.nzpost.co.nz/business/sending-within-nz/quality-addressing/postcode-network-file',
    sourceNames: ['nz post pnf', 'postcode network file', 'new zealand postcode network'],
    openSourceIds: ['nz-post-postcode-network'],
    requiresCredential: true,
    notes: ['Authoritative six-monthly postcode network geometry; paid licence and redistribution rights must be enforced.'],
  },
  {
    id: 'nz-post',
    countryCodes: ['NZ'],
    label: 'NZ Post PAF and Address Checker',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'commercial-or-restricted',
    depth: 'delivery-point',
    url: 'https://www.nzpost.co.nz/business/terms-and-conditions/addressing-api',
    sourceNames: ['nz post', 'new zealand post', 'postal address file', 'paf nz', 'address checker'],
    openSourceIds: ['nz-post-postcode-network'],
    requiresCredential: true,
    notes: ['Official postal validation path with licensed and API Restricted Data; scraping, bulk caching, and unapproved redistribution are prohibited.'],
  },
  {
    id: 'linz-nz-address-data',
    countryCodes: ['NZ'],
    label: 'LINZ New Zealand Address Data',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'address',
    url: 'https://data.linz.govt.nz/layer/123113-nz-addresses/',
    sourceNames: ['linz', 'linz address', 'new zealand address data', 'linz data service'],
    openSourceIds: ['linz-nz-addresses', 'linz-nz-building-outlines', 'linz-data-service'],
    requiresCredential: false,
    notes: ['Official open New Zealand address points under CC BY 4.0; use NZ Post evidence for postcode assignment and a source-backed relation for definitive building display.'],
  },
  {
    id: 'posturinn-is-postcodes',
    countryCodes: ['IS'],
    label: 'Pósturinn Iceland Postcode Regions',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://posturinn.is/einstaklingar/ymsar-upplysingar/verdskra/svaedaskipting-postnumera/',
    sourceNames: ['pósturinn', 'islandspostur', 'iceland post', 'iceland postcode regions'],
    openSourceIds: ['posturinn-iceland-postcodes'],
    requiresCredential: false,
    notes: ['Official operator routing and service classification; public pages are reference evidence, not bulk geometry or a deliverability API.'],
  },
  {
    id: 'natt-is50v-postcode-boundaries',
    countryCodes: ['IS'],
    label: 'Náttúrufræðistofnun IS 50V Postcode Boundaries',
    authority: 'official-open-data',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'postcode',
    url: 'https://www.natt.is/en/resources/geospatial-data/base-map-data',
    sourceNames: ['is 50v postcode', 'natt postcode boundaries', 'iceland postcode polygons'],
    openSourceIds: ['natt-is50v-postcode-boundaries'],
    requiresCredential: false,
    notes: ['Official public postcode-area geometry at 1:50,000; pin layer release, metadata, terms, attribution, CRS, and digest.'],
  },
  {
    id: 'hms-is-address-register',
    countryCodes: ['IS'],
    label: 'HMS Staðfangaskrá Iceland Address Register',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'address',
    url: 'https://hms.is/gogn-og-maelabord/grunngogntilnidurhals/stadfangaskra',
    sourceNames: ['hms staðfangaskrá', 'stadfangaskra', 'iceland address register', 'hms addresses'],
    openSourceIds: ['hms-iceland-address-register'],
    requiresCredential: false,
    notes: ['Official weekly address points with postcode, stable identifiers, coordinate type, review state, and accuracy; address evidence is not a delivery guarantee or footprint.'],
  },
  {
    id: 'natt-is50v-buildings',
    countryCodes: ['IS'],
    label: 'Náttúrufræðistofnun IS 50V Buildings',
    authority: 'official-open-data',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'building',
    url: 'https://www.natt.is/en/resources/geospatial-data/base-map-data',
    sourceNames: ['is 50v buildings', 'natt buildings', 'iceland base map buildings'],
    openSourceIds: ['natt-is50v-buildings'],
    requiresCredential: false,
    notes: ['Official topographic building geometry at 1:50,000; proximity alone is not an exact HMS address-to-building relationship.'],
  },
  {
    id: 'poste-italiane-cap-search',
    countryCodes: ['IT'],
    label: 'Poste Italiane CAP Search',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://www.poste.it/cap',
    sourceNames: ['poste italiane', 'poste cap', 'cerca cap', 'italy cap search'],
    openSourceIds: ['poste-italiane-cap-search'],
    requiresCredential: false,
    notes: ['Official current CAP and change reference; public search is not a bulk-open dataset, official polygon layer, or delivery guarantee.'],
  },
  {
    id: 'poste-italiane-cap-professional',
    countryCodes: ['IT'],
    label: 'Poste Italiane CAP Professional',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'licensed-bulk-data',
    depth: 'street',
    url: 'https://business.poste.it/professionisti-imprese/prodotti/cap-professional.html',
    sourceNames: ['cap professional', 'poste cap professional', 'poste italiane toponomastica'],
    openSourceIds: ['poste-italiane-cap-professional'],
    requiresCredential: true,
    notes: ['Official licensed locality, multiCAP city-zone, street-arc and civic-range assignments; enforce contract-specific caching, derivation, and redistribution rights.'],
  },
  {
    id: 'anncsu-it-addresses',
    countryCodes: ['IT'],
    label: 'ANNCSU Streets and Civic Numbers',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'address',
    url: 'https://www.anncsu.gov.it/it/consultazione-dellarchivio/open-data/index.html',
    sourceNames: ['anncsu', 'archivio nazionale numeri civici', 'italy civic numbers'],
    openSourceIds: ['anncsu-italy-addresses'],
    requiresCredential: false,
    notes: ['Official CC BY 4.0 street and civic-number data, monthly in bulk and daily by API; it is not Poste CAP assignment or exact building-link evidence.'],
  },
  {
    id: 'istat-it-admin-boundaries',
    countryCodes: ['IT'],
    label: 'ISTAT Administrative Boundaries',
    authority: 'official-open-data',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'geo-only',
    url: 'https://www.istat.it/notizia/confini-delle-unita-amministrative-a-fini-statistici-al-1-gennaio-2018-2/',
    sourceNames: ['istat boundaries', 'istat confini amministrativi', 'italy municipality boundaries'],
    openSourceIds: ['istat-italy-admin-boundaries'],
    requiresCredential: false,
    notes: ['Official administrative geometry under ISTAT attribution terms; useful as context or a rights-cleared derivation clip, never an official CAP boundary.'],
  },
  {
    id: 'italy-regional-dbgt-buildings',
    countryCodes: ['IT'],
    label: 'Italian Regional and Municipal DBGT Buildings',
    authority: 'government',
    trustTier: 'official',
    availability: 'bulk-open-data',
    depth: 'building',
    url: 'https://geodati.gov.it/geoportale/datiterritoriali/regole-tecniche',
    sourceNames: ['dbgt', 'italy regional buildings', 'database geotopografico'],
    openSourceIds: ['italy-regional-dbgt-buildings'],
    requiresCredential: false,
    notes: ['DBGT is a common national specification, while implementations and licences are federated; review each dataset and require a source-backed civic-to-building link.'],
  },
  {
    id: 'dawa-denmark',
    countryCodes: ['DK'],
    label: 'Danish Address Web API (DAWA)',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'address',
    url: 'https://api.dataforsyningen.dk/postnumre',
    sourceNames: ['dawa', 'dataforsyningen', 'danish address web api', 'postnumre'],
    openSourceIds: ['dataforsyningen-denmark', 'danish-address-register-dar'],
    requiresCredential: false,
    notes: ['Official Danish address and postcode API.'],
  },
  {
    id: 'hk-csdi',
    countryCodes: ['HK'],
    label: 'Hong Kong CSDI / LandsD address and geodata',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'geo-only',
    url: 'https://portal.csdi.gov.hk/',
    sourceNames: ['hk-csdi', 'csdi', 'landsd', 'hk-als'],
    openSourceIds: ['csdi-hk', 'landsd-hk', 'hk-csdi', 'hk-als'],
    requiresCredential: false,
    notes: ['Hong Kong does not use normal postcodes; verify with official address/geodata evidence.'],
  },
  {
    id: 'macao-geoguide',
    countryCodes: ['MO'],
    label: 'Macao DSCC / GeoGuide',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'geo-only',
    url: 'https://www.dscc.gov.mo/',
    sourceNames: ['dscc', 'geoguide', 'macao geoguide'],
    openSourceIds: ['dscc-macao', 'geoguide-macao'],
    requiresCredential: false,
    notes: ['Macau does not use normal postcodes; verify with official geodata and building/street evidence.'],
  },
  {
    id: 'qatar-gis',
    countryCodes: ['QA'],
    label: 'Qatar GIS / official geodata',
    authority: 'government',
    trustTier: 'official',
    availability: 'public-api',
    depth: 'geo-only',
    url: 'https://geoportal.gisqatar.org.qa/',
    sourceNames: ['qatar gis', 'qatar-gis-geoportal'],
    openSourceIds: ['qatar-gis-geoportal'],
    requiresCredential: false,
    notes: ['Use official geodata for building-zone-street style addressing.'],
  },
  {
    id: 'makani-dubai',
    countryCodes: ['AE'],
    label: 'Dubai Makani / UAE official geodata',
    authority: 'government',
    trustTier: 'official',
    availability: 'public-api',
    depth: 'geo-only',
    url: 'https://www.makani.ae/',
    sourceNames: ['makani', 'dubai makani'],
    openSourceIds: ['makani-dubai-open-data'],
    requiresCredential: false,
    notes: ['Use official geodata and local address systems where no normal postcode is used.'],
  },
  {
    id: 'antarctic-research-stations',
    countryCodes: ['AQ'],
    label: 'Antarctic research station and open geodata references',
    authority: 'official-open-data',
    trustTier: 'official',
    availability: 'bulk-open-data',
    depth: 'geo-only',
    url: 'https://github.com/SCAR/antimeridian',
    sourceNames: ['antarctic-research-stations', 'scar', 'antarctic station'],
    openSourceIds: ['antarctic-research-stations'],
    requiresCredential: false,
    notes: ['Use station/operator and coordinate evidence rather than normal postal-code validation.'],
  },
  {
    id: 'correios-angola',
    countryCodes: ['AO'],
    label: 'Correios de Angola',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://www.correiosdeangola.ao/',
    sourceNames: ['correios de angola', 'encta'],
    openSourceIds: [],
    requiresCredential: false,
    notes: ['Official Angolan postal operator; use for postal-network evidence until a machine-readable postcode file is connected.'],
  },
  {
    id: 'la-poste-cote-divoire',
    countryCodes: ['CI'],
    label: "La Poste de Cote d'Ivoire official portal",
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://www.laposte.ci/',
    sourceNames: ["la poste cote d'ivoire", 'laposte.ci', 'poste ci', 'annuaire postal cote divoire'],
    openSourceIds: ['la-poste-cote-divoire'],
    requiresCredential: false,
    notes: ["Official Cote d'Ivoire postal operator portal; use as current postal-network evidence while direct public postcode lookup remains limited."],
  },
  {
    id: 'correios-cabo-verde',
    countryCodes: ['CV'],
    label: 'Correios de Cabo Verde postcode reference',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://correios.cv/faq',
    sourceNames: ['correios de cabo verde', 'correios.cv', 'codigo postal cabo verde', 'pesquisar codigos postais cabo verde'],
    openSourceIds: ['correios-cabo-verde'],
    requiresCredential: false,
    notes: ['Official Cabo Verde postal operator FAQ and postcode guidance, including public postcode examples and postcode-search instructions.'],
  },
  {
    id: 'la-poste-benin',
    countryCodes: ['BJ'],
    label: 'La Poste du Benin agency directory',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://laposte.bj/nos-agences/',
    sourceNames: ['la poste du benin', 'laposte.bj', 'poste benin'],
    openSourceIds: ['la-poste-benin'],
    requiresCredential: false,
    notes: ['Official Benin postal operator directory; use as postal-network evidence while direct public postcode tooling remains limited.'],
  },
  {
    id: 'la-poste-burkina',
    countryCodes: ['BF'],
    label: 'La Poste Burkina Faso postcode search',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://codespostaux.laposte.bf/',
    sourceNames: ['la poste burkina faso', 'laposte.bf', 'codes postaux burkina'],
    openSourceIds: ['la-poste-burkina'],
    requiresCredential: false,
    notes: ['Official Burkina Faso postal operator postcode search for locality and five-digit postal-code confirmation.'],
  },
  {
    id: 'gambia-post-services',
    countryCodes: ['GM'],
    label: 'Gambia Postal Services Corporation',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://gambiapost.gm/',
    sourceNames: ['gambia postal services corporation', 'gampost', 'gambiapost.gm'],
    openSourceIds: ['gambia-post-services'],
    requiresCredential: false,
    notes: ['Official GAMPOST portal; use as current postal-operator evidence while direct public postcode search remains limited.'],
  },
  {
    id: 'mopt-liberia-postal-services',
    countryCodes: ['LR'],
    label: 'Liberia Ministry of Posts and Telecommunications',
    authority: 'government',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://mopt.gov.lr/about-us/',
    sourceNames: [
      'liberia ministry of posts and telecommunications',
      'mopt liberia',
      'liberia postal services',
      'liberia postmaster general',
      'liberia post office',
    ],
    openSourceIds: ['mopt-liberia-postal-services'],
    requiresCredential: false,
    notes: ['Official Liberia postal authority page describing the ministry mandate to provide postal services nationwide and linking current postal-service resources.'],
  },
  {
    id: 'guinee-poste',
    countryCodes: ['GN'],
    label: 'La Poste Guineenne official portal',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://www.laposte.gn/',
    sourceNames: ['la poste guineenne', 'laposte.gn', 'poste gn sa', 'guinee poste'],
    openSourceIds: ['guinee-poste'],
    requiresCredential: false,
    notes: ['Official Guinea postal operator portal; use as current postal-network evidence while direct public postcode lookup remains limited.'],
  },
  {
    id: 'la-poste-senegal-codes',
    countryCodes: ['SN'],
    label: 'La Poste Senegal postcode directory',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://www.laposte.sn/code-postal-senegal/',
    sourceNames: ['la poste senegal', 'laposte.sn', 'code postal senegal', 'code postal du senegal'],
    openSourceIds: ['la-poste-senegal-codes'],
    requiresCredential: false,
    notes: ['Official La Poste Senegal postcode directory for five-digit code, locality, and nearby post-office lookup.'],
  },
  {
    id: 'societe-postes-togo',
    countryCodes: ['TG'],
    label: 'Societe des Postes du Togo office network',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://www.laposte.tg/bureaux-poste',
    sourceNames: ['societe des postes du togo', 'la poste togo', 'laposte.tg', 'bureaux poste togo'],
    openSourceIds: ['societe-postes-togo'],
    requiresCredential: false,
    notes: ['Official Togo postal operator office-network directory and service portal; use as current postal-reference evidence while direct postcode search remains limited.'],
  },
  {
    id: 'la-poste-mali',
    countryCodes: ['ML'],
    label: 'La Poste du Mali official portal',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://laposte.ml/',
    sourceNames: ['la poste du mali', 'laposte.ml', 'poste du mali'],
    openSourceIds: ['la-poste-mali'],
    requiresCredential: false,
    notes: ['Official Mali postal operator portal; use as current postal-network evidence while direct public postcode lookup remains limited.'],
  },
  {
    id: 'niger-poste',
    countryCodes: ['NE'],
    label: 'Niger Poste official portal',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://nigerposte.ne/',
    sourceNames: ['niger poste', 'nigerposte.ne', 'office national de la poste'],
    openSourceIds: ['niger-poste'],
    requiresCredential: false,
    notes: ['Official Niger Poste portal with postal-box, agency, and code-postal service pages; use as current postal-reference evidence.'],
  },
  {
    id: 'salpost-sierra-leone',
    countryCodes: ['SL'],
    label: 'Sierra Leone Postal Services Ltd (SALPOST)',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://salpost.gov.sl/',
    sourceNames: ['salpost', 'sierra leone postal services', 'salpost.gov.sl'],
    openSourceIds: ['salpost-sierra-leone'],
    requiresCredential: false,
    notes: ['Official Sierra Leone postal operator portal; use as postal-network evidence while direct public postcode lookup remains limited.'],
  },
  {
    id: 'algerie-poste',
    countryCodes: ['DZ'],
    label: 'Algerie Poste postal offices and postcodes',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://www.poste.dz/customer/bureaux_postaux',
    sourceNames: ['algerie poste', 'algerie-poste', 'poste.dz', 'bureaux postaux'],
    openSourceIds: ['algerie-poste'],
    requiresCredential: false,
    notes: ['Official Algeria Post office lookup; use as official web evidence for code/locality checks.'],
  },
  {
    id: 'egypt-post',
    countryCodes: ['EG'],
    label: 'Egypt Post',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://www.egyptpost.org/',
    sourceNames: ['egypt post', 'egyptpost'],
    openSourceIds: [],
    requiresCredential: false,
    notes: ['Official Egyptian postal operator; connect a postal-code lookup endpoint when confirmed.'],
  },
  {
    id: 'nipost-postcode',
    countryCodes: ['NG'],
    label: 'Nigerian Postal Service Postcode Finder',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://nipost.gov.ng/postcode-finder/',
    sourceNames: ['nipost', 'nipost postcode finder', 'nigerian postal service', 'nigerian postal service postcode finder'],
    openSourceIds: ['nipost-postcode'],
    requiresCredential: false,
    notes: ['Official NIPOST postcode finder for Nigerian state, city, and postcode lookup.'],
  },
  {
    id: 'ghanapostgps',
    countryCodes: ['GH'],
    label: 'GhanaPostGPS National Digital Address System',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'address',
    url: 'https://www.ghanapostgps.com/',
    sourceNames: ['ghanapostgps', 'ghana post gps', 'ghana digital address', 'national digital address system'],
    openSourceIds: ['ghanapostgps'],
    requiresCredential: false,
    notes: ['Official Ghana digital property addressing system by Ghana Post/Government of Ghana.'],
  },
  {
    id: 'posta-kenya',
    countryCodes: ['KE'],
    label: 'Postal Corporation of Kenya post offices',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://posta.co.ke/post-offices/',
    sourceNames: ['postal corporation of kenya', 'posta kenya', 'posta.co.ke'],
    openSourceIds: ['posta-kenya'],
    requiresCredential: false,
    notes: ['Official Kenya postal operator post-office directory; use for postcode/post-office confirmation.'],
  },
  {
    id: 'poste-maroc-codepostal',
    countryCodes: ['MA'],
    label: 'Poste Maroc postcode directory',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://codepostal.ma/default.aspx',
    sourceNames: ['poste maroc', 'codepostal.ma', 'barid al-maghrib'],
    openSourceIds: ['poste-maroc-codepostal'],
    requiresCredential: false,
    notes: ['Official Poste Maroc postcode search/directory.'],
  },
  {
    id: 'libya-post-services',
    countryCodes: ['LY'],
    label: 'Libya Post services portal',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://libyapost.ly/en/services/',
    sourceNames: ['libya post', 'libyapost', 'libyapost.ly'],
    openSourceIds: ['libya-post-services'],
    requiresCredential: false,
    notes: ['Official Libya Post services reference; use as postal-network evidence until a direct public postcode lookup is confirmed.'],
  },
  {
    id: 'mauripost',
    countryCodes: ['MR'],
    label: 'MAURIPOST official portal',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://www.mauripost.mr/',
    sourceNames: ['mauripost', 'mauri post', 'mauripost.mr'],
    openSourceIds: ['mauripost'],
    requiresCredential: false,
    notes: ['Official Mauritania postal operator portal; use as postal-network evidence while public postcode tooling remains limited.'],
  },
  {
    id: 'la-poste-tunisienne-codes',
    countryCodes: ['TN'],
    label: 'La Poste Tunisienne postcode search',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://www.laposte.tn/codes.php',
    sourceNames: ['la poste tunisienne', 'laposte.tn', 'poste tunisienne'],
    openSourceIds: ['la-poste-tunisienne-codes'],
    requiresCredential: false,
    notes: ['Official Tunisian Post postcode search.'],
  },
  {
    id: 'sudapost',
    countryCodes: ['SD'],
    label: 'Sudapost official site',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://sudapost.sd/wp/',
    sourceNames: ['sudapost', 'sudan post', 'sudapost.sd'],
    openSourceIds: ['sudapost'],
    requiresCredential: false,
    notes: ['Official Sudan Post site; use as current postal-operator evidence until a stable public postcode search endpoint is confirmed.'],
  },
  {
    id: 'correios-mocambique-codigos-postais',
    countryCodes: ['MZ'],
    label: 'Correios de Mocambique codigos postais',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://www.correios.co.mz/?cod=11&pagina=codigo',
    sourceNames: ['correios de mocambique', 'correios mocambique', 'correios.co.mz', 'codigos postais mocambique'],
    openSourceIds: ['correios-mocambique-codigos-postais'],
    requiresCredential: false,
    notes: ['Official Correios de Mocambique postal-code directory; use as current postcode and locality evidence from the national postal operator.'],
  },
  {
    id: 'ethiopost-branches',
    countryCodes: ['ET'],
    label: 'Ethiopost branch locator',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://ethio.post/branches/',
    sourceNames: ['ethiopost', 'ethio.post', 'ethiopia post', 'ethiopost branch locator'],
    openSourceIds: ['ethiopost-branches'],
    requiresCredential: false,
    notes: ['Official Ethiopost branch locator and service directory; use as current postal-operator evidence while a dedicated public postcode search endpoint remains limited.'],
  },
  {
    id: 'mcpt-djibouti-poste',
    countryCodes: ['DJ'],
    label: 'Djibouti MCPT La Poste de Djibouti page',
    authority: 'government',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://communication.gouv.dj/structures-sous-tutelle/',
    sourceNames: [
      'la poste de djibouti',
      'djibouti mcpt',
      'communication gouv dj',
      'structures sous tutelle',
      'poste de djibouti',
    ],
    openSourceIds: ['mcpt-djibouti-poste'],
    requiresCredential: false,
    notes: ['Official Djibouti ministry page naming La Poste de Djibouti as the national postal service and linking the operator site while direct public operator endpoints remain unstable.'],
  },
  {
    id: 'snpsf-comores-poste',
    countryCodes: ['KM'],
    label: 'SNPSF Comoros postal services',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://www.snpsf.com/poste',
    sourceNames: [
      'snpsf',
      'societe nationale des postes et services financiers',
      'snpsf comores',
      'comores poste',
      'poste comores',
    ],
    openSourceIds: ['snpsf-comores-poste'],
    requiresCredential: false,
    notes: [
      'Official Comoros postal operator portal with postal services, tracking, EMS, and postal-guide references.',
      'Corroborated by the September 13, 2023 Comorian postal-regulator decree published on justice.gouv.km.',
    ],
  },
  {
    id: 'somalia-moct-posta',
    countryCodes: ['SO'],
    label: 'Somalia MOCT Postal Service page',
    authority: 'government',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://moct.gov.so/en/posta/',
    sourceNames: [
      'somalia moct posta',
      'somalia postal service',
      'somali national postal service',
      'moct posta',
      'posta somalia',
    ],
    openSourceIds: ['somalia-moct-posta'],
    requiresCredential: false,
    notes: ['Official Somalia ministry postal-service department page documenting the national postal service; pair with current MOCT postal-exchange announcements for live operational evidence while public postcode tooling remains limited.'],
  },
  {
    id: 'south-sudan-nca-postal-sector',
    countryCodes: ['SS'],
    label: 'South Sudan NCA postal-sector oversight',
    authority: 'government',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://www.nca.gov.ss/',
    sourceNames: [
      'south sudan nca',
      'national communication authority',
      'south sudan postal services',
      'postal and courier sectors',
      'nca south sudan',
    ],
    openSourceIds: ['south-sudan-nca-postal-sector'],
    requiresCredential: false,
    notes: ['Official South Sudan National Communication Authority site stating that the agency regulates the postal and courier sectors; use as current country-specific official postal evidence while direct public postal-operator tooling remains limited.'],
  },
  {
    id: 'malawi-postcodes-macra',
    countryCodes: ['MW'],
    label: 'MACRA Malawi post codes',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://macra.mw/post-codes/',
    sourceNames: ['macra', 'malawi post codes', 'malawi postcodes', 'malawi communications regulatory authority', 'malawi posts corporation'],
    openSourceIds: ['malawi-postcodes-macra'],
    requiresCredential: false,
    notes: ['Official Malawi Communications Regulatory Authority postcode table; pair with Malawi Posts operator references for current postcode and locality evidence.'],
  },
  {
    id: 'posta-uganda-physical-address',
    countryCodes: ['UG'],
    label: 'Posta Uganda physical address service',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://ugapost.co.ug/our-services/physical-address/',
    sourceNames: ['posta uganda', 'uganda post', 'ugapost', 'physical address', 'eposta ug'],
    openSourceIds: ['posta-uganda-physical-address'],
    requiresCredential: false,
    notes: ['Official Posta Uganda physical-address application guidance; use as current postal-network evidence while postcode discovery remains service-led.'],
  },
  {
    id: 'nampost-postal-codes',
    countryCodes: ['NA'],
    label: 'NamPost postal codes',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://www.nampost.com.na/postal/postal-codes',
    sourceNames: ['nampost', 'nam post', 'nampost postal codes', 'namibia post'],
    openSourceIds: ['nampost-postal-codes'],
    requiresCredential: false,
    notes: ['Official NamPost public postal-code directory grouped by political region and locality.'],
  },
  {
    id: 'seychelles-post-po-box-directory',
    countryCodes: ['SC'],
    label: 'Seychelles Post P.O. Box directory',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://www.seychelles-post.com/poboxdirectory.php',
    sourceNames: ['seychelles post', 'seychelles postal services', 'p.o. box directory', 'poboxdirectory'],
    openSourceIds: ['seychelles-post-po-box-directory'],
    requiresCredential: false,
    notes: ['Official Seychelles Postal Services directory search and service portal for P.O. Box routing and operator reference.'],
  },
  {
    id: 'tcra-tanzania-postcode',
    countryCodes: ['TZ'],
    label: 'Tanzania postcode service',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://www.tcra.go.tz/services/postcode',
    sourceNames: ['tcra postcode', 'tanzania postcode', 'posta tanzania', 'tanzania posts corporation'],
    openSourceIds: [],
    requiresCredential: false,
    notes: ['Official Tanzania Communications Regulatory Authority postcode service.'],
  },
  {
    id: 'rwanda-national-post-office',
    countryCodes: ['RW'],
    label: 'National Post Office of Rwanda',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://i-posita.rw/',
    sourceNames: ['national post office of rwanda', 'i-posita', 'iposita'],
    openSourceIds: [],
    requiresCredential: false,
    notes: ['Official Rwandan postal operator; use as official postal-network source where postcodes are limited.'],
  },
  {
    id: 'zampost',
    countryCodes: ['ZM'],
    label: 'Zambia Postal Services Corporation',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://www.zampost.com.zm/',
    sourceNames: ['zampost', 'zambia postal services corporation'],
    openSourceIds: ['zampost'],
    requiresCredential: false,
    notes: ['Official Zambia postal operator; pair with UPU postcode data when machine-readable local data is not available.'],
  },
  {
    id: 'zimpost',
    countryCodes: ['ZW'],
    label: 'Zimbabwe Posts official portal',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://www.zimpost.co.zw/',
    sourceNames: ['zimpost', 'zimbabwe posts', 'zimpost.co.zw'],
    openSourceIds: ['zimpost'],
    requiresCredential: false,
    notes: ['Official Zimbabwe postal operator portal; use as current postal-network evidence while public postcode search remains limited.'],
  },
  {
    id: 'paositra-malagasy',
    countryCodes: ['MG'],
    label: 'Paositra Malagasy',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'postcode',
    url: 'https://www.paositramalagasy.mg/cds',
    sourceNames: ['paositra malagasy', 'madagascar post'],
    openSourceIds: [],
    requiresCredential: false,
    notes: ['Official Madagascar postal operator; use for postal-network evidence until postcode bulk data is connected.'],
  },
  {
    id: 'mauritius-post-postcode',
    countryCodes: ['MU'],
    label: 'Mauritius Post postcode finder',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://www.mauritiuspost.mu/',
    sourceNames: ['mauritius post', 'postcode finder'],
    openSourceIds: [],
    requiresCredential: false,
    notes: ['Official Mauritius Post website exposes a postcode finder.'],
  },
  {
    id: 'botswanapost',
    countryCodes: ['BW'],
    label: 'BotswanaPost',
    authority: 'postal-operator',
    trustTier: 'official',
    availability: 'web-search',
    depth: 'locality',
    url: 'https://www.botswanapost.co.bw/',
    sourceNames: ['botswanapost', 'botswana post'],
    openSourceIds: [],
    requiresCredential: false,
    notes: ['Official Botswana postal operator; connect a confirmed postcode lookup when available.'],
  },
  {
    id: 'austrian-post-postcode',
    countryCodes: ['AT'],
    label: 'Austrian Post postal encyclopedia',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'postcode',
    url: 'https://www.post.at/en/g/c/postal-encyclopedia',
    sourceNames: ['austrian post', 'oesterreichische post', 'post.at', 'postal encyclopedia'],
    openSourceIds: [],
    requiresCredential: false,
    notes: ['Official Austrian Post postcode and destination-location directory.'],
  },
  {
    id: 'swiss-post-postcodes',
    countryCodes: ['CH', 'LI'],
    label: 'Swiss Post postcodes and address geodata',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'web-search',
    depth: 'street',
    url: 'https://www.post.ch/en/business-solutions/address-management/address-and-geodata',
    sourceNames: ['swiss post', 'post.ch', 'swiss postcodes', 'plz suche', 'street directory with sorting data', 'geopost zipcodes'],
    openSourceIds: ['swiss-post-postcodes'],
    requiresCredential: false,
    notes: [
      'Official postcode/place search and regularly updated street directory provide operator assignment and sorting evidence.',
      'NPA6, GeoPost areas, delivery coordinates and other products remain contract-partitioned; public search does not grant unrestricted redistribution or prove deliverability.',
    ],
  },
  {
    id: 'swisstopo-plzo-postal-localities',
    countryCodes: ['CH', 'LI'],
    label: 'swisstopo Official Directory of Towns and Cities (PLZO_CH)',
    authority: 'official-open-data',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'postcode',
    url: 'https://www.swisstopo.admin.ch/en/official-directory-of-towns-and-cities',
    sourceNames: ['plzo ch', 'swisstopo postcode perimeter', 'official directory towns and cities', 'npa6'],
    openSourceIds: ['swisstopo-plzo-postal-localities'],
    requiresCredential: false,
    notes: [
      'Official monthly four-digit postcode, NPA6 and locality perimeters for domicile-address postcode types under swisstopo OGD attribution terms.',
      'Special, professional, company and administrative postcode types may be absent and must not be assigned invented residential polygons.',
    ],
  },
  {
    id: 'swisstopo-building-address-directory',
    countryCodes: ['CH', 'LI'],
    label: 'swisstopo Official Directory of Building Addresses',
    authority: 'official-open-data',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'address',
    url: 'https://www.swisstopo.admin.ch/en/official-directory-of-building-addresses',
    sourceNames: ['official building address directory', 'egaid', 'egid edid', 'swisstopo building addresses'],
    openSourceIds: ['swisstopo-building-address-directory'],
    requiresCredential: false,
    notes: ['Official daily building-entrance addresses and LV95 points; preserve EGAID, EGID, EDID, status, release and cadastral coordinate provenance.'],
  },
  {
    id: 'swiss-federal-gwr',
    countryCodes: ['CH'],
    label: 'Swiss Federal Register of Buildings and Dwellings (GWR)',
    authority: 'government',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'building',
    url: 'https://www.housing-stat.ch/',
    sourceNames: ['gwr', 'rbd', 'regbl', 'federal register buildings dwellings', 'egid', 'edid'],
    openSourceIds: ['swiss-federal-gwr'],
    requiresCredential: false,
    notes: ['Official federal building and entrance identity/status evidence; public AGID output excludes dwelling EWID, occupants, owners and non-public register attributes.'],
  },
  {
    id: 'swisstopo-swissbuildings3d',
    countryCodes: ['CH', 'LI'],
    label: 'swisstopo swissBUILDINGS3D 3.0 Beta',
    authority: 'official-open-data',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'building',
    url: 'https://www.swisstopo.admin.ch/en/landscape-model-swissbuildings3d-3-0-beta',
    sourceNames: ['swissbuildings3d', 'swisstopo 3d buildings', 'egid building model'],
    openSourceIds: ['swisstopo-swissbuildings3d'],
    requiresCredential: false,
    notes: ['Official 3D geometry under swisstopo OGD terms, with phased canton/tile EGID integration; exact building linkage requires an identical EGID in the pinned edition.'],
  },
  {
    id: 'swisstopo-swissboundaries3d',
    countryCodes: ['CH', 'LI'],
    label: 'swisstopo swissBOUNDARIES3D',
    authority: 'official-open-data',
    trustTier: 'authoritative',
    availability: 'bulk-open-data',
    depth: 'geo-only',
    url: 'https://www.swisstopo.admin.ch/en/landscape-model-swissboundaries3d',
    sourceNames: ['swissboundaries3d', 'swisstopo municipal boundaries', 'swiss canton boundaries'],
    openSourceIds: ['swisstopo-swissboundaries3d'],
    requiresCredential: false,
    notes: ['Official national, canton, district and municipality geometry under swisstopo OGD terms; administrative boundaries are not postcode/locality perimeters.'],
  },
  {
    id: 'postnl-postcode-finder',
    countryCodes: ['NL'],
    label: 'PostNL postcode finder',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'public-api',
    depth: 'address',
    url: 'https://www.postnl.nl/en/find-a-postcode/',
    sourceNames: ['postnl', 'postcode finder', 'find a postcode'],
    openSourceIds: [],
    requiresCredential: false,
    notes: ['Official PostNL postcode/address finder.'],
  },
  {
    id: 'postnl-postcode-table',
    countryCodes: ['NL'],
    label: 'PostNL postcode table',
    authority: 'postal-operator',
    trustTier: 'authoritative',
    availability: 'licensed-bulk-data',
    depth: 'address',
    url: 'https://www.postnl.nl/api/assets/blt43aa441bfc1e29f2/bltfcd225acf8c54b1e/69aad68afa2e53eeaaf76e79/postcode-table-file-structure.pdf',
    sourceNames: ['postnl postcode table', 'pct-h'],
    openSourceIds: [],
    requiresCredential: true,
    notes: ['Official PostNL postcode table documentation for address-level Dutch postcode data.'],
  },
  ...GLOBAL_OPEN_REFERENCE_SOURCES,
  ...GLOBAL_OFFICIAL_POSTAL_SOURCES,
];

const TRUST_ORDER: Record<PostalSourceTrustTier, number> = {
  authoritative: 6,
  official: 5,
  'official-derived': 4,
  'open-reference': 3,
  community: 2,
  weak: 1,
};

const AVAILABILITY_ORDER: Record<PostalSourceAvailability, number> = {
  'public-api': 8,
  'auth-required-api': 7,
  'bulk-open-data': 6,
  'licensed-bulk-data': 5,
  'commercial-or-restricted': 4,
  'web-search': 3,
  'no-normal-postcode': 2,
  unknown: 1,
};

const STRONG_TIERS = new Set<PostalSourceTrustTier>([
  'authoritative',
  'official',
  'official-derived',
  'open-reference',
]);

const WEAK_SOURCE_PATTERNS = [
  /datahub/i,
  /postal-codes-json/i,
  /postalcodes\.info/i,
  /spotzi/i,
  /scrape4u/i,
  /regional table/i,
  /candidate/i,
];

const POSTAL_OPERATOR_PATTERNS = [
  /\bposte\b/i,
  /\bposten\b/i,
  /\bpostnord\b/i,
  /\bcorreos\b/i,
  /\bcorreios\b/i,
  /\bpoczta\b/i,
  /\bposta\b/i,
  /\bptt\b/i,
  /\busps\b/i,
  /\broyal mail\b/i,
  /\b4-72\b/i,
  /\bcanada post\b/i,
  /\baustralia post\b/i,
  /\bauspost\b/i,
  /\bjapan post\b/i,
  /\bindia post\b/i,
  /\bqazpost\b/i,
  /\bkazpost\b/i,
  /\bhaypost\b/i,
  /\bepost\b/i,
  /\bphlpost\b/i,
  /\blibanpost\b/i,
  /\bslpost\b/i,
  /\bmaldives post\b/i,
  /\bbhutan post\b/i,
  /\bpakistan post\b/i,
  /\bnepal post\b/i,
  /\bpos malaysia\b/i,
  /\bsingapore post\b/i,
  /\bthailand post\b/i,
  /\bvietnam post\b/i,
  /\bsaudi post\b/i,
  /\boman post\b/i,
];

const clean = (value: unknown) => String(value ?? '').normalize('NFKC').replace(/[\u3000\s]+/g, ' ').trim();

function normalizeCountryCode(value: unknown) {
  const normalized = clean(value).toUpperCase().replace(/[^A-Z0-9_-]/g, '');
  return normalized === 'UK' ? 'GB' : normalized;
}

function normalizeTextKey(value: unknown) {
  return clean(value).toLowerCase().replace(/[^\p{Letter}\p{Number}]+/gu, '');
}

function sourceAppliesToCountry(profile: OfficialPostalSourceProfile, countryCode: string) {
  if (!countryCode || profile.countryCodes.includes('*')) return true;
  return profile.countryCodes.map(normalizeCountryCode).includes(countryCode);
}

function profileMatchesText(profile: OfficialPostalSourceProfile, textKeys: string[]) {
  const profileKeys = [
    profile.id,
    profile.label,
    profile.url,
    ...profile.sourceNames,
    ...profile.openSourceIds,
  ].map(normalizeTextKey).filter(Boolean);

  return textKeys.some(textKey => profileKeys.some(profileKey => (
    textKey.includes(profileKey) || profileKey.includes(textKey)
  )));
}

function sortProfiles(profiles: OfficialPostalSourceProfile[]) {
  return [...profiles].sort((left, right) => {
    const tierDelta = TRUST_ORDER[right.trustTier] - TRUST_ORDER[left.trustTier];
    if (tierDelta) return tierDelta;
    const globalDelta = Number(left.countryCodes.includes('*')) - Number(right.countryCodes.includes('*'));
    if (globalDelta) return globalDelta;
    const availabilityDelta = AVAILABILITY_ORDER[right.availability] - AVAILABILITY_ORDER[left.availability];
    if (availabilityDelta) return availabilityDelta;
    const credentialDelta = Number(left.requiresCredential) - Number(right.requiresCredential);
    if (credentialDelta) return credentialDelta;
    return left.id.localeCompare(right.id);
  });
}

export function getOfficialPostalSourcesForCountry(countryCode: string) {
  const code = normalizeCountryCode(countryCode);
  return sortProfiles(OFFICIAL_POSTAL_SOURCE_CATALOG.filter(profile => sourceAppliesToCountry(profile, code)));
}

export function isPostalReferenceDataSource(profile: OfficialPostalSourceProfile) {
  return profile.sourceRole !== 'legal-framework-only';
}

export function classifyPostalSourceTrust(input: {
  countryCode?: string;
  source?: string | null;
  url?: string | null;
  sourceIds?: string[];
}): PostalSourceClassification {
  const countryCode = normalizeCountryCode(input.countryCode);
  const textKeys = [
    input.source,
    input.url,
    ...(input.sourceIds || []),
  ].map(normalizeTextKey).filter(Boolean);
  const raw = clean([input.source, input.url, ...(input.sourceIds || [])].filter(Boolean).join(' '));

  if (!textKeys.length) {
    return {
      tier: 'weak',
      strength: 'weak',
      reason: 'No postal source identity was supplied.',
      matches: [],
    };
  }

  const matches = sortProfiles(OFFICIAL_POSTAL_SOURCE_CATALOG.filter(profile => (
    sourceAppliesToCountry(profile, countryCode) && profileMatchesText(profile, textKeys)
  )));

  if (matches.length) {
    const postalReferenceMatches = matches.filter(isPostalReferenceDataSource);
    if (!postalReferenceMatches.length) {
      return {
        tier: 'weak',
        strength: 'weak',
        reason: 'Source matches an official legal framework, not a postal-reference dataset; it cannot support postal lookup or address validation.',
        matches,
      };
    }
    const validationEligibleMatches = postalReferenceMatches.filter(profile => (
      profile.validationReadiness !== 'metadata-only'
    ));
    const best = validationEligibleMatches[0];
    if (!best) {
      return {
        tier: 'weak',
        strength: 'weak',
        reason: 'Source matches an official catalog entry retained for metadata only; terms, version, coverage, correction, and quality gates must pass before postal-reference validation.',
        matches,
      };
    }
    if (!STRONG_TIERS.has(best.trustTier) &&
      !WEAK_SOURCE_PATTERNS.some(pattern => pattern.test(raw)) &&
      (/official|government|postal operator|national address|national-address/i.test(raw) ||
        POSTAL_OPERATOR_PATTERNS.some(pattern => pattern.test(raw)))
    ) {
      return {
        tier: 'official',
        strength: 'strong',
        reason: 'Source text includes an official/government or postal-operator signal in addition to weaker fallback references.',
        matches,
      };
    }

    return {
      tier: best.trustTier,
      strength: STRONG_TIERS.has(best.trustTier) ? 'strong' : 'weak',
      reason: `${best.label} matched as ${best.trustTier} (${best.availability}).`,
      matches,
    };
  }

  if (WEAK_SOURCE_PATTERNS.some(pattern => pattern.test(raw))) {
    return {
      tier: 'weak',
      strength: 'weak',
      reason: 'Source matches a weak or community-only postal dataset pattern.',
      matches: [],
    };
  }

  if (/official|government|postal operator|national address|national-address/i.test(raw)) {
    return {
      tier: 'official',
      strength: 'strong',
      reason: 'Source text declares official or government authority but is not yet cataloged.',
      matches: [],
    };
  }

  if (POSTAL_OPERATOR_PATTERNS.some(pattern => pattern.test(raw))) {
    return {
      tier: 'official',
      strength: 'strong',
      reason: 'Source text appears to be a national postal operator or postal-office source but is not yet individually cataloged.',
      matches: [],
    };
  }

  return {
    tier: 'community',
    strength: 'weak',
    reason: 'Source is not in the official postal source catalog yet.',
    matches: [],
  };
}

export function isStrongPostalTrustTier(tier: PostalSourceTrustTier) {
  return STRONG_TIERS.has(tier);
}

export function getPreferredPostalSourceIdsForCountry(countryCode: string) {
  return getOfficialPostalSourcesForCountry(countryCode)
    .filter(isPostalReferenceDataSource)
    .filter(source => source.validationReadiness !== 'metadata-only')
    .filter(source => source.trustTier !== 'weak')
    .map(source => source.id);
}
