import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
type Profile={artifact_scope:string;sources:Array<{source_id:string;assignment_authority:string;geometry_authority:string;redistribution_class:string;bundled_here:boolean}>;artifact_partitions:Array<{id:string}>};
type Manifest={repository:{name:string;country_code:string;maturity:string};release_scope:Record<string,boolean|string>;postal_system:Record<string,string>;promotion:{current_stage:string;hard_blockers:string[]}};
type Fixtures={country_code:string;synthetic:boolean;promotion_eligible:boolean;fixture_policy:{contains_real_addresses:boolean;contains_upstream_rows:boolean;contains_personal_data:boolean;postal_prefix:string;coordinates_are_geographic:boolean;postcodes_are_assignment_evidence:boolean;deliberately_outside_documented_province_prefix_range:boolean};fixtures:Array<{fixture_id:string;synthetic_address:{postcode?:string};expected:{must_not_assert:string[]}}>};
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'); const seedRoot=resolve(root,'data/postal_country_packs/af/postal-context'); const readJson=<T>(name:string)=>JSON.parse(readFileSync(resolve(seedRoot,name),'utf8')) as T;

test('Afghanistan seed separates current six digits, map geometry, P-codes, addresses, buildings, AGID, rights, and privacy',()=>{
 const value=readJson<Manifest>('repository-manifest.json'); assert.equal(value.repository.name,'agid-postal-af'); assert.equal(value.repository.country_code,'AF'); assert.equal(value.repository.maturity,'M1_metadata'); assert.equal(value.release_scope.metadata_only,true); assert.equal(value.release_scope.contains_raw_source_data,false); assert.equal(value.release_scope.contains_real_addresses,false); assert.equal(value.release_scope.contains_personal_data,false); assert.equal(value.release_scope.contains_production_geometry,false); assert.equal(value.postal_system.current_code_format,'NNNNNN');
 assert.match(value.postal_system.transition_rule,/07\/2025.*1 October 2024.*province.*10-43.*city districts 01-50.*rural districts 51-99.*delivery zones 01-99.*Legacy four-digit.*not accepted/i); assert.match(value.postal_system.assignment_rule,/six-character digit string.*Afghan Post.*UPU examples.*administrative P-codes.*do not independently create/i); assert.match(value.postal_system.geometry_rule,/Afghan Post Postal Code System.*GeoJSON.*no production.*exact Afghan Post response.*OCHA.*administrative context.*never become official/i); assert.match(value.postal_system.building_rule,/explicit rights-cleared civic-address identifier.*stable reviewed relation.*permitted building geometry.*HOT or OSM.*not an automatic.*nearest-building/i); assert.match(value.postal_system.agid_rule,/AGID.*independent spatial index.*versioned crosswalk.*without relabelling/i); assert.match(value.postal_system.licence_rule,/all rights reserved.*do not grant blanket.*CC BY 3\.0 IGO.*ODbL/i); assert.match(value.postal_system.privacy_rule,/address and postcode queries.*premise numbers.*private coordinates.*P\.O\. Box holders.*excluded/i);
 for(const blocker of ['legacy-four-digit-postcode-presented-as-current-six-digit-assignment','interactive-afghan-post-map-presented-as-blanket-geometry-or-address-licence','administrative-pcode-province-or-district-presented-as-postcode-or-postal-boundary','ocha-401-district-boundary-version-presented-as-complete-457-district-current-geography'])assert.ok(value.promotion.hard_blockers.includes(blocker));
});

test('Afghanistan source profile keeps operator, map, UPU, policy, administration, and community authorities separate',()=>{
 const profile=readJson<Profile>('source-profile.json'); const sources=new Map(profile.sources.map(source=>[source.source_id,source])); assert.equal(profile.artifact_scope,'metadata-only-contract-seed'); assert.ok(profile.sources.every(source=>source.bundled_here===false)); assert.match(sources.get('afghan-post')?.redistribution_class??'',/all_rights_reserved/i); assert.match(sources.get('afghan-postal-code-system')?.assignment_authority??'',/official_current_interactive/i); assert.match(sources.get('afghan-postal-code-system')?.geometry_authority??'',/official_postal_map_response.*rights_cleared/i); assert.equal(sources.get('upu-afghanistan-addressing-2025')?.geometry_authority,'none'); assert.match(sources.get('afghan-post-policy')?.assignment_authority??'',/policy_only/i); assert.match(sources.get('ocha-afghanistan-admin-boundaries-2026')?.geometry_authority??'',/administrative_geometry.*cc_by_igo/i); assert.match(sources.get('hot-osm-afghanistan')?.redistribution_class??'',/ODbL/i);
 for(const partition of ['official-six-digit-postcode-assignments','official-postal-area-response','post-office-po-box-and-service-objects','address-search-and-coordinate-private','province-district-and-administrative-pcode-context','derived-postal-administrative-join-surface','civic-address-and-building','community-road-address-and-building-validation','agid-crosswalk'])assert.ok(profile.artifact_partitions.some(candidate=>candidate.id===partition));
});

test('Afghanistan fixtures are synthetic and keep non-postal evidence non-authoritative',()=>{
 const pack=readJson<Fixtures>('fixtures/afghanistan-synthetic.json'); const postcodes=pack.fixtures.map(item=>item.synthetic_address.postcode).filter((value):value is string=>Boolean(value)); const prohibited=new Set(pack.fixtures.flatMap(item=>item.expected.must_not_assert)); assert.equal(pack.country_code,'AF'); assert.equal(pack.synthetic,true); assert.equal(pack.promotion_eligible,false); assert.equal(pack.fixture_policy.contains_real_addresses,false); assert.equal(pack.fixture_policy.contains_upstream_rows,false); assert.equal(pack.fixture_policy.contains_personal_data,false); assert.equal(pack.fixture_policy.coordinates_are_geographic,false); assert.equal(pack.fixture_policy.postcodes_are_assignment_evidence,false); assert.equal(pack.fixture_policy.postal_prefix,'999999'); assert.equal(pack.fixture_policy.deliberately_outside_documented_province_prefix_range,true); assert.ok(postcodes.every(postcode=>/^\d{6}$/.test(postcode))); assert.ok(pack.fixtures.every(item=>item.fixture_id.startsWith('af-syn-')));
 for(const claim of ['synthetic-code-is-current-afghan-post-assignment','interactive-map-or-upu-example-is-bulk-postcode-data','administrative-pcode-or-ocha-boundary-is-postal-authority-polygon','po-box-or-post-office-is-guaranteed-polygon','po-box-holder-or-address-query-is-public-data','hot-or-osm-building-is-automatically-address-linked','postcode-pcode-containment-or-proximity-is-exact-building-link','public-map-policy-pdf-or-search-endpoint-is-artifact-licence'])assert.ok(prohibited.has(claim));
});
