import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
type Profile={artifact_scope:string;sources:Array<{source_id:string;assignment_authority:string;geometry_authority:string;redistribution_class:string;bundled_here:boolean}>;artifact_partitions:Array<{id:string}>};
type Manifest={repository:{name:string;country_code:string;maturity:string};release_scope:Record<string,boolean|string>;postal_system:Record<string,string>;promotion:{current_stage:string;hard_blockers:string[]}};
type Fixtures={country_code:string;synthetic:boolean;promotion_eligible:boolean;fixture_policy:{contains_real_addresses:boolean;contains_upstream_rows:boolean;contains_personal_data:boolean;postal_value:string;coordinates_are_upstream_observations:boolean;postcodes_are_assignment_evidence:boolean;synthetic_value_not_checked_against_live_lookup:boolean;collision_requires_replacement_before_promotion:boolean};fixtures:Array<{fixture_id:string;synthetic_address:{postcode?:string};expected:{must_not_assert:string[]}}>};
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'); const seedRoot=resolve(root,'data/postal_country_packs/il/postal-context'); const readJson=<T>(name:string)=>JSON.parse(readFileSync(resolve(seedRoot,name),'utf8')) as T;

test('Israel seed separates seven digits, distribution code, non-area postal objects, government context, buildings, territorial scope, rights, and privacy',()=>{
 const value=readJson<Manifest>('repository-manifest.json'); assert.equal(value.repository.name,'agid-postal-il'); assert.equal(value.repository.country_code,'IL'); assert.equal(value.repository.maturity,'M1_metadata'); assert.equal(value.release_scope.metadata_only,true); assert.equal(value.release_scope.contains_raw_source_data,false); assert.equal(value.release_scope.contains_real_addresses,false); assert.equal(value.release_scope.contains_personal_data,false); assert.equal(value.release_scope.contains_production_geometry,false); assert.equal(value.postal_system.current_code_format,'NNNNNNN'); assert.equal(value.postal_system.current_code_default_geometry,'area_or_non_area_no_polygon_presumption');
 assert.match(value.postal_system.assignment_rule,/seven digits.*address for mail delivery.*updated.*exact current Israel Post.*UPU example.*GovMap.*does not create/i); assert.match(value.postal_system.geometry_rule,/opaque.*address.*route.*P\.O\. Box.*non-area.*Never generate.*official postal geometry.*GovMap.*model geometry/i); assert.match(value.postal_system.distribution_code_rule,/separate nine-digit distribution code.*must not.*seven-digit postcode/i); assert.match(value.postal_system.building_rule,/explicit rights-cleared civic-address identifier.*stable reviewed relation.*permitted building geometry.*GovMap.*not automatic/i); assert.match(value.postal_system.agid_rule,/AGID.*independent spatial index.*versioned crosswalk.*without relabelling/i); assert.match(value.postal_system.licence_rule,/informational only.*commercial use.*all-rights-reserved.*Data\.gov\.il.*privacy.*ODbL/i); assert.match(value.postal_system.territorial_rule,/not a territorial or sovereignty assertion.*Palestinian Authority.*routing metadata.*cannot create IL/i);
 for(const blocker of ['seven-digit-postcode-presented-as-guaranteed-polygon','israel-post-website-or-lookup-presented-as-bulk-or-commercial-reuse-permission','govmap-search-coordinate-parcel-or-layer-presented-as-israel-post-authority','routing-via-israel-note-presented-as-il-assignment-coverage-boundary-or-sovereignty-evidence'])assert.ok(value.promotion.hard_blockers.includes(blocker));
});

test('Israel source profile keeps operator, guide, terms, UPU, government, community, and territorial authorities separate',()=>{
 const profile=readJson<Profile>('source-profile.json'); const sources=new Map(profile.sources.map(source=>[source.source_id,source])); assert.equal(profile.artifact_scope,'metadata-only-contract-seed'); assert.ok(profile.sources.every(source=>source.bundled_here===false)); assert.match(sources.get('israel-post')?.redistribution_class??'',/restricted_reference/i); assert.match(sources.get('israel-post')?.assignment_authority??'',/official_current_interactive/i); assert.equal(sources.get('israel-post-mail-guide-2020')?.geometry_authority,'none'); assert.match(sources.get('israel-post-terms')?.assignment_authority??'',/legal_terms/i); assert.match(sources.get('govmap-israel')?.geometry_authority??'',/spatial_candidate.*exact_terms/i); assert.match(sources.get('population-authority-israel-street-list')?.redistribution_class??'',/conditional_data_gov/i); assert.match(sources.get('cbs-israel-geography')?.assignment_authority??'',/administrative_only/i); assert.match(sources.get('data-gov-il-terms-2025')?.redistribution_class??'',/default_open_data_terms/i); assert.match(sources.get('osm-israel')?.redistribution_class??'',/ODbL/i);
 for(const partition of ['official-seven-digit-postcode-assignments','postal-object-type-and-official-geometry','nine-digit-distribution-code-private-or-restricted','po-box-delivery-centre-route-and-large-recipient-objects','government-street-locality-administrative-and-statistical-context','derived-postal-context-surface','civic-address-and-building','cross-border-routing-instruction-metadata','agid-crosswalk'])assert.ok(profile.artifact_partitions.some(candidate=>candidate.id===partition));
});

test('Israel fixtures are synthetic and keep non-postal and territorial evidence non-authoritative',()=>{
 const pack=readJson<Fixtures>('fixtures/israel-synthetic.json'); const postcodes=pack.fixtures.map(item=>item.synthetic_address.postcode).filter((value):value is string=>Boolean(value)); const prohibited=new Set(pack.fixtures.flatMap(item=>item.expected.must_not_assert)); assert.equal(pack.country_code,'IL'); assert.equal(pack.synthetic,true); assert.equal(pack.promotion_eligible,false); assert.equal(pack.fixture_policy.contains_real_addresses,false); assert.equal(pack.fixture_policy.contains_upstream_rows,false); assert.equal(pack.fixture_policy.contains_personal_data,false); assert.equal(pack.fixture_policy.coordinates_are_upstream_observations,false); assert.equal(pack.fixture_policy.postcodes_are_assignment_evidence,false); assert.equal(pack.fixture_policy.postal_value,'9999999'); assert.equal(pack.fixture_policy.synthetic_value_not_checked_against_live_lookup,true); assert.equal(pack.fixture_policy.collision_requires_replacement_before_promotion,true); assert.ok(postcodes.every(postcode=>/^\d{7}$/.test(postcode))); assert.ok(pack.fixtures.every(item=>item.fixture_id.startsWith('il-syn-')));
 for(const claim of ['synthetic-code-is-current-israel-post-assignment','seven-digit-code-is-always-a-polygon','israel-post-lookup-or-upu-example-is-bulk-reusable-data','po-box-delivery-centre-or-route-is-guaranteed-polygon','nine-digit-distribution-code-is-a-postcode','postcode-govmap-coordinate-or-proximity-is-exact-building-link','street-cbs-parcel-or-osm-building-is-automatically-address-linked','routing-via-israel-note-is-il-assignment-boundary-or-sovereignty-evidence'])assert.ok(prohibited.has(claim));
});
