import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
type Profile={artifact_scope:string;sources:Array<{source_id:string;assignment_authority:string;geometry_authority:string;redistribution_class:string;bundled_here:boolean}>;artifact_partitions:Array<{id:string}>};
type Manifest={repository:{name:string;country_code:string;maturity:string};release_scope:Record<string,boolean|string>;postal_system:Record<string,string>;promotion:{current_stage:string;hard_blockers:string[]}};
type Fixtures={country_code:string;synthetic:boolean;promotion_eligible:boolean;fixture_policy:{contains_real_addresses:boolean;contains_upstream_rows:boolean;contains_personal_data:boolean;postal_prefix:string;coordinates_are_geographic:boolean;postcodes_are_assignment_evidence:boolean};fixtures:Array<{fixture_id:string;synthetic_address:{postcode?:string};expected:{must_not_assert:string[]}}>};
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'); const seedRoot=resolve(root,'data/postal_country_packs/lb/postal-context'); const readJson=<T>(name:string)=>JSON.parse(readFileSync(resolve(seedRoot,name),'utf8')) as T;

test('Lebanon seed separates postcode, NAC, P-code, surfaces, address, building, cadastre, AGID, rights, and privacy',()=>{
 const value=readJson<Manifest>('repository-manifest.json'); assert.equal(value.repository.name,'agid-postal-lb'); assert.equal(value.repository.country_code,'LB'); assert.equal(value.repository.maturity,'M1_metadata'); assert.equal(value.release_scope.metadata_only,true); assert.equal(value.release_scope.contains_raw_source_data,false); assert.equal(value.release_scope.contains_real_addresses,false); assert.equal(value.release_scope.contains_personal_data,false); assert.equal(value.release_scope.contains_production_geometry,false); assert.equal(value.postal_system.current_code_format,'NNNN or NN NNN NNN');
 assert.match(value.postal_system.legal_rule,/LibanPost.*NAC.*UPU.*9999.*99 999 999.*not.*canonical national postal polygons.*buildings/i); assert.match(value.postal_system.assignment_rule,/four digits.*NN NNN NNN.*leading zeroes.*NAC.*P-codes.*do not independently create/i); assert.match(value.postal_system.geometry_rule,/No reviewed.*canonical national Lebanon.*polygon.*derived postal-administrative join surface.*Administrative P-codes.*not postcodes.*never become official/i); assert.match(value.postal_system.building_rule,/explicit rights-cleared civic-address identifier.*stable reviewed relation.*permitted building geometry.*DLRC.*not public.*nearest-building/i); assert.match(value.postal_system.agid_rule,/AGID.*independent spatial index.*NAC.*versioned crosswalk.*without relabelling/i); assert.match(value.postal_system.licence_rule,/exact page, item, layer or service URL.*terms or licence.*digest.*blank copyright text.*not grant blanket/i); assert.match(value.postal_system.privacy_rule,/NAC tokens.*P\.O\. Box holders.*owners.*title-register.*excluded/i); assert.match(value.postal_system.privacy_rule,/Law 81\/2018.*Article 98.*before access.*publication/i);
 for(const blocker of ['libanpost-upu-format-or-address-page-presented-as-official-postcode-polygon','nac-map-pin-or-coordinate-presented-as-postcode-or-agid','administrative-pcode-governorate-district-or-cadaster-presented-as-postal-assignment','dlrc-parcel-unit-title-owner-or-cadastral-record-presented-as-public-building-data'])assert.ok(value.promotion.hard_blockers.includes(blocker));
});

test('Lebanon source profile keeps postal, NAC, UPU, administration, cadastre, personal data, and OSM authorities separate',()=>{
 const profile=readJson<Profile>('source-profile.json'); const sources=new Map(profile.sources.map(source=>[source.source_id,source])); assert.equal(profile.artifact_scope,'metadata-only-contract-seed'); assert.ok(profile.sources.every(source=>source.bundled_here===false)); assert.match(sources.get('libanpost')?.assignment_authority??'',/official_current_assignment/i); assert.match(sources.get('libanpost-address-and-nac')?.redistribution_class??'',/private_or_transaction/i); assert.equal(sources.get('upu-lebanon-addressing')?.geometry_authority,'none'); assert.match(sources.get('upu-lebanon-postcode-formats-2025')?.assignment_authority??'',/format_only/i); assert.match(sources.get('moph-lebanon-administrative-zones')?.geometry_authority??'',/official_administrative_geometry/i); assert.match(sources.get('lebanon-atlas-admin-boundaries-2026')?.geometry_authority??'',/derived_administrative/i); assert.match(sources.get('dlrc-lebanon-cadastre')?.geometry_authority??'',/restricted_cadastral/i); assert.match(sources.get('lebanon-law-81-2018-personal-data')?.redistribution_class??'',/permission_required/i);
 for(const partition of ['official-postcode-assignments','nac-and-location-token-private','post-office-po-box-and-service-objects','official-postal-surface','derived-postal-administrative-join-surface','governorate-district-cadaster-and-pcode-context','civic-address-and-building','cadastral-parcel-unit-title-and-owner-private','agid-crosswalk'])assert.ok(profile.artifact_partitions.some(candidate=>candidate.id===partition));
});

test('Lebanon fixtures keep codes synthetic and NAC, P-code, cadastral, and model evidence non-authoritative',()=>{
 const pack=readJson<Fixtures>('fixtures/lebanon-synthetic.json'); const postcodes=pack.fixtures.map(item=>item.synthetic_address.postcode).filter((value):value is string=>Boolean(value)); const prohibited=new Set(pack.fixtures.flatMap(item=>item.expected.must_not_assert)); assert.equal(pack.country_code,'LB'); assert.equal(pack.synthetic,true); assert.equal(pack.promotion_eligible,false); assert.equal(pack.fixture_policy.contains_real_addresses,false); assert.equal(pack.fixture_policy.contains_upstream_rows,false); assert.equal(pack.fixture_policy.contains_personal_data,false); assert.equal(pack.fixture_policy.coordinates_are_geographic,false); assert.equal(pack.fixture_policy.postcodes_are_assignment_evidence,false); assert.equal(pack.fixture_policy.postal_prefix,'9999'); assert.ok(postcodes.every(postcode=>/^\d{4}$/.test(postcode))); assert.ok(pack.fixtures.every(item=>item.fixture_id.startsWith('lb-syn-')));
 for(const claim of ['libanpost-upu-format-or-address-page-is-official-postal-boundary','nac-map-pin-or-coordinate-is-postcode-or-agid','administrative-pcode-or-cadaster-is-postal-authority-polygon','po-box-or-nac-is-polygon','po-box-holder-or-address-query-is-public-data','dlrc-parcel-unit-title-or-owner-record-is-public-building-data','postcode-nac-pcode-containment-or-proximity-is-exact-building-link','public-form-pdf-viewer-arcgis-or-paid-lookup-is-artifact-licence'])assert.ok(prohibited.has(claim));
});
