import assert from 'node:assert/strict';
import { test } from 'node:test';
import { PostalContextPackRuntime, normalizeHaitiPostalCode, validatePostalContextRuntimePack } from './postalContextPackRuntime';
import { HAITI_POSTAL_CONTEXT_TEST_INSTANT, HAITI_POSTAL_CONTEXT_TEST_POINT, createHaitiPostalContextRuntimeTestPack } from '../testFixtures/postalContextHaitiRuntimeFixture';

test('Haitian pack keeps operator assignment, derived geometry, explicit building relation, and AGID separate', () => { const pack = createHaitiPostalContextRuntimeTestPack(); const validation = validatePostalContextRuntimePack(pack, 'HT'); const polygon = pack.geometry.features.find(feature => feature.role === 'postal_area'); assert.equal(validation.valid, true, validation.errors.join('; ')); assert.equal(normalizeHaitiPostalCode('ＨＴ９９９９'), 'HT9999'); assert.equal(normalizeHaitiPostalCode('ht 9999'), 'HT9999'); assert.equal(normalizeHaitiPostalCode('9999'), null); assert.equal(normalizeHaitiPostalCode('HT-9999'), null); assert.equal(polygon?.quality.status, 'derived'); assert.equal(polygon?.source.sourceId, 'ht-synthetic-derived-postal-validation-polygon'); assert.notEqual(polygon?.source.geometryAuthority, 'official_haiti_postal_geometry'); });

test('Haitian postcode lookup normalizes integral HTNNNN and gates synthetic geometry', () => { const runtime = new PostalContextPackRuntime(createHaitiPostalContextRuntimeTestPack()); const lookup = runtime.lookupPostalCode('ht 9999', HAITI_POSTAL_CONTEXT_TEST_INSTANT); const withGeometry = runtime.lookupPostalCode('HT9999', HAITI_POSTAL_CONTEXT_TEST_INSTANT, HAITI_POSTAL_CONTEXT_TEST_INSTANT, true); assert.equal(lookup.status, 'unique'); assert.equal(lookup.countryCode, 'HT'); assert.equal(lookup.normalizedPostalCode, 'HT9999'); assert.deepEqual(lookup.geometries, []); assert.equal(withGeometry.geometries[0]?.geometry.type, 'Polygon'); });

test('Haitian coordinate resolution reaches a building only through an explicit synthetic civic relation', () => { const runtime = new PostalContextPackRuntime(createHaitiPostalContextRuntimeTestPack()); const result = runtime.resolvePublicCoordinate({ ...HAITI_POSTAL_CONTEXT_TEST_POINT, purpose: 'display', validAt: HAITI_POSTAL_CONTEXT_TEST_INSTANT }); assert.equal(result.status, 'unique'); assert.equal(result.countryCode, 'HT'); assert.equal(result.resolvedLevel, 'building'); assert.equal(result.addressPointEvidence.matched, true); assert.deepEqual(result.postalEvidence, [{ postalCode: 'HT9999', relation: 'inside' }]); assert.equal(result.selected?.components.some(component => component.label === 'Synthetic explicitly address-linked Haitian building'), true); });

test('Haitian bbox lookup returns only the synthetic derived validation surface', () => { const runtime = new PostalContextPackRuntime(createHaitiPostalContextRuntimeTestPack()); const result = runtime.intersectsPostalBbox([-72.32,18.53,-72.28,18.57], HAITI_POSTAL_CONTEXT_TEST_INSTANT); assert.equal(result.status, 'unique'); assert.equal(result.matches[0]?.node.postalCode, 'HT9999'); assert.equal(result.matches[0]?.source.sourceId, 'ht-synthetic-derived-postal-validation-polygon'); });
