import assert from 'node:assert/strict';
import { test } from 'node:test';
import { PostalContextPackRuntime, normalizeIraqPostalCode, validatePostalContextRuntimePack } from './postalContextPackRuntime';
import { IRAQ_POSTAL_CONTEXT_TEST_INSTANT, IRAQ_POSTAL_CONTEXT_TEST_POINT, createIraqPostalContextRuntimeTestPack } from '../testFixtures/postalContextIraqRuntimeFixture';

test('Iraq pack separates five-digit assignment, non-area semantics, migration candidate, government context, building, jurisdiction, and AGID', () => {
  const pack=createIraqPostalContextRuntimeTestPack(); const validation=validatePostalContextRuntimePack(pack,'IQ'); const postalArea=pack.geometry.features.find(feature=>feature.role==='postal_area'); assert.equal(validation.valid,true,validation.errors.join('\n')); assert.equal(normalizeIraqPostalCode('۹۹۹۹۹'),'99999'); assert.equal(normalizeIraqPostalCode('٩٩ ٩٩٩'),'99999'); assert.equal(normalizeIraqPostalCode('99999AR1'),null); assert.equal(postalArea?.quality.status,'derived'); assert.equal(postalArea?.source.sourceId,'iq-synthetic-derived-postal-context-surface'); assert.equal(postalArea?.source.assignmentAuthority,'synthetic_fixture_assignment'); assert.equal(postalArea?.source.geometryAuthority,'synthetic_fixture_geometry');
});
test('Iraq postcode lookup canonicalizes Arabic digits and exposes only opt-in synthetic geometry',()=>{ const runtime=new PostalContextPackRuntime(createIraqPostalContextRuntimeTestPack()); const lookup=runtime.lookupPostalCode('۹۹۹۹۹',IRAQ_POSTAL_CONTEXT_TEST_INSTANT); const withGeometry=runtime.lookupPostalCode('99999',IRAQ_POSTAL_CONTEXT_TEST_INSTANT,IRAQ_POSTAL_CONTEXT_TEST_INSTANT,true); assert.equal(lookup.status,'unique'); assert.equal(lookup.countryCode,'IQ'); assert.equal(lookup.normalizedPostalCode,'99999'); assert.deepEqual(lookup.geometries,[]); assert.equal(withGeometry.geometries[0]?.geometry.type,'Polygon'); });
test('Iraq coordinate resolution reaches a building only through explicit civic relation',()=>{ const runtime=new PostalContextPackRuntime(createIraqPostalContextRuntimeTestPack()); const result=runtime.resolvePublicCoordinate({...IRAQ_POSTAL_CONTEXT_TEST_POINT,purpose:'display',validAt:IRAQ_POSTAL_CONTEXT_TEST_INSTANT}); assert.equal(result.status,'unique'); assert.equal(result.countryCode,'IQ'); assert.equal(result.resolvedLevel,'building'); assert.equal(result.addressPointEvidence.matched,true); assert.deepEqual(result.postalEvidence,[{postalCode:'99999',relation:'inside'}]); assert.equal(result.selected?.components.some(component=>component.label==='Synthetic explicitly address-linked Iraq building'),true); });
test('Iraq bbox lookup returns only the synthetic derived validation surface',()=>{ const runtime=new PostalContextPackRuntime(createIraqPostalContextRuntimeTestPack()); const result=runtime.intersectsPostalBbox([43.98,32.48,44.02,32.52],IRAQ_POSTAL_CONTEXT_TEST_INSTANT); assert.equal(result.status,'unique'); assert.equal(result.matches[0]?.node.postalCode,'99999'); assert.equal(result.matches[0]?.source.sourceId,'iq-synthetic-derived-postal-context-surface'); });
