import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
type Profile={artifact_scope:string;sources:Array<{source_id:string;assignment_authority:string;geometry_authority:string;redistribution_class:string;bundled_here:boolean}>;artifact_partitions:Array<{id:string}>};
type Manifest={repository:{name:string;country_code:string;maturity:string};release_scope:Record<string,boolean|string>;postal_system:Record<string,string>;promotion:{current_stage:string;hard_blockers:string[]}};
type Fixtures={country_code:string;synthetic:boolean;promotion_eligible:boolean;fixture_policy:{contains_real_addresses:boolean;contains_upstream_rows:boolean;contains_personal_data:boolean;postal_prefix:string;coordinates_are_geographic:boolean;postcodes_are_assignment_evidence:boolean};fixtures:Array<{fixture_id:string;synthetic_address:{postcode?:string};expected:{must_not_assert:string[]}}>};
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'); const seedRoot=resolve(root,'data/postal_country_packs/jo/postal-context'); const readJson=<T>(name:string)=>JSON.parse(readFileSync(resolve(seedRoot,name),'utf8')) as T;

test('Jordan seed separates routing codes, offices, surfaces, addresses, buildings, AGID, rights, and privacy',()=>{
 const value=readJson<Manifest>('repository-manifest.json'); assert.equal(value.repository.name,'agid-postal-jo'); assert.equal(value.repository.country_code,'JO'); assert.equal(value.repository.maturity,'M1_metadata'); assert.equal(value.release_scope.metadata_only,true); assert.equal(value.release_scope.contains_raw_source_data,false); assert.equal(value.release_scope.contains_real_addresses,false); assert.equal(value.release_scope.contains_personal_data,false); assert.equal(value.release_scope.contains_production_geometry,false); assert.equal(value.postal_system.current_code_format,'NNNNN');
 assert.match(value.postal_system.legal_rule,/Jordan Post.*UPU.*five digits.*carrier-route sorting.*incomplete.*not.*canonical postal polygons.*building/i); assert.match(value.postal_system.assignment_rule,/five-character digit string.*leading zeroes.*Jordan Post.*post-office rows.*village codes.*do not create/i); assert.match(value.postal_system.geometry_rule,/No reviewed.*canonical national.*polygon.*derived routing-administrative join surface.*P.O. boxes.*non-area.*never become official/i); assert.match(value.postal_system.building_rule,/explicit rights-cleared civic-address identifier.*stable reviewed relation.*permitted building geometry.*MoU.*not a public building dataset.*nearest-building/i); assert.match(value.postal_system.agid_rule,/AGID.*independent spatial index.*versioned crosswalk.*without relabelling/i); assert.match(value.postal_system.licence_rule,/exact artifact expressly published.*publisher.*digest.*do not.*blanket.*redistribution/i); assert.match(value.postal_system.privacy_rule,/P.O. Box holders.*digital mailbox.*home locations.*owners.*occupants.*excluded/i);
 for(const blocker of ['jordan-post-upu-or-office-row-presented-as-official-postcode-polygon','administrative-boundary-village-code-or-street-record-presented-as-postal-authority-geometry','rjgc-gam-mou-presented-as-public-address-or-building-data','digital-mailbox-pilot-presented-as-public-production-address-api'])assert.ok(value.promotion.hard_blockers.includes(blocker));
});

test('Jordan source profile keeps postal, policy, offices, licence, mapping, building, village, street, pilot, and AGID authorities separate',()=>{
 const profile=readJson<Profile>('source-profile.json'); const sources=new Map(profile.sources.map(source=>[source.source_id,source])); assert.equal(profile.artifact_scope,'metadata-only-contract-seed'); assert.ok(profile.sources.every(source=>source.bundled_here===false)); assert.match(sources.get('jordanpost')?.assignment_authority??'',/official_current_assignment/i); assert.equal(sources.get('upu-jordan-addressing-2004')?.geometry_authority,'none'); assert.match(sources.get('jordan-post-offices-open-data-2023')?.geometry_authority??'',/point_or_non_area/i); assert.match(sources.get('rjgc-jordan')?.geometry_authority??'',/official_mapping_products/i); assert.match(sources.get('rjgc-gam-building-mou')?.redistribution_class??'',/private_or_institutional/i); assert.match(sources.get('dls-jordan-village-codes-2022')?.assignment_authority??'',/none_administrative_cadastral/i); assert.match(sources.get('jordan-digital-mailbox-pilot-2026')?.geometry_authority??'',/private_or_controlled/i);
 for(const partition of ['official-postcode-assignments','post-office-and-routing-objects','official-postal-surface','derived-routing-administrative-join-surface','administrative-village-and-street-context','civic-address-and-building','digital-mailbox-pilot-and-private-address','agid-crosswalk','private-restricted-and-cadastral'])assert.ok(profile.artifact_partitions.some(candidate=>candidate.id===partition));
});

test('Jordan fixtures keep synthetic codes and non-postal evidence non-authoritative',()=>{
 const pack=readJson<Fixtures>('fixtures/jordan-synthetic.json'); const postcodes=pack.fixtures.map(item=>item.synthetic_address.postcode).filter((value):value is string=>Boolean(value)); const prohibited=new Set(pack.fixtures.flatMap(item=>item.expected.must_not_assert)); assert.equal(pack.country_code,'JO'); assert.equal(pack.synthetic,true); assert.equal(pack.promotion_eligible,false); assert.equal(pack.fixture_policy.contains_real_addresses,false); assert.equal(pack.fixture_policy.contains_upstream_rows,false); assert.equal(pack.fixture_policy.contains_personal_data,false); assert.equal(pack.fixture_policy.coordinates_are_geographic,false); assert.equal(pack.fixture_policy.postcodes_are_assignment_evidence,false); assert.equal(pack.fixture_policy.postal_prefix,'99999'); assert.ok(postcodes.every(postcode=>/^\d{5}$/.test(postcode))); assert.ok(pack.fixtures.every(item=>item.fixture_id.startsWith('jo-syn-')));
 for(const claim of ['jordan-post-upu-or-office-row-is-official-postal-boundary','post-office-po-box-or-carrier-route-is-guaranteed-area','administrative-boundary-village-code-or-street-is-postal-authority-polygon','digital-mailbox-pilot-is-public-production-address-api','rjgc-gam-mou-is-public-building-data','postcode-containment-or-proximity-is-exact-building-link','open-data-portal-viewer-policy-or-public-access-is-artifact-licence'])assert.ok(prohibited.has(claim));
});
