import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..'); const seedRoot = resolve(root, 'data/postal_country_packs/ve/postal-context'); const readJson = (name: string) => JSON.parse(readFileSync(resolve(seedRoot, name), 'utf8')) as any;
test('Venezuelan seed separates delivery network, geometry, administration, buildings, cadastre, jurisdiction, privacy, and AGID', () => {
  const value = readJson('repository-manifest.json'); assert.equal(value.repository.name, 'agid-postal-ve'); assert.equal(value.repository.country_code, 'VE'); assert.equal(value.repository.maturity, 'M1_metadata'); assert.equal(value.release_scope.metadata_only, true);
  assert.equal(value.release_scope.contains_raw_source_data, false); assert.equal(value.release_scope.contains_real_addresses, false); assert.equal(value.release_scope.contains_personal_data, false); assert.equal(value.release_scope.contains_production_geometry, false);
  assert.match(value.postal_system.assignment_rule, /IPOSTEL.*May 2019.*four digits.*postal region.*delivery office.*not current.*time-bound/i);
  assert.match(value.postal_system.geometry_rule, /delivery-network-first.*not automatically an area.*No reusable nationwide.*Voronoi.*cannot.*official/i);
  assert.match(value.postal_system.postal_object_rule, /delivery_office.*service_area.*postal_region.*route.*po_box.*must never be collapsed/i);
  assert.match(value.postal_system.building_rule, /stable civic-address.*explicit reviewed relation.*postcode.*not an exact/i);
  assert.match(value.postal_system.administrative_rule, /INE 2001.*not a current.*IPOSTEL.*pin exact current/i);
  assert.match(value.postal_system.cartography_and_cadastre_rule, /IGVSB.*national and municipal.*public.*not by itself.*bulk-data licence.*building relation/i);
  assert.match(value.postal_system.derived_and_realtime_rule, /IPOSTEL observations.*rank candidates.*train or run review models.*never upgrades.*unknown/i);
  assert.match(value.postal_system.agid_rule, /independent spatial index.*Versioned crosswalks.*official Venezuelan postal geometry/i);
  assert.match(value.postal_system.jurisdiction_rule, /ISO VE.*territorial representation.*disputed or claimed-area.*sovereignty/i);
  assert.match(value.postal_system.hugging_face_rule, /Dataset.*Parquet.*GeoParquet.*pin a Hub commit.*digests/i);
  for (const blocker of ['valid-four-digit-text-presented-as-current-ipostel-assignment', 'delivery-office-route-po-box-locality-or-region-presented-as-an-automatic-polygon', 'interactive-ipostel-response-republished-as-a-bulk-postcode-or-address-dataset', 'upu-example-ine-locality-igvsb-municipal-cadastral-community-or-model-geometry-presented-as-ipostel-postal-geometry', 'postcode-reference-parcel-coordinate-containment-interpolation-or-proximity-presented-as-exact-building-relation', 'territorial-representation-presented-as-resolving-a-dispute-or-sovereignty', 'derived-buffer-voronoi-interpolation-or-model-surface-presented-as-official-or-used-to-fill-unknown-coverage']) assert.ok(value.promotion.hard_blockers.includes(blocker), blocker);
});
test('Venezuelan source profile gates IPOSTEL observations and caps postal geometry at derived review', () => {
  const profile = readJson('source-profile.json'); const sources = new Map<string, any>(profile.sources.map((source: any) => [source.source_id, source])); assert.equal(profile.artifact_scope, 'metadata-only-contract-seed'); assert.ok(profile.sources.every((source: any) => source.bundled_here === false));
  assert.match(sources.get('ipostel-venezuela-postcode-lookup')?.assignment_authority ?? '', /official_postal_operator.*observation/i); assert.match(sources.get('ipostel-venezuela-postcode-lookup')?.geometry_authority ?? '', /none.*no_verified.*polygon/i);
  assert.match(sources.get('ine-venezuela-populated-places-2001')?.assignment_authority ?? '', /dated.*statistical/i); assert.match(sources.get('igvsb-venezuela-geographic-authority')?.geometry_authority ?? '', /dataset_specific.*not_postal/i); assert.match(sources.get('osm-venezuela')?.redistribution_class ?? '', /ODbL/i);
  assert.equal(profile.assignment_observation_gate.maximum_claim, 'official-observation'); assert.equal(profile.geometry_promotion_gate.maximum_claim, 'derived-review'); assert.match(profile.geometry_promotion_gate.failure_mode, /non-geometric delivery-network object.*failed gate/i);
  for (const check of ['authorized-four-digit-ipostel-query', 'official-page-and-endpoint-state-revalidated', 'postal-region-and-delivery-office-semantics-validated', 'addresses-references-credentials-and-query-logs-minimized-and-protected']) assert.ok(profile.assignment_observation_gate.required_checks.includes(check), check);
  for (const check of ['source-postal-service-area-evidence-rights-cleared', 'delivery-office-service-area-crosswalk-reviewed', 'ine-igvsb-municipal-cadastral-and-community-context-not-promoted-to-postal-authority', 'jurisdiction-territorial-representation-crs-topology-and-input-digests-pinned', 'derived-status-never-upgraded-by-model-confidence']) assert.ok(profile.geometry_promotion_gate.required_checks.includes(check), check);
  assert.deepEqual(profile.hugging_face.preferred_formats, ['parquet', 'geoparquet']); assert.match(profile.hugging_face.production_read_rule, /pin-hub-commit.*digests/i);
});
test('Venezuelan fixtures are synthetic and keep postal, person, territorial, building, and AGID claims non-authoritative', () => {
  const pack = readJson('fixtures/venezuela-synthetic.json'); const prohibited = new Set(pack.fixtures.flatMap((item: any) => item.expected.must_not_assert)); assert.equal(pack.country_code, 'VE'); assert.equal(pack.synthetic, true); assert.equal(pack.promotion_eligible, false);
  assert.equal(pack.fixture_policy.contains_real_addresses, false); assert.equal(pack.fixture_policy.contains_upstream_rows, false); assert.equal(pack.fixture_policy.contains_personal_data, false); assert.equal(pack.fixture_policy.postal_value, '9999'); assert.equal(pack.fixture_policy.postcodes_are_assignment_evidence, false); assert.equal(pack.fixture_policy.synthetic_value_not_checked_against_live_operator, true); assert.equal(pack.fixture_policy.collision_requires_replacement_before_promotion, true); assert.ok(pack.fixtures.every((item: any) => item.fixture_id.startsWith('ve-syn-')));
  for (const claim of ['synthetic-code-is-current-ipostel-assignment', 'synthetic-polygon-is-official-ipostel-postal-geometry', 'delivery-office-route-po-box-locality-or-region-is-automatically-a-polygon', 'upu-ine-igvsb-municipal-cadastral-community-or-model-object-is-ipostel-postal-geometry', 'territorial-representation-resolves-a-dispute-or-sovereignty', 'postcode-reference-parcel-coordinate-containment-interpolation-or-proximity-is-exact-building-link', 'person-household-owner-occupant-organization-credential-query-log-or-fine-address-is-public-data', 'postal-source-coverage-extends-beyond-declared-ve-scope', 'agid-cell-is-official-postal-geometry']) assert.ok(prohibited.has(claim), claim);
});
