import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../data/postal_country_packs/ht/postal-context'); const readJson = (name: string) => JSON.parse(readFileSync(resolve(root, name), 'utf8'));
test('Haitian seed separates operator assignment, administration, derived geometry, buildings, realtime, time, privacy and AGID', () => { const value = readJson('repository-manifest.json'); assert.equal(value.repository.country_code, 'HT'); assert.equal(value.repository.maturity, 'M1_metadata'); assert.equal(value.release_scope.contains_raw_source_data, false); assert.equal(value.release_scope.contains_real_addresses, false); assert.equal(value.release_scope.contains_production_geometry, false); assert.match(value.postal_system.assignment_rule, /HT plus four digits.*domestic.*not proof/i); assert.match(value.postal_system.geometry_rule, /No reusable nationwide.*IHSI.*CNIGS.*derived-review/i); assert.match(value.postal_system.address_format_rule, /building.*house number.*communal section.*HTNNNN/i); assert.match(value.postal_system.building_rule, /stable civic-address identifier.*explicit reviewed relation.*not an exact/i); assert.match(value.postal_system.administrative_rule, /IHSI.*six-digit.*not.*HTNNNN/i); assert.match(value.postal_system.derived_and_realtime_rule, /realtime.*timeout.*machine|model output/i); assert.match(value.postal_system.agid_rule, /AGID remains an independent.*without relabelling/i); assert.match(value.postal_system.licence_rule, /Public visibility is not.*redistribution licence/i); assert.match(value.postal_system.privacy_rule, /lookup queries.*purpose limitation/i); assert.match(value.postal_system.temporal_rule, /September 2017.*2024.*valid_from.*supersession/i); assert.equal(value.promotion.current_stage, 'M1_metadata'); assert.ok(value.promotion.hard_blockers.length >= 10); });
test('Haitian source profile caps operator observations and administrative geometry claims', () => { const profile = readJson('source-profile.json'); assert.equal(profile.country_code, 'HT'); assert.equal(profile.sources.length, 6); assert.equal(profile.sources.some((item: any) => item.source_id === 'office-postes-haiti-postcode-search' && item.assignment_authority === 'official_postal_operator_observation'), true); assert.equal(profile.sources.some((item: any) => item.source_id === 'ihsi-haiti-territorial-codes' && item.assignment_authority === 'not_postal'), true); assert.equal(profile.sources.some((item: any) => item.source_id === 'cnigs-haiti-reference-geodata' && item.geometry_authority.includes('not_postal')), true); assert.equal(profile.assignment_observation_gate.maximum_claim, 'operator-observation'); assert.equal(profile.geometry_promotion_gate.maximum_claim, 'derived-review-geometry'); assert.match(profile.geometry_promotion_gate.failure_mode, /never-official-operator/i); assert.equal(profile.realtime_and_model.outage_rule, 'timeout-empty-or-unavailable-is-unknown-not-no-assignment'); assert.equal(profile.hugging_face.production_read_rule, 'pin-hub-commit-and-verify-shard-digests'); });
test('Haitian fixtures are synthetic and keep postal, administration, person, building and AGID claims non-authoritative', () => { const pack = readJson('fixtures/haiti-synthetic.json'); const prohibited = new Set(pack.fixtures.flatMap((item: any) => item.expected.must_not_assert)); assert.equal(pack.country_code, 'HT'); assert.equal(pack.synthetic, true); assert.equal(pack.promotion_eligible, false); assert.equal(pack.fixture_policy.contains_real_addresses, false); assert.equal(pack.fixture_policy.contains_upstream_rows, false); assert.equal(pack.fixture_policy.contains_personal_data, false); assert.equal(pack.fixture_policy.postal_value, 'HT9999'); assert.equal(pack.fixture_policy.postcodes_are_assignment_evidence, false); assert.equal(pack.fixture_policy.synthetic_value_not_checked_against_live_operator, true); assert.equal(pack.fixture_policy.collision_requires_replacement_before_promotion, true); assert.ok(pack.fixtures.every((item: any) => item.fixture_id.startsWith('ht-syn-'))); for (const claim of ['synthetic-code-is-current-office-des-postes-assignment','synthetic-polygon-is-official-haitian-postal-geometry','ihsi-territorial-object-is-office-des-postes-postal-geometry','cnigs-administrative-reference-or-model-object-is-office-des-postes-postal-geometry','postcode-administrative-area-street-number-parcel-point-coordinate-or-proximity-is-exact-building-link','person-household-owner-occupant-organization-credential-query-log-or-private-address-is-public-data','agid-cell-is-official-postal-geometry']) assert.ok(prohibited.has(claim), claim); });
