import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
type Profile={artifact_scope:string;sources:Array<{source_id:string;assignment_authority:string;geometry_authority:string;redistribution_class:string;bundled_here:boolean}>;artifact_partitions:Array<{id:string}>};
type Manifest={repository:{name:string;country_code:string;maturity:string};release_scope:Record<string,boolean|string>;postal_system:Record<string,string>;promotion:{current_stage:string;hard_blockers:string[]}};
type Fixtures={country_code:string;synthetic:boolean;promotion_eligible:boolean;fixture_policy:{contains_real_addresses:boolean;contains_upstream_rows:boolean;contains_personal_data:boolean;postal_prefix:string;coordinates_are_geographic:boolean;postcodes_are_assignment_evidence:boolean};fixtures:Array<{fixture_id:string;synthetic_address:{postcode?:string};expected:{must_not_assert:string[]}}>};
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'); const seedRoot=resolve(root,'data/postal_country_packs/mn/postal-context'); const readJson=<T>(name:string)=>JSON.parse(readFileSync(resolve(seedRoot,name),'utf8')) as T;

test('Mongolia seed separates five-digit zones, nine-digit building codes, government grids, AGID, rights, and privacy',()=>{
 const value=readJson<Manifest>('repository-manifest.json'); assert.equal(value.repository.name,'agid-postal-mn'); assert.equal(value.repository.country_code,'MN'); assert.equal(value.repository.maturity,'M1_metadata'); assert.equal(value.release_scope.metadata_only,true); assert.equal(value.release_scope.contains_raw_source_data,false); assert.equal(value.release_scope.contains_real_addresses,false); assert.equal(value.release_scope.contains_personal_data,false); assert.equal(value.release_scope.contains_production_geometry,false); assert.equal(value.postal_system.current_code_format,'NNNNN or NNNNN-NNNN');
 assert.match(value.postal_system.legal_rule,/five-digit postal zone.*nine-digit unified.*appends four digits.*assigned to a building.*not.*canonical polygons.*building geometry/i); assert.match(value.postal_system.assignment_rule,/five-character string.*NNNNN-NNNN.*leading zeroes.*CRC.*Gazar grid codes.*do not create/i); assert.match(value.postal_system.geometry_rule,/No reviewed.*canonical national.*polygon.*derived postal-zone surface.*nine-digit code.*non-spatial.*Gazar grids.*never become official/i); assert.match(value.postal_system.building_rule,/nine-digit unified code.*exact CRC.*stable building identifier.*separately permitted building geometry.*nearest-building.*only/i); assert.match(value.postal_system.grid_rule,/100 km.*10 km.*10 m.*never.*CRC postal codes.*AGID.*independent/i); assert.match(value.postal_system.licence_rule,/CRC.*UPU.*Gazar.*NSDI.*NSO.*do not.*blanket.*redistribution/i); assert.match(value.postal_system.privacy_rule,/Recipients.*queries.*households.*owners.*occupants.*cadastral.*excluded/i);
 for(const blocker of ['five-digit-zone-presented-as-canonical-polygon-without-exact-postal-geometry','nine-digit-code-presented-as-building-footprint-without-explicit-provider-relation','gazar-government-grid-presented-as-postcode-or-agid','administrative-boundary-presented-as-postal-authority-polygon'])assert.ok(value.promotion.hard_blockers.includes(blocker));
});

test('Mongolia source profile keeps postal, address grid, boundaries, statistics, building, and licence authorities separate',()=>{
 const profile=readJson<Profile>('source-profile.json'); const sources=new Map(profile.sources.map(source=>[source.source_id,source])); assert.equal(profile.artifact_scope,'metadata-only-contract-seed'); assert.ok(profile.sources.every(source=>source.bundled_here===false)); assert.match(sources.get('zipcode-mn')?.assignment_authority??'',/official_current_assignment/i); assert.match(sources.get('crc-mongolia-unified-postcode-2019')?.assignment_authority??'',/none_legal/i); assert.equal(sources.get('upu-mongolia-addressing')?.geometry_authority,'none'); assert.match(sources.get('gazar-mongolia-address-system')?.geometry_authority??'',/official_address_registry_geometry/i); assert.match(sources.get('gazar-mongolia-boundaries')?.geometry_authority??'',/official_mapping_geometry/i); assert.equal(sources.get('nso-mongolia-administrative-units')?.geometry_authority,'none');
 for(const partition of ['official-postcode-assignments','official-five-digit-postal-surface','derived-postal-zone-surface','nine-digit-unified-building-code','civic-address-and-building','government-address-grid','administrative-statistics-and-private-restricted'])assert.ok(profile.artifact_partitions.some(candidate=>candidate.id===partition));
});

test('Mongolia fixtures keep synthetic codes and non-postal evidence non-authoritative',()=>{
 const pack=readJson<Fixtures>('fixtures/mongolia-synthetic.json'); const postcodes=pack.fixtures.map(item=>item.synthetic_address.postcode).filter((value):value is string=>Boolean(value)); const prohibited=new Set(pack.fixtures.flatMap(item=>item.expected.must_not_assert)); assert.equal(pack.country_code,'MN'); assert.equal(pack.synthetic,true); assert.equal(pack.promotion_eligible,false); assert.equal(pack.fixture_policy.contains_real_addresses,false); assert.equal(pack.fixture_policy.contains_upstream_rows,false); assert.equal(pack.fixture_policy.contains_personal_data,false); assert.equal(pack.fixture_policy.coordinates_are_geographic,false); assert.equal(pack.fixture_policy.postcodes_are_assignment_evidence,false); assert.equal(pack.fixture_policy.postal_prefix,'99999'); assert.ok(postcodes.every(postcode=>/^\d{5}(?:-\d{4})?$/.test(postcode))); assert.ok(pack.fixtures.every(item=>item.fixture_id.startsWith('mn-syn-')));
 for(const claim of ['five-digit-zone-is-canonical-postal-polygon','nine-digit-code-is-building-footprint','gazar-grid-is-postcode','gazar-grid-is-agid','grid-containment-is-civic-address-or-building','viewer-standard-or-open-data-programme-is-redistribution-right'])assert.ok(prohibited.has(claim));
});
