import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
type Profile={artifact_scope:string;sources:Array<{source_id:string;assignment_authority:string;geometry_authority:string;redistribution_class:string;bundled_here:boolean}>;artifact_partitions:Array<{id:string}>};
type Manifest={repository:{name:string;country_code:string;maturity:string};release_scope:Record<string,boolean|string>;postal_system:Record<string,string>;promotion:{current_stage:string;hard_blockers:string[]}};
type Fixtures={country_code:string;synthetic:boolean;promotion_eligible:boolean;fixture_policy:{contains_real_addresses:boolean;contains_upstream_rows:boolean;contains_personal_data:boolean;postal_prefix:string;coordinates_are_geographic:boolean;postcodes_are_assignment_evidence:boolean};fixtures:Array<{fixture_id:string;synthetic_address:{postcode?:string};expected:{must_not_assert:string[]}}>};
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'); const seedRoot=resolve(root,'data/postal_country_packs/mv/postal-context'); const readJson=<T>(name:string)=>JSON.parse(readFileSync(resolve(seedRoot,name),'utf8')) as T;

test('Maldives seed separates assignments, prefixes, island geometry, feature codes, buildings, rights, and privacy',()=>{
 const value=readJson<Manifest>('repository-manifest.json'); assert.equal(value.repository.name,'agid-postal-mv'); assert.equal(value.repository.country_code,'MV'); assert.equal(value.repository.maturity,'M1_metadata'); assert.equal(value.release_scope.metadata_only,true); assert.equal(value.release_scope.contains_raw_source_data,false); assert.equal(value.release_scope.contains_real_addresses,false); assert.equal(value.release_scope.contains_personal_data,false); assert.equal(value.release_scope.contains_production_geometry,false); assert.equal(value.postal_system.current_code_format,'NNNNN');
 assert.match(value.postal_system.legal_rule,/Maldives Post.*five-digit.*UPU.*Malé-region.*atoll.*not canonical polygons.*building/i); assert.match(value.postal_system.assignment_rule,/five-character digit string.*leading zeroes.*Maldives Post.*validity.*LD Codes.*do not create.*postal area/i); assert.match(value.postal_system.geometry_rule,/No reviewed.*canonical national.*polygon.*island administrative join surface.*not a postal-authority polygon.*LD Codes.*never become official/i); assert.match(value.postal_system.building_rule,/civic-address identifier.*building geometry.*stable relation.*Land-registry.*OneMap.*never establish/i); assert.match(value.postal_system.licence_rule,/Maldives Post.*OneMap.*public viewer.*do not grant blanket.*Statistics maps.*independent verification/i); assert.match(value.postal_system.privacy_rule,/Recipients.*P.O. Box holders.*query.*households.*owners.*occupants.*census microdata.*excluded/i);
 for(const blocker of ['maldives-post-upu-or-service-row-presented-as-official-postcode-polygon','atoll-prefix-presented-as-complete-five-digit-assignment','onemap-island-or-administrative-boundary-presented-as-postal-authority-polygon','ld-code-or-fcode-presented-as-postcode-civic-address-or-building'])assert.ok(value.promotion.hard_blockers.includes(blocker));
});

test('Maldives source profile keeps postal, island, survey, statistics, building, and licence authorities separate',()=>{
 const profile=readJson<Profile>('source-profile.json'); const sources=new Map(profile.sources.map(source=>[source.source_id,source])); assert.equal(profile.artifact_scope,'metadata-only-contract-seed'); assert.ok(profile.sources.every(source=>source.bundled_here===false)); assert.match(sources.get('maldives-post')?.assignment_authority??'',/official_postcode_assignment/i); assert.equal(sources.get('maldives-post')?.geometry_authority,'none'); assert.equal(sources.get('upu-maldives-addressing-2004')?.geometry_authority,'none'); assert.match(sources.get('mlsa-maldives')?.geometry_authority??'',/source_qualified_geometry/i); assert.match(sources.get('maldives-onemap-island-api-2024')?.geometry_authority??'',/official_island_geometry/i); assert.match(sources.get('maldives-geomatics-land-survey-standard-2025')?.assignment_authority??'',/none_survey_standard/i); assert.equal(sources.get('maldives-bureau-statistics-gis-maps')?.redistribution_class,'R4_validation_only');
 for(const partition of ['official-postcode-assignments','official-postal-surface','island-administrative-join-surface','derived-delivery-surface','postal-service-and-civic-address','civic-address-and-building','island-land-statistics-and-private-restricted','territory-and-private-restricted'])assert.ok(profile.artifact_partitions.some(candidate=>candidate.id===partition));
});

test('Maldives fixtures keep synthetic five-digit codes and non-postal evidence non-authoritative',()=>{
 const pack=readJson<Fixtures>('fixtures/maldives-synthetic.json'); const postcodes=pack.fixtures.map(item=>item.synthetic_address.postcode).filter((value):value is string=>Boolean(value)); const prohibited=new Set(pack.fixtures.flatMap(item=>item.expected.must_not_assert)); assert.equal(pack.country_code,'MV'); assert.equal(pack.synthetic,true); assert.equal(pack.promotion_eligible,false); assert.equal(pack.fixture_policy.contains_real_addresses,false); assert.equal(pack.fixture_policy.contains_upstream_rows,false); assert.equal(pack.fixture_policy.contains_personal_data,false); assert.equal(pack.fixture_policy.coordinates_are_geographic,false); assert.equal(pack.fixture_policy.postcodes_are_assignment_evidence,false); assert.equal(pack.fixture_policy.postal_prefix,'99999'); assert.ok(postcodes.every(postcode=>/^\d{5}$/.test(postcode))); assert.ok(pack.fixtures.every(item=>item.fixture_id.startsWith('mv-syn-')));
 for(const claim of ['maldives-post-or-upu-row-is-official-postal-boundary','postal-service-object-is-area','ld-code-or-fcode-is-postcode','island-boundary-join-is-postal-authority-polygon','land-registry-survey-or-census-row-is-public-address-data','containment-or-proximity-is-exact-building-link','viewer-api-survey-submission-or-attribution-is-redistribution-right'])assert.ok(prohibited.has(claim));
});
