import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
type Profile={artifact_scope:string;sources:Array<{source_id:string;assignment_authority:string;geometry_authority:string;redistribution_class:string;bundled_here:boolean}>;artifact_partitions:Array<{id:string}>};
type Manifest={repository:{name:string;country_code:string;maturity:string};release_scope:Record<string,boolean|string>;postal_system:Record<string,string>;promotion:{current_stage:string;hard_blockers:string[]}};
type Fixtures={country_code:string;synthetic:boolean;promotion_eligible:boolean;fixture_policy:{contains_real_addresses:boolean;contains_upstream_rows:boolean;contains_personal_data:boolean;postal_prefix:string;coordinates_are_geographic:boolean;postcodes_are_assignment_evidence:boolean};fixtures:Array<{fixture_id:string;synthetic_address:{postcode?:string};expected:{must_not_assert:string[]}}>};
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'); const seedRoot=resolve(root,'data/postal_country_packs/la/postal-context'); const readJson=<T>(name:string)=>JSON.parse(readFileSync(resolve(seedRoot,name),'utf8')) as T;

test('Laos seed separates delivery codes, network objects, surfaces, administrative context, addresses, buildings, AGID, rights, and privacy',()=>{
 const value=readJson<Manifest>('repository-manifest.json'); assert.equal(value.repository.name,'agid-postal-la'); assert.equal(value.repository.country_code,'LA'); assert.equal(value.repository.maturity,'M1_metadata'); assert.equal(value.release_scope.metadata_only,true); assert.equal(value.release_scope.contains_raw_source_data,false); assert.equal(value.release_scope.contains_real_addresses,false); assert.equal(value.release_scope.contains_personal_data,false); assert.equal(value.release_scope.contains_production_geometry,false); assert.equal(value.postal_system.current_code_format,'NNNNN');
 assert.match(value.postal_system.legal_rule,/Postal Services Law.*location.*scope.*delivery.*post offices.*mail exchange.*mail routes.*not.*canonical national postal polygons.*buildings/i); assert.match(value.postal_system.assignment_rule,/five-character digit string.*leading zeroes.*Lao Postal Service.*P\.O\. boxes.*village names.*do not independently create/i); assert.match(value.postal_system.geometry_rule,/No reviewed.*canonical national Laos.*polygon.*derived postal-administrative join surface.*P\.O\. boxes.*route or non-area.*never become official/i); assert.match(value.postal_system.building_rule,/explicit rights-cleared civic-address identifier.*stable reviewed relation.*permitted building geometry.*Census GIS.*LaoLandReg.*not public.*nearest-building/i); assert.match(value.postal_system.agid_rule,/AGID.*independent spatial index.*versioned crosswalk.*without relabelling/i); assert.match(value.postal_system.licence_rule,/exact item or service URL.*terms or licence.*digest.*Blank copyright metadata.*not an open licence/i); assert.match(value.postal_system.privacy_rule,/P\.O\. Box holders.*household.*building locations.*owners.*occupants.*excluded/i); assert.match(value.postal_system.privacy_rule,/Electronic Data Law.*before access.*transfer.*publication/i);
 for(const blocker of ['lao-post-laopedia-or-law-reference-presented-as-official-postcode-polygon','administrative-boundary-village-or-census-geography-presented-as-postal-authority-geometry','nfms-public-service-or-blank-copyright-presented-as-open-licence','laolandreg-cadastral-personal-or-address-record-presented-as-public-building-data'])assert.ok(value.promotion.hard_blockers.includes(blocker));
});

test('Laos source profile keeps postal, law, allocation, boundaries, census, cadastre, data law, and OSM authorities separate',()=>{
 const profile=readJson<Profile>('source-profile.json'); const sources=new Map(profile.sources.map(source=>[source.source_id,source])); assert.equal(profile.artifact_scope,'metadata-only-contract-seed'); assert.ok(profile.sources.every(source=>source.bundled_here===false)); assert.match(sources.get('lao-post-postcode')?.assignment_authority??'',/official_current_assignment/i); assert.equal(sources.get('laos-postal-service-law-2013')?.geometry_authority,'none'); assert.match(sources.get('laopedia-laos-postcodes')?.assignment_authority??'',/official_public_allocation/i); assert.match(sources.get('nfms-laos-administrative-boundaries')?.geometry_authority??'',/official_administrative_geometry/i); assert.match(sources.get('lsb-laos-phc-2025')?.redistribution_class??'',/private_or_item_specific/i); assert.match(sources.get('laolandreg-laos')?.geometry_authority??'',/restricted_cadastral/i); assert.match(sources.get('laos-electronic-data-law')?.redistribution_class??'',/permission_required/i);
 for(const partition of ['official-postcode-assignments','post-office-po-box-mail-exchange-and-route-objects','official-postal-surface','derived-postal-administrative-join-surface','province-district-village-context','civic-address-and-building','census-household-dwelling-and-building-private','cadastral-and-personal-private','agid-crosswalk'])assert.ok(profile.artifact_partitions.some(candidate=>candidate.id===partition));
});

test('Laos fixtures keep synthetic codes and non-postal evidence non-authoritative',()=>{
 const pack=readJson<Fixtures>('fixtures/laos-synthetic.json'); const postcodes=pack.fixtures.map(item=>item.synthetic_address.postcode).filter((value):value is string=>Boolean(value)); const prohibited=new Set(pack.fixtures.flatMap(item=>item.expected.must_not_assert)); assert.equal(pack.country_code,'LA'); assert.equal(pack.synthetic,true); assert.equal(pack.promotion_eligible,false); assert.equal(pack.fixture_policy.contains_real_addresses,false); assert.equal(pack.fixture_policy.contains_upstream_rows,false); assert.equal(pack.fixture_policy.contains_personal_data,false); assert.equal(pack.fixture_policy.coordinates_are_geographic,false); assert.equal(pack.fixture_policy.postcodes_are_assignment_evidence,false); assert.equal(pack.fixture_policy.postal_prefix,'99999'); assert.ok(postcodes.every(postcode=>/^\d{5}$/.test(postcode))); assert.ok(pack.fixtures.every(item=>item.fixture_id.startsWith('la-syn-')));
 for(const claim of ['lao-post-laopedia-or-law-reference-is-official-postal-boundary','post-office-po-box-mail-exchange-or-mail-route-is-guaranteed-area','administrative-boundary-village-or-census-geography-is-postal-authority-polygon','address-query-is-public-dataset','census-or-laolandreg-is-public-building-data','postcode-containment-or-proximity-is-exact-building-link','public-page-viewer-law-or-project-document-is-artifact-licence'])assert.ok(prohibited.has(claim));
});
