import assert from 'node:assert/strict';
import { test } from 'node:test';
import { PostalContextPackRuntime, normalizePanamaPostalCode, validatePostalContextRuntimePack } from './postalContextPackRuntime';
import { PANAMA_POSTAL_CONTEXT_TEST_INSTANT, PANAMA_POSTAL_CONTEXT_TEST_POINT, createPanamaPostalContextRuntimeTestPack } from '../testFixtures/postalContextPanamaRuntimeFixture';

test('Panama pack keeps API assignment, PICO cell, administration, explicit building relation, and AGID separate', () => { const pack = createPanamaPostalContextRuntimeTestPack(); const validation = validatePostalContextRuntimePack(pack, 'PA'); const polygon = pack.geometry.features.find(feature => feature.role === 'postal_area'); assert.equal(validation.valid, true, validation.errors.join('; ')); assert.equal(normalizePanamaPostalCode('ｚ９ｚｚｚ－ｚｚｚｚｚ'), 'Z9ZZZ-ZZZZZ'); assert.equal(normalizePanamaPostalCode('z9zzzzzzzz'), 'Z9ZZZ-ZZZZZ'); assert.equal(normalizePanamaPostalCode('zzzzzzzz'), 'ZZZ-ZZZZZ'); assert.equal(normalizePanamaPostalCode('Z9ZZZ/ZZZZZ'), null); assert.equal(polygon?.quality.status, 'derived'); assert.equal(polygon?.source.sourceId, 'pa-synthetic-derived-pico-validation-polygon'); assert.notEqual(polygon?.source.geometryAuthority, 'official_panama_postal_geometry'); });

test('Panama postcode lookup canonicalizes the full geolocated code and gates synthetic geometry', () => { const runtime = new PostalContextPackRuntime(createPanamaPostalContextRuntimeTestPack()); const lookup = runtime.lookupPostalCode('z9zzz-zzzzz', PANAMA_POSTAL_CONTEXT_TEST_INSTANT); const withGeometry = runtime.lookupPostalCode('Z9ZZZZZZZZ', PANAMA_POSTAL_CONTEXT_TEST_INSTANT, PANAMA_POSTAL_CONTEXT_TEST_INSTANT, true); assert.equal(lookup.status, 'unique'); assert.equal(lookup.countryCode, 'PA'); assert.equal(lookup.normalizedPostalCode, 'Z9ZZZ-ZZZZZ'); assert.deepEqual(lookup.geometries, []); assert.equal(withGeometry.geometries[0]?.geometry.type, 'Polygon'); });

test('Panama coordinate resolution reaches a building only through an explicit synthetic civic relation', () => { const runtime = new PostalContextPackRuntime(createPanamaPostalContextRuntimeTestPack()); const result = runtime.resolvePublicCoordinate({ ...PANAMA_POSTAL_CONTEXT_TEST_POINT, purpose: 'display', validAt: PANAMA_POSTAL_CONTEXT_TEST_INSTANT }); assert.equal(result.status, 'unique'); assert.equal(result.countryCode, 'PA'); assert.equal(result.resolvedLevel, 'building'); assert.equal(result.addressPointEvidence.matched, true); assert.deepEqual(result.postalEvidence, [{ postalCode: 'Z9ZZZ-ZZZZZ', relation: 'inside' }]); assert.equal(result.selected?.components.some(component => component.label === 'Synthetic explicitly address-linked Panamanian building'), true); });

test('Panama bbox lookup returns only the synthetic derived PICO validation surface', () => { const runtime = new PostalContextPackRuntime(createPanamaPostalContextRuntimeTestPack()); const result = runtime.intersectsPostalBbox([-79.52126,8.98120,-79.52120,8.98126], PANAMA_POSTAL_CONTEXT_TEST_INSTANT); assert.equal(result.status, 'unique'); assert.equal(result.matches[0]?.node.postalCode, 'Z9ZZZ-ZZZZZ'); assert.equal(result.matches[0]?.source.sourceId, 'pa-synthetic-derived-pico-validation-polygon'); });
