import type { SourceBoundaryEntry } from './sourceBoundary';

export const OPEN_SOURCE_SOURCE_BOUNDARY_ENTRIES: SourceBoundaryEntry[] = [
  {
    id: 'agid-aoid-public-standards',
    label: 'AGID/AOID public standards and test vectors',
    boundary: 'open-source',
    license: 'Apache-2.0',
    currentPaths: [
      'sdk/agid-spec/**',
      'sdk/agid-*/**',
      'src/lib/agid.ts',
      'src/lib/aoid.ts',
      'src/lib/agidSecureShare.ts',
    ],
    recommendedPaths: [
      'packages/oss/agid-spec/**',
      'packages/oss/agid-sdk/**',
      'packages/oss/agid-secure-share/**',
    ],
    compatibility: {
      stableImport: 'src/lib/agid.ts',
      keepCurrentPath: true,
      requiresShim: true,
      publicApiMustRemain: true,
      notes: [
        'Keep existing SDK paths until generated packages and import aliases are published.',
        'AGID encode/decode and AGID-S local decrypt remain independently implementable.',
      ],
    },
    guardrails: [
      'No private AOID descriptor examples in public test vectors.',
      'No raw address or recipient proof code in public fixtures.',
    ],
  },
  {
    id: 'local-resolver-address-display',
    label: 'Local resolver, address display, language tabs, and postal assist',
    boundary: 'open-source',
    license: 'Apache-2.0',
    currentPaths: [
      'src/lib/agidLocalResolver.ts',
      'src/lib/addressDisplay.ts',
      'src/lib/addressRendering.ts',
      'src/lib/addressValidation.ts',
      'src/lib/languageTabs.ts',
      'src/components/AddressLanguageTabs.tsx',
      'src/components/PostcodeInput.tsx',
      'src/data/address_formats/**',
    ],
    recommendedPaths: [
      'packages/oss/address-resolver/**',
      'packages/oss/address-rendering/**',
      'packages/oss/address-formats/**',
    ],
    compatibility: {
      stableImport: 'src/lib/addressDisplay.ts',
      keepCurrentPath: true,
      requiresShim: true,
      publicApiMustRemain: true,
      notes: [
        'Existing UI imports should continue to resolve while resolver packages are split out.',
        'Language switching and local address display are not commercial service dependencies.',
      ],
    },
    guardrails: [
      'Do not upload raw address text from local resolver paths.',
      'Expose user-facing decision states instead of internal quality scores.',
    ],
  },
  {
    id: 'address-registration-and-element',
    label: 'Address Registration and AGID Address Element',
    boundary: 'open-source',
    license: 'Apache-2.0',
    currentPaths: [
      'src/components/AddressRegistration.tsx',
      'src/components/AgidAddressElement.tsx',
      'src/lib/addressRegistrationState.ts',
      'src/lib/addressRegistrationAutomation.ts',
      'src/lib/addressRegistrationReadiness.ts',
      'src/lib/addressElement.ts',
      'src/lib/addressElementEvents.ts',
      'src/lib/addressElementReadiness.ts',
      'src/lib/addressLink.ts',
    ],
    recommendedPaths: [
      'apps/oss/address-registration/**',
      'packages/oss/address-element/**',
    ],
    compatibility: {
      stableImport: 'src/lib/addressElement.ts',
      keepCurrentPath: true,
      requiresShim: true,
      publicApiMustRemain: true,
      notes: [
        'Address Element stays embeddable without Hosted Registry or paid analytics.',
        'Registration feedback remains local-first and opt-in.',
      ],
    },
    guardrails: [
      'Host integration events must be redacted.',
      'Feedback learning must not sync private corrections without explicit consent.',
    ],
  },
  {
    id: 'basic-pos-terminal',
    label: 'Basic POS terminal, QR/NFC intake, local handoff, and receipts',
    boundary: 'open-source',
    license: 'Apache-2.0',
    currentPaths: [
      'src/components/PosAppScreen.tsx',
      'src/components/PosTerminalPanel.tsx',
      'src/components/pos/**',
      'src/lib/posAcceptance.ts',
      'src/lib/posOfflineUsageLedger.ts',
      'src/lib/posPrint.ts',
      'src/lib/posRuntimePolicy.ts',
      'src/lib/agidSecurePos.ts',
      'src/lib/shippingLabelQr.ts',
    ],
    recommendedPaths: [
      'apps/oss/pos-terminal/**',
      'packages/oss/pos-core/**',
    ],
    compatibility: {
      stableImport: 'src/lib/posAcceptance.ts',
      keepCurrentPath: true,
      requiresShim: true,
      publicApiMustRemain: true,
      notes: [
        'Scan -> Decision -> Handoff -> Report remains available in local mode.',
        'Advanced fleet management may be commercial, but local scan and receipt paths stay OSS.',
      ],
    },
    guardrails: [
      'Receipts store commitments and device signatures, not raw QR payloads.',
      'Offline queues must redact raw address fields before export.',
    ],
  },
  {
    id: 'address-portal-user-control',
    label: 'Address Portal user consent, revoke, delete, and export',
    boundary: 'open-source',
    license: 'Apache-2.0',
    currentPaths: [
      'src/components/AddressPortalScreen.tsx',
      'src/lib/addressPortal.ts',
      'src/lib/addressItem.ts',
      'src/lib/addressConsentEnvelope.ts',
      'src/lib/addressAccessAuth.ts',
      'src/lib/addressIdentity.ts',
    ],
    recommendedPaths: [
      'apps/oss/address-portal/**',
      'packages/oss/consent/**',
    ],
    compatibility: {
      stableImport: 'src/lib/addressPortal.ts',
      keepCurrentPath: true,
      requiresShim: true,
      publicApiMustRemain: true,
      notes: [
        'Users must always be able to review scope, revoke, delete, and export without a paid dashboard.',
        'Portal records should use aliases and scopes rather than private address text.',
      ],
    },
    guardrails: [
      'Never make revoke, delete, or export dependent on commercial services.',
      'Portal events must avoid raw AOID, raw address, and recipient secrets.',
    ],
  },
  {
    id: 'privacy-security-release-gates',
    label: 'Privacy, security, high-risk mode, and release gates',
    boundary: 'open-source',
    license: 'Apache-2.0',
    currentPaths: [
      'SECURITY.md',
      'src/lib/noRawAddressReleaseScan.ts',
      'src/lib/publicPrivateSeparation.ts',
      'src/lib/privacyHumanRightsPrinciples.ts',
      'src/lib/privacyPolicy.ts',
      'src/lib/securityPrivacyDesign.ts',
      'src/lib/securityMandatoryReleaseGate.ts',
      'scripts/verify-no-raw-address-release*.ts',
      'scripts/verify-external-audit-secret-scan.ts',
    ],
    recommendedPaths: [
      'packages/oss/security-gates/**',
      'docs/oss/security/**',
    ],
    compatibility: {
      stableImport: 'src/lib/noRawAddressReleaseScan.ts',
      keepCurrentPath: true,
      requiresShim: true,
      publicApiMustRemain: true,
      notes: [
        'No-raw-address tests and security fixes are part of the public trust boundary.',
        'High-risk mode must be auditable from source.',
      ],
    },
    guardrails: [
      'No release path may require paid services for redaction or high-risk mode.',
      'Secret scans run before external publication.',
    ],
  },
  {
    id: 'zk-baseline-open-proof-relations',
    label: 'ZK baseline proof relations and public signal schemas',
    boundary: 'open-source',
    license: 'Apache-2.0',
    currentPaths: [
      'circuits/**',
      'src/lib/agidZkAddressProofs.ts',
      'src/lib/zkProofRuntime.ts',
      'src/lib/zkProofCompatibility.ts',
      'src/lib/zkProofBundleRegistry.ts',
      'src/lib/addressDuplicateNullifier.ts',
      'src/lib/aoidOwnershipProof.ts',
      'src/lib/credentialIssuerTrustRegistry.ts',
    ],
    recommendedPaths: [
      'packages/oss/zk-address-predicates/**',
      'packages/oss/zk-test-fixtures/**',
    ],
    compatibility: {
      stableImport: 'src/lib/zkProofRuntime.ts',
      keepCurrentPath: true,
      requiresShim: true,
      publicApiMustRemain: true,
      notes: [
        'Managed proving can be commercial; proof relations and fixtures remain public.',
        'Public signal schemas must be leakage-tested.',
      ],
    },
    guardrails: [
      'Witnesses and private inputs must not be logged.',
      'Verifier fixtures must not contain real address records.',
    ],
  },
  {
    id: 'developer-docs-research-and-test-vectors',
    label: 'Developer docs, AGID research links, verification notes, and test vectors',
    boundary: 'open-source',
    license: 'CC-BY-4.0',
    currentPaths: [
      'README.md',
      'CONTRIBUTING.md',
      'LICENSE_POLICY.md',
      'DATA_LICENSES.md',
      'docs/agid-spec-v0.1-rc.md',
      'docs/address-morphism-theory-*.md',
      'docs/zk-address-*.md',
      'docs/*verification*.md',
      'sdk/agid-spec/test-vectors.json',
    ],
    recommendedPaths: [
      'docs/oss/specs/**',
      'external/address-morphism-theory/**',
      'docs/oss/verification/**',
    ],
    compatibility: {
      stableImport: null,
      keepCurrentPath: true,
      requiresShim: false,
      publicApiMustRemain: true,
      notes: [
        'Address Morphism Theory manuscripts are canonically maintained in the independent address-morphism-theory repository.',
        'AGID keeps compatibility links or mirrored snapshots until research-page links and release scripts are migrated.',
        'Research claims must keep verification status visible.',
      ],
    },
    guardrails: [
      'Respect upstream data licenses in DATA_LICENSES.md.',
      'Do not edit AMT papers as AGID runtime implementation details.',
      'Separate AMT theory, AGID/AOID application, and ZK Address Predicate papers.',
    ],
  },
];
