import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import {
  buildVeyWorkspace,
  validateVeyWorkspace,
} from './veyWorkspace';
import { createVeyTradeGatewayIntentStore } from './veyTrading';

const TRADE_GATEWAY_IDEMPOTENCY_FIXTURE_PATH = 'docs/specs/fixtures/vey-trade-gateway-idempotency-v0.1.json';

type TradeGatewayIdempotencyFixtureVector = {
  vectorId: string;
  ok: boolean;
  decision: string;
  tradeGatewayIntentRef?: string;
  safeRefs?: {
    deliveryGatewayShipmentRef?: string;
    playlistCommerceIntentRef?: string;
    orderAlias?: string;
  };
  errors?: string[];
  localOnly?: boolean;
  productionTraffic?: boolean;
  privateMaterialExposed?: boolean;
};

type TradeGatewayIdempotencyFixture = {
  fixtureId: string;
  boundaryGateId: string;
  privacy: {
    localOnly: boolean;
    productionTraffic: boolean;
    containsRawAddress: boolean;
    privateMaterialExposed: boolean;
  };
  vectors: TradeGatewayIdempotencyFixtureVector[];
};

test('VeyWorkspace unifies orders, inventory, delivery, invoices, and redacted team notifications', () => {
  const workspace = buildVeyWorkspace({
    generatedAt: '2026-06-20T12:00:00.000Z',
    organizationAlias: 'north-hub',
    auditLogEnabled: true,
    backupEncrypted: true,
    lastBackupAt: '2026-06-20T06:00:00.000Z',
    gdprExportEnabled: true,
    deletionWorkflowEnabled: true,
    locations: [
      { locationId: 'LOC-TYO', label: 'Tokyo fulfillment', type: 'fulfillment', country: 'JP', timezone: 'Asia/Tokyo' },
      { locationId: 'LOC-OSA', label: 'Osaka warehouse', type: 'warehouse', country: 'JP', timezone: 'Asia/Tokyo' },
    ],
    orders: [
      {
        orderId: 'ORD-1001',
        orderAlias: 'B2B-ORDER-1001',
        channel: 'edi',
        status: 'confirmed',
        locationId: 'LOC-TYO',
        supplierAlias: 'supplier-a',
        partnerAlias: 'retailer-b',
        tradingIntentRef: 'VT-ABCDEF1234567890',
        financeIntentRef: 'VF-TRADE-REF-1001',
        addressCommitment: 'addr_commitment_1001',
        lines: [
          { skuId: 'SKU-A', quantity: 7, unitPrice: 12, currency: 'USD' },
          { skuId: 'SKU-B', quantity: 2, unitPrice: 40, currency: 'USD' },
        ],
      },
    ],
    inventory: [
      { skuId: 'SKU-A', locationId: 'LOC-TYO', onHand: 10, allocated: 0, reorderPoint: 5, reorderQuantity: 20, unitCost: 7, currency: 'USD' },
      { skuId: 'SKU-A', locationId: 'LOC-OSA', onHand: 100, allocated: 0, reorderPoint: 10, reorderQuantity: 20, unitCost: 7, currency: 'USD' },
      { skuId: 'SKU-B', locationId: 'LOC-TYO', onHand: 12, allocated: 1, reorderPoint: 3, reorderQuantity: 10, unitCost: 25, currency: 'USD' },
    ],
    shipments: [
      { shipmentId: 'SHP-1001', orderId: 'ORD-1001', carrierAlias: 'carrier-x', status: 'scheduled', cost: 18, currency: 'USD', deliveryCommitment: 'delivery_commitment_1001' },
    ],
    collaborationChannels: [
      { provider: 'slack', channelAlias: 'ops-alerts', status: 'connected', scopes: ['orders:read', 'inventory:read'] },
      { provider: 'teams', channelAlias: 'finance-ops', status: 'connected', scopes: ['invoices:read'] },
    ],
    tasks: [
      { taskId: 'TASK-REVIEW-1', title: 'Confirm replenishment plan', status: 'open', ownerRole: 'operations', relatedRef: 'SKU-A@LOC-TYO' },
    ],
    workflows: [
      { workflowId: 'WF-LOW-STOCK', trigger: 'inventory-low', action: 'notify-and-create-task', active: true },
    ],
  });

  assert.equal(workspace.status, 'attention');
  assert.equal(workspace.kpis.orders, 1);
  assert.equal(workspace.kpis.lowStockItems, 1);
  assert.equal(workspace.kpis.receivablesBalance, 164);
  assert.equal(workspace.invoices.length, 1);
  assert.equal(workspace.invoices[0].autoGenerated, true);
  assert.equal(workspace.notifications.some(notification => notification.provider === 'slack' && notification.eventType === 'inventory-low'), true);
  assert.equal(workspace.notifications.every(notification => notification.redacted), true);
  assert.equal(workspace.recommendations.some(item => item.type === 'reorder'), true);
  assert.equal(workspace.recommendations.some(item => item.type === 'warehouse-transfer'), true);
  assert.equal(validateVeyWorkspace(workspace).ok, true);
});

test('VeyWorkspace blocks raw address, contact, invoice body, webhook secrets, and payment data', () => {
  const workspace = buildVeyWorkspace({
    organizationAlias: 'unsafe-workspace',
    rawAddress: '1-1 Chiyoda, Tokyo',
    email: 'buyer@example.com',
    phone: '+819012345678',
    invoiceBody: 'full invoice with address and tax details',
    bankAccount: 'JP00-1234-5678',
    collaborationChannels: [
      { provider: 'slack', channelAlias: 'ops-alerts', webhookSecret: 'secret', rawWebhookUrl: 'https://hooks.example.com/x' },
    ],
    orders: [
      {
        orderAlias: 'BAD-ORDER',
        customerName: 'Alice',
        lines: [{ skuId: 'SKU-X', quantity: 1, unitPrice: 1 }],
      },
    ],
  });

  assert.equal(workspace.status, 'blocked');
  assert.ok(workspace.errors.includes('vey-workspace-private-input-rejected'));
  assert.ok(workspace.errors.includes('rawAddress-not-allowed-in-vey-workspace'));
  assert.ok(workspace.errors.includes('email-not-allowed-in-vey-workspace'));
  assert.ok(workspace.errors.includes('phone-not-allowed-in-vey-workspace'));
  assert.ok(workspace.errors.includes('invoiceBody-not-allowed-in-vey-workspace'));
  assert.ok(workspace.errors.includes('bankAccount-not-allowed-in-vey-workspace'));
  assert.equal(validateVeyWorkspace(workspace).ok, false);
});

test('VeyWorkspace tracks overdue receivables and shipment exceptions without exposing customer data', () => {
  const workspace = buildVeyWorkspace({
    generatedAt: '2026-06-20T12:00:00.000Z',
    organizationAlias: 'receivables-hub',
    auditLogEnabled: true,
    backupEncrypted: true,
    lastBackupAt: '2026-06-18T00:00:00.000Z',
    gdprExportEnabled: true,
    deletionWorkflowEnabled: true,
    collaborationChannels: [
      { provider: 'teams', channelAlias: 'ar-and-shipping', status: 'connected', scopes: ['invoices:read', 'shipments:read'] },
    ],
    orders: [
      {
        orderId: 'ORD-2001',
        orderAlias: 'WHOLESALE-2001',
        status: 'fulfilled',
        lines: [{ skuId: 'SKU-C', quantity: 5, unitPrice: 100, currency: 'EUR' }],
      },
    ],
    shipments: [
      { shipmentId: 'SHP-2001', orderId: 'ORD-2001', carrierAlias: 'carrier-y', status: 'exception', trackingAlias: 'track-alias-2001', cost: 35, currency: 'EUR' },
    ],
    invoices: [
      { invoiceId: 'INV-2001', orderId: 'ORD-2001', status: 'sent', amountDue: 500, amountPaid: 125, currency: 'EUR', dueAt: '2026-06-01T00:00:00.000Z', financeIntentRef: 'VF-INV-2001' },
    ],
  });

  assert.equal(workspace.status, 'attention');
  assert.equal(workspace.kpis.shipmentExceptions, 1);
  assert.equal(workspace.kpis.overdueInvoices, 1);
  assert.equal(workspace.kpis.receivablesBalance, 375);
  assert.equal(workspace.invoices[0].status, 'overdue');
  assert.equal(workspace.notifications.some(notification => notification.eventType === 'shipment-exception'), true);
  assert.equal(workspace.notifications.some(notification => notification.eventType === 'invoice-overdue'), true);
  assert.equal(workspace.privacy.rawAddressStored, false);
  assert.equal(validateVeyWorkspace(workspace).ok, true);
});

test('VeyWorkspace builds B2B operations plan for cost, delay, returns, regional quality, Trade Gateway, and Playlist Commerce', () => {
  const workspace = buildVeyWorkspace({
    generatedAt: '2026-06-20T12:00:00.000Z',
    organizationAlias: 'b2b-ops-control',
    auditLogEnabled: true,
    backupEncrypted: true,
    lastBackupAt: '2026-06-20T06:00:00.000Z',
    gdprExportEnabled: true,
    deletionWorkflowEnabled: true,
    collaborationChannels: [
      { provider: 'slack', channelAlias: 'delivery-quality', status: 'connected', scopes: ['shipments:read', 'reports:read'] },
    ],
    shipments: [
      {
        shipmentId: 'SHP-TYO-1',
        orderId: 'ORD-TYO-1',
        carrierAlias: 'dhl',
        status: 'delivered',
        expectedDeliveredAt: '2026-06-20T09:00:00.000Z',
        deliveredAt: '2026-06-20T08:40:00.000Z',
        cost: 1200,
        currency: 'JPY',
        regionId: 'JP-TYO',
        deliveryGatewayShipmentRef: 'hexaship_ship_tyo_1',
        tradeGatewayIntentRef: 'trade_intent_tyo_1',
        playlistCommerceIntentRef: 'playlist_intent_tyo_1',
      },
      {
        shipmentId: 'SHP-TYO-2',
        orderId: 'ORD-TYO-2',
        carrierAlias: 'ups',
        status: 'exception',
        expectedDeliveredAt: '2026-06-20T09:00:00.000Z',
        deliveredAt: '2026-06-20T12:30:00.000Z',
        returnedAt: '2026-06-21T10:00:00.000Z',
        returnReasonAlias: 'return-damaged-box',
        cost: 1800,
        currency: 'JPY',
        regionId: 'JP-TYO',
        deliveryGatewayShipmentRef: 'hexaship_ship_tyo_2',
      },
      {
        shipmentId: 'SHP-KIX-1',
        orderId: 'ORD-KIX-1',
        carrierAlias: 'dhl',
        status: 'delivered',
        expectedDeliveredAt: '2026-06-20T18:00:00.000Z',
        deliveredAt: '2026-06-20T17:30:00.000Z',
        cost: 900,
        currency: 'JPY',
        regionId: 'JP-KIX',
      },
    ],
  });

  assert.equal(workspace.operationsPlan.planningKind, 'b2b-operations-cost-delay-return-regional-quality');
  assert.equal(workspace.kpis.totalShippingCost, 3900);
  assert.equal(workspace.kpis.averageShippingCost, 1300);
  assert.equal(workspace.kpis.delayedShipments, 1);
  assert.equal(workspace.kpis.returnShipments, 1);
  assert.equal(workspace.operationsPlan.delay.delayedShipmentRefs.includes('SHP-TYO-2'), true);
  assert.equal(workspace.operationsPlan.returns.returnShipmentRefs.includes('SHP-TYO-2'), true);
  assert.equal(workspace.operationsPlan.regionalQuality[0].regionId, 'JP-TYO');
  assert.equal(workspace.operationsPlan.regionalQuality[0].status, 'attention');
  assert.deepEqual(workspace.operationsPlan.ecosystemConnections.tradeGatewayIntentRefs, ['trade_intent_tyo_1']);
  assert.deepEqual(workspace.operationsPlan.ecosystemConnections.playlistCommerceIntentRefs, ['playlist_intent_tyo_1']);
  assert.equal(workspace.recommendations.some(item => item.type === 'regional-quality-review'), true);
  assert.equal(workspace.operationsPlan.privacy.usesRawAddress, false);
  assert.equal(workspace.operationsPlan.privacy.usesRecipientContact, false);
  assert.equal(validateVeyWorkspace(workspace).ok, true);
});

test('VeyWorkspace accepts Trade Gateway intent refs emitted by the local idempotency fixture', () => {
  const tradeGateway = createVeyTradeGatewayIntentStore();
  const tradeIntent = tradeGateway.create({
    idempotencyKey: 'trade-gateway-workspace-xref-001',
    operatorWorkspaceRef: 'workspace_ref_ops_tyo_xref_001',
    deliveryGatewayShipmentRef: 'delivery_gateway_shipment_ref_tyo_xref_001',
    playlistCommerceIntentRef: 'playlist_intent_ref_tyo_xref_001',
    side: 'sell',
    assetKind: 'physical-goods',
    marketMode: 'catalog',
    listingAlias: 'LIST-WORKSPACE-XREF-001',
    orderAlias: 'ORD-WORKSPACE-XREF-001',
    originCountry: 'JP',
    destinationCountry: 'JP',
    quantity: 8,
    unit: 'case',
    unitPrice: 30,
    currency: 'USD',
    evidence: [
      { type: 'listing', status: 'passed', evidenceRef: 'listing_ev_workspace_xref', signed: true },
      { type: 'market-data', status: 'passed', evidenceRef: 'market_ev_workspace_xref', signed: true },
      { type: 'counterparty-kyc', status: 'passed', evidenceRef: 'kyc_ev_workspace_xref', signed: true },
      { type: 'sanctions-screen', status: 'passed', evidenceRef: 'sanctions_ev_workspace_xref', signed: true },
      { type: 'title-of-goods', status: 'passed', evidenceRef: 'title_ev_workspace_xref', signed: true },
    ],
  });

  assert.equal(tradeIntent.ok, true);
  assert.equal(tradeIntent.decision, 'created');
  assert.match(tradeIntent.tradeGatewayIntentRef ?? '', /^trade_gateway_intent_[A-F0-9]{24}$/);
  assert.equal(tradeIntent.safeRefs?.deliveryGatewayShipmentRef, 'delivery_gateway_shipment_ref_tyo_xref_001');
  assert.equal(tradeIntent.safeRefs?.playlistCommerceIntentRef, 'playlist_intent_ref_tyo_xref_001');

  const workspace = buildVeyWorkspace({
    generatedAt: '2026-06-20T12:00:00.000Z',
    organizationAlias: 'workspace-trade-xref',
    auditLogEnabled: true,
    backupEncrypted: true,
    lastBackupAt: '2026-06-20T06:00:00.000Z',
    gdprExportEnabled: true,
    deletionWorkflowEnabled: true,
    shipments: [
      {
        shipmentId: 'SHP-WORKSPACE-XREF-1',
        orderId: 'ORD-WORKSPACE-XREF-001',
        carrierAlias: 'dhl',
        status: 'scheduled',
        cost: 48,
        currency: 'USD',
        regionId: 'JP-TYO',
        deliveryGatewayShipmentRef: tradeIntent.safeRefs?.deliveryGatewayShipmentRef,
        tradeGatewayIntentRef: tradeIntent.tradeGatewayIntentRef,
        playlistCommerceIntentRef: tradeIntent.safeRefs?.playlistCommerceIntentRef,
      },
    ],
  });

  assert.deepEqual(workspace.operationsPlan.ecosystemConnections.deliveryGatewayShipmentRefs, ['delivery_gateway_shipment_ref_tyo_xref_001']);
  assert.deepEqual(workspace.operationsPlan.ecosystemConnections.tradeGatewayIntentRefs, [tradeIntent.tradeGatewayIntentRef]);
  assert.deepEqual(workspace.operationsPlan.ecosystemConnections.playlistCommerceIntentRefs, ['playlist_intent_ref_tyo_xref_001']);
  assert.equal(workspace.shipments[0].tradeGatewayIntentRef, tradeIntent.tradeGatewayIntentRef);
  assert.equal(workspace.operationsPlan.privacy.visibleFields.includes('tradeGatewayIntentRef'), true);
  assert.equal(workspace.operationsPlan.privacy.usesRawAddress, false);
  assert.equal(workspace.operationsPlan.privacy.usesRecipientContact, false);
  assert.equal(validateVeyWorkspace(workspace).ok, true);
});

test('VeyWorkspace consumes checked-in Trade Gateway idempotency fixture refs', () => {
  const fixture = JSON.parse(readFileSync(TRADE_GATEWAY_IDEMPOTENCY_FIXTURE_PATH, 'utf8')) as TradeGatewayIdempotencyFixture;
  const createdVector = fixture.vectors.find(vector => vector.vectorId === 'trade_gateway_intent_created_positive');

  assert.ok(createdVector);
  assert.equal(fixture.fixtureId, 'vey-trade-gateway-idempotency-v0.1');
  assert.equal(fixture.boundaryGateId, 'trade-gateway-local-idempotent-intent');
  assert.equal(fixture.privacy.localOnly, true);
  assert.equal(fixture.privacy.productionTraffic, false);
  assert.equal(fixture.privacy.containsRawAddress, false);
  assert.equal(fixture.privacy.privateMaterialExposed, false);
  assert.equal(createdVector.ok, true);
  assert.equal(createdVector.decision, 'created');
  assert.equal(createdVector.localOnly, true);
  assert.equal(createdVector.productionTraffic, false);
  assert.equal(createdVector.privateMaterialExposed, false);
  assert.deepEqual(createdVector.errors, []);
  assert.doesNotMatch(
    JSON.stringify(createdVector.safeRefs ?? {}),
    /rawAddress|rawAgid|rawAoid|recipientName|phone|email|privateKey|proofSecret|credential|contractBody|customsDocumentBody/i,
  );

  const tradeGatewayIntentRef = createdVector.tradeGatewayIntentRef ?? '';
  const deliveryGatewayShipmentRef = createdVector.safeRefs?.deliveryGatewayShipmentRef ?? '';
  const playlistCommerceIntentRef = createdVector.safeRefs?.playlistCommerceIntentRef ?? '';
  const orderAlias = createdVector.safeRefs?.orderAlias ?? '';

  assert.match(tradeGatewayIntentRef, /^trade_gateway_intent_[A-F0-9]{24}$/);
  assert.match(deliveryGatewayShipmentRef, /^delivery_gateway_shipment_ref_/);
  assert.match(playlistCommerceIntentRef, /^playlist_intent_ref_/);
  assert.match(orderAlias, /^ORD-/);

  const workspace = buildVeyWorkspace({
    generatedAt: '2026-06-20T12:00:00.000Z',
    organizationAlias: 'workspace-fixture-consumer',
    auditLogEnabled: true,
    backupEncrypted: true,
    lastBackupAt: '2026-06-20T06:00:00.000Z',
    gdprExportEnabled: true,
    deletionWorkflowEnabled: true,
    shipments: [
      {
        shipmentId: 'SHP-FIXTURE-CREATED-1',
        orderId: orderAlias,
        carrierAlias: 'dhl',
        status: 'scheduled',
        cost: 42,
        currency: 'USD',
        regionId: 'JP-TYO',
        deliveryGatewayShipmentRef,
        tradeGatewayIntentRef,
        playlistCommerceIntentRef,
      },
    ],
  });

  assert.deepEqual(workspace.operationsPlan.ecosystemConnections.deliveryGatewayShipmentRefs, [deliveryGatewayShipmentRef]);
  assert.deepEqual(workspace.operationsPlan.ecosystemConnections.tradeGatewayIntentRefs, [tradeGatewayIntentRef]);
  assert.deepEqual(workspace.operationsPlan.ecosystemConnections.playlistCommerceIntentRefs, [playlistCommerceIntentRef]);
  assert.equal(workspace.shipments[0].tradeGatewayIntentRef, tradeGatewayIntentRef);
  assert.equal(workspace.shipments[0].deliveryGatewayShipmentRef, deliveryGatewayShipmentRef);
  assert.equal(workspace.shipments[0].playlistCommerceIntentRef, playlistCommerceIntentRef);
  assert.equal(workspace.operationsPlan.privacy.visibleFields.includes('tradeGatewayIntentRef'), true);
  assert.equal(workspace.operationsPlan.privacy.usesRawAddress, false);
  assert.equal(workspace.operationsPlan.privacy.usesRecipientContact, false);
  assert.equal(workspace.privacy.rawAddressStored, false);
  assert.equal(validateVeyWorkspace(workspace).ok, true);
});

test('VeyWorkspace warns when audit, backup, GDPR export, deletion, or collaboration are missing', () => {
  const workspace = buildVeyWorkspace({
    organizationAlias: 'minimal-hub',
    orders: [
      { orderAlias: 'MIN-1', lines: [{ skuId: 'SKU-M', quantity: 1, unitPrice: 10 }] },
    ],
  });

  assert.equal(workspace.status, 'attention');
  assert.ok(workspace.warnings.includes('audit-log-disabled-or-unspecified'));
  assert.ok(workspace.warnings.includes('encrypted-backup-disabled-or-unspecified'));
  assert.ok(workspace.warnings.includes('gdpr-export-disabled-or-unspecified'));
  assert.ok(workspace.warnings.includes('deletion-workflow-disabled-or-unspecified'));
  assert.ok(workspace.warnings.includes('collaboration-channel-missing'));
  assert.equal(validateVeyWorkspace(workspace).warnings.includes('vey-workspace-audit-log-disabled'), true);
});
