import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

import {
  createVeyIdCoreMerchantVisibleRedactionAdapterFixture,
  displayRefsFromMerchantVisibleRedactionContract,
  loadHostedAddressLoginMerchantVisibleRedactionDisplayContract,
} from '../../sdk/veygrit-address-login-test-helpers/merchantVisibleRedactionFixtures';
import { MerchantConsoleScreen } from './MerchantConsoleScreen';

const here = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(here, 'MerchantConsoleScreen.tsx'), 'utf8');
const rootSource = readFileSync(join(here, '..', 'RootApp.tsx'), 'utf8');
const navigationSource = readFileSync(join(here, '..', 'lib', 'appNavigation.ts'), 'utf8');

function extractHostedRedactionHtml(html: string): string {
  const redactionStart = html.indexOf('data-merchant-visible-redaction-contract="hosted-test-vectors"');
  assert.ok(redactionStart >= 0, 'expected hosted redaction contract card in SSR output');
  const redactionEnd = html.indexOf('Vey Ecosystem operations map', redactionStart);
  assert.ok(redactionEnd > redactionStart, 'expected redaction card before Vey Ecosystem section');
  return html.slice(redactionStart, redactionEnd);
}

function extractCarrierCoverageMatrixHtml(html: string): string {
  const coverageStart = html.indexOf('Address Wallet carrier coverage matrix');
  assert.ok(coverageStart >= 0, 'expected carrier coverage matrix in SSR output');
  const coverageEnd = html.indexOf('Hexaship shipment creation readiness', coverageStart);
  assert.ok(coverageEnd > coverageStart, 'expected carrier coverage matrix before shipment readiness section');
  const skipshipLedgerStart = html.indexOf('Skipship webhook ledger', coverageStart);
  assert.ok(skipshipLedgerStart > coverageEnd, 'expected real Skipship webhook ledger after carrier coverage matrix');
  return html.slice(coverageStart, coverageEnd);
}

function renderMerchantConsoleWithWarnings(): { html: string; renderWarnings: string[] } {
  const renderWarnings: string[] = [];
  const originalConsoleError = console.error;

  console.error = (...args: unknown[]) => {
    renderWarnings.push(args.map(String).join(' '));
  };

  try {
    return {
      html: renderToStaticMarkup(React.createElement(MerchantConsoleScreen)),
      renderWarnings,
    };
  } finally {
    console.error = originalConsoleError;
  }
}

function assertNoMerchantConsoleWarnings(renderWarnings: string[]) {
  assert.deepEqual(
    renderWarnings,
    [],
    `expected Merchant Console SSR render to be warning-free, got: ${renderWarnings.join('\n')}`,
  );
}

test('Merchant Console screen exposes callback, webhook, policy, and test-vector setup', () => {
  assert.match(source, /Address Login Merchant Console/);
  assert.match(source, /Merchant Console beta/);
  assert.match(source, /Callback URL validator/);
  assert.match(source, /Run synthetic test vectors/);
  assert.match(source, /Callback preflight repair actions/);
  assert.match(source, /Negative fixture export/);
  assert.match(source, /Copy callback preflight negative fixture/);
  assert.match(source, /Copy negative fixture/);
  assert.match(source, /callbackPreflightNegativeFixture\.fixtureId/);
  assert.match(source, /Address Login live enablement gates/);
  assert.match(source, /Redacted lifecycle operations/);
  assert.match(source, /Skipship webhook ledger/);
  assert.match(source, /Redacted event idempotency view/);
  assert.match(source, /Events/);
  assert.match(source, /Retrying/);
  assert.match(source, /Expired/);
  assert.match(source, /source:/);
  assert.match(source, /localOnly:/);
  assert.match(source, /productionTraffic:/);
  assert.match(source, /Vey Ecosystem operations map/);
  assert.match(source, /Wallet, Address Login, Playlist Commerce, Delivery Gateway, and Carrier API Stripe/);
  assert.match(source, /Sandbox carrier smoke/);
  assert.match(source, /rate -&gt; allocate -&gt; label -&gt; tracking webhook -&gt; delivery proof/);
  assert.match(source, /sandboxCarrierSmoke\.steps\.map\(step => \(\s*<div key=\{step\.surface\}/);
  assert.doesNotMatch(source, /sandboxCarrierSmoke\.steps\.map\(step => \(\s*<div key=\{step\.id\}/);
  assert.match(source, /Address Wallet carrier coverage matrix/);
  assert.match(source, /key="merchant-console-carrier-coverage-matrix"/);
  assert.match(source, /key="merchant-console-carrier-coverage-matrix-header"/);
  assert.equal(source.match(/key="merchant-console-skipship-webhook-ledger"/g)?.length, 1);
  assert.match(source, /DHL\/UPS country forms before runtime capability checks/);
  assert.match(source, /MVP country forms/);
  assert.match(source, /Carrier runtime boundary/);
  assert.match(source, /Carrier form preflight next actions/);
  assert.match(source, /Active preflight next action/);
  assert.match(source, /Wallet form policy/);
  assert.match(source, /User familiar country form - carrier label shape is generated server-side/);
  assert.match(source, /poBoxSpellings/);
  assert.match(source, /P\/O Box/);
  assert.match(source, /normalizeAddressWalletPoBoxSpelling/);
  assert.match(source, /P\/O\/BOX/);
  assert.match(source, /normalizedPoBox/);
  assert.match(source, /poBoxSpellingAccepted/);
  assert.match(source, /carrierShapeInUI/);
  assert.match(source, /nextLabelAction/);
  assert.match(source, /function CarrierCountryPreflightSelector/);
  assert.match(source, /selectedCarrierCode/);
  assert.match(source, /selectedCountryCode/);
  assert.match(source, /selectionNextAction/);
  assert.match(source, /preflightNextAction/);
  assert.match(source, /missingWalletFields/);
  assert.match(source, /capabilityMode/);
  assert.match(source, /capabilityModes:/);
  assert.match(source, /streetLevelValidationCountryCodes:/);
  assert.match(source, /serverSideRuntimeChecksRequired:/);
  assert.match(source, /Merchant-visible refs/);
  assert.match(source, /Blocked material/);
  assert.match(source, /Hosted \/test-vectors redaction/);
  assert.match(source, /Merchant-visible display contract/);
  assert.match(source, /data-merchant-visible-redaction-contract/);
  assert.match(source, /hostedMerchantVisibleRedactionContract/);
  assert.match(source, /hostedMerchantVisibleRedactionCopyPayload/);
  assert.match(source, /copyHostedAddressLoginMerchantVisibleRedactionClipboardPayload/);
  assert.match(source, /MerchantVisibleRedactionContractCard/);
  assert.match(source, /displayRefsByField/);
  assert.match(source, /copyPayload\.label/);
  assert.match(source, /Copy hosted redaction refs/);
  assert.match(source, /copyPayload\.buttonLabel/);
  assert.match(source, /copyPayload\.successLabel/);
  assert.match(source, /Hexaship shipment creation readiness/);
  assert.match(source, /Shipment Readiness/);
  assert.match(source, /Create shipment/);
  assert.match(source, /Shipment blocked/);
  assert.match(source, /Local Hexaship result/);
  assert.match(source, /Gateway preflight/);
  assert.match(source, /Gateway can create/);
  assert.match(source, /Gateway missing refs/);
  assert.match(source, /Capability preflight/);
  assert.match(source, /Capability preflight result/);
  assert.match(source, /deliveryGatewaySurface/);
  assert.match(source, /surfaceBoundary/);
  assert.match(source, /productionAvailabilityClaim/);
  assert.match(source, /Capability ref override/);
  assert.match(source, /Guided two-step/);
  assert.match(source, /Guided step/);
  assert.match(source, /Primary action/);
  assert.match(source, /Redacted shipment history/);
  assert.match(source, /Local Hexaship shipment history/);
  assert.match(source, /Sandbox-created refs/);
  assert.match(source, /Synthetic merchant history/);
  assert.match(source, /No local Hexaship shipment created yet/);
  assert.match(source, /Local idempotency ledger/);
  assert.match(source, /Create shipment and webhook replay refs/);
  assert.match(source, /Copy latest webhook ref/);
  assert.match(source, /Copy ref/);
  assert.match(source, /Copied ref/);
  assert.match(source, /webhookReplayStatus/);
  assert.match(source, /safeWebhookReplayRef/);
  assert.match(source, /acceptedReplayKind/);
  assert.match(source, /conflictReplayKind/);
  assert.match(source, /safeBodyFingerprintRef/);
  assert.match(source, /ReplayKindBadge/);
  assert.match(source, /sm:grid-cols-2 xl:grid-cols-4/);
  assert.match(source, /compactGrid/);
  assert.match(source, /maxCols/);
  assert.match(source, /wrappedRefs/);
  assert.match(source, /addressExposure/);
  assert.match(source, /No local idempotency ledger rows yet/);
  assert.match(source, /Local Hexaship webhook replay/);
  assert.match(source, /Created shipment lifecycle refs/);
  assert.match(source, /No local Hexaship webhook events yet/);
  assert.match(source, /selectedCarrier/);
  assert.match(source, /idempotencyKey/);
  assert.match(source, /decisionRef/);
  assert.match(source, /duplicateClicks/);
  assert.match(source, /SDK \/ route fixture/);
  assert.match(source, /Copy fixture/);
  assert.match(source, /Copied fixture/);
  assert.match(source, /sdkRequestOptions\.idempotencyKey/);
  assert.match(source, /headers\.idempotency-key/);
  assert.match(source, /headers\.x-hexaship-local-only/);
  assert.match(source, /bodyRefs\.addressFormVersion/);
  assert.match(source, /bodyRefs\.carrierCapabilityRef/);
  assert.match(source, /replayPreview\.replayStatus/);
  assert.match(source, /replayPreview\.safeReplayRef/);
  assert.match(source, /replayPreview\.duplicateClickCount/);
  assert.match(source, /replayPreview\.productionTraffic/);
  assert.match(source, /localOnly/);
  assert.match(source, /blocked_missing_carrier_capability/);
  assert.match(source, /ready_for_hexaship_createShipment/);
  assert.match(source, /run_address_wallet_preflight -&gt; run_carrier_capability_preflight -&gt; ready_for_hexaship_createShipment/);
  assert.match(source, /Playlist Commerce webhook OpenAPI preflight/);
  assert.match(source, /docs\/specs\/playlist-commerce-webhooks\.openapi\.yaml/);
  assert.match(source, /Synthetic signed ping/);
  assert.match(source, /Preflight report/);
  assert.match(source, /Preflight history/);
  assert.match(source, /Evidence Vault reference/);
  assert.match(source, /Latest evidence/);
  assert.match(source, /Next safe step/);
  assert.match(source, /Passed/);
  assert.match(source, /Accepted/);
  assert.match(source, /Replay/);
  assert.match(source, /Webhook HMAC validator/);
  assert.match(source, /Webhook key rotation readiness/);
  assert.match(source, /Rollout phases/);
  assert.match(source, /Evidence vectors/);
  assert.match(source, /Negative fixture gate/);
  assert.match(source, /Safe callback preview/);
  assert.match(source, /Privacy boundary/);
  assert.match(source, /Shipping Stripe onboarding/);
  assert.match(source, /One Hexaship integration for DHL and UPS/);
  assert.match(source, /EC SDK call/);
  assert.match(source, /Merchant onboarding SDK/);
  assert.match(source, /Copy Merchant onboarding SDK snippet/);
  assert.match(source, /merchantOnboardingSdkCopyPayload\.buttonLabel/);
  assert.match(source, /merchantOnboardingSdkCopyPayload\.successLabel/);
  assert.match(source, /merchantConsoleOnboardingFixture/);
  assert.match(source, /buildMerchantConsoleOnboardingOpenApiContractCopyPayload/);
  assert.match(source, /buildMerchantConsoleOnboardingOpenApiContractStatus/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus/);
  assert.match(source, /merchantOnboardingOpenApiContractCopyPayload/);
  assert.match(source, /Merchant onboarding OpenAPI contract/);
  assert.match(source, /Copy Merchant onboarding OpenAPI contract/);
  assert.match(source, /copyMerchantOnboardingOpenApiContract/);
  assert.match(source, /copiedOnboardingContract/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.path/);
  assert.match(source, /docs\/specs\/fixtures\/merchant-console-onboarding-v0\.1\.json/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.contractState/);
  assert.match(source, /enabled carriers/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.enabledCarriers\.join\(' \+ '\)/);
  assert.match(source, /Vey ID client/);
  assert.match(source, /Callback preflight/);
  assert.match(source, /Callback contract/);
  assert.match(source, /Callback preflight passed/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.addressLoginClientRef/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.addressLoginCallbackPreflightRef/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.callbackContractVersion/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.callbackPreflightPassed/);
  assert.match(source, /address form/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.addressFormVersionRef/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.safetyFlags/);
  assert.match(source, /Merchant visible/);
  assert.match(source, /Hidden from EC/);
  assert.match(source, /mode\.title/);
  assert.match(source, /mode\.target/);
  assert.match(source, /mode\.primaryInstallArtifact/);
  assert.match(source, /STEP \{index \+ 1\}/);
  assert.match(source, /step\.fieldGroups\.flatMap/);
  assert.match(source, /field\.required/);
  assert.match(source, /field\.id/);
  assert.match(source, /field\.label/);
  assert.match(source, /addressFormVersionRef/);
  assert.match(source, /carrierSpecificAddressShapeBlocked/);
  assert.match(source, /API keys/);
  assert.match(source, /Webhook events/);
  assert.match(source, /Production review/);
  assert.match(source, /Vey ID Core adoption check/);
  assert.match(source, /Google\/Apple account creation/);
  assert.match(source, /PKCE server exchange/);
  assert.match(source, /Wallet-side revocation/);
  assert.match(source, /SDK packages/);
  assert.match(source, /Required controls/);
  assert.match(source, /Verifier commands/);
  assert.match(source, /Merchant visible refs/);
  assert.match(source, /Browser-only refs/);
  assert.match(source, /Server-only refs/);
});

test('Merchant Console is driven by Address Login executable setup preflight helpers', () => {
  assert.match(source, /buildAddressLoginMerchantIntegration/);
  assert.match(source, /buildHostedAddressLoginWebhookKeyRotationRunbook/);
  assert.match(source, /buildHostedAddressLoginMerchantVisibleRedactionCopyPayload/);
  assert.match(source, /buildVeyEcosystemResearch/);
  assert.match(source, /buildMerchantConsoleEcPluginPlan/);
  assert.match(source, /buildMerchantConsoleMerchantOnboardingSdkCopyPayload/);
  assert.match(source, /buildMerchantConsoleCallbackPreflightRepairActions/);
  assert.match(source, /buildMerchantConsoleCallbackPreflightNegativeFixture/);
  assert.match(source, /buildMerchantConsoleCallbackPreflightNegativeFixtureCopyText/);
  assert.match(source, /buildMerchantConsoleClipboardRedactionAudit/);
  assert.match(source, /merchantConsoleClipboardRedactionAudit/);
  assert.match(source, /localHexashipShipmentRecords: localHexashipShipments/);
  assert.match(source, /merchantConsoleClipboardRedactionAudit\.candidateCount/);
  assert.match(source, /merchantConsoleClipboardRedactionAudit\.privateMaterialExposed/);
  assert.match(source, /merchantOnboardingSdkCopyPayload/);
  assert.match(source, /merchantOnboardingSdkCopyPayload\.clipboardText/);
  assert.match(source, /merchantOnboardingSdkCopyPayload\.buttonLabel/);
  assert.match(source, /merchantOnboardingSdkCopyPayload\.successLabel/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.safetyFlags\.map/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.contractState/);
  assert.match(source, /merchantOnboardingOpenApiContractStatus\.verifier/);
  assert.match(source, /merchantOnboardingOpenApiContractCopyPayload\.clipboardText/);
  assert.match(source, /merchantOnboardingOpenApiContractCopyPayload\.buttonLabel/);
  assert.match(source, /merchantOnboardingOpenApiContractCopyPayload\.successLabel/);
  assert.match(source, /navigator\.clipboard\?\.writeText\(merchantOnboardingOpenApiContractCopyPayload\.clipboardText\)/);
  assert.match(source, /const callbackPreflightRepairActions = React\.useMemo/);
  assert.match(source, /const callbackPreflightNegativeFixture = React\.useMemo/);
  assert.match(source, /copiedCallbackNegativeFixture/);
  assert.match(source, /copyCallbackNegativeFixture/);
  assert.match(source, /navigator\.clipboard\?\.writeText\(buildMerchantConsoleCallbackPreflightNegativeFixtureCopyText\(callbackPreflightNegativeFixture\)\)/);
  assert.match(source, /callbackPreflightRepairActions\.map/);
  assert.match(source, /callbackPreflightNegativeFixture\.expectedMissingRefs\.join/);
  assert.match(source, /callbackPreflightNegativeFixture\.repairActionIds\.join/);
  assert.match(source, /callbackPreflightNegativeFixture\.forbiddenValueParamRefs\.join/);
  assert.match(source, /callbackPreflightNegativeFixture\.callbackValidationVectorIds\.join/);
  assert.match(source, /callbackPreflightNegativeFixture\.exportCommand/);
  assert.match(source, /copiedOnboardingSdk/);
  assert.match(source, /copyMerchantOnboardingSdkSnippet/);
  assert.match(source, /navigator\.clipboard\?\.writeText\(merchantOnboardingSdkCopyPayload\.clipboardText\)/);
  assert.match(source, /merchantConsolePlan\.integrationModes\.map/);
  assert.match(source, /merchantConsolePlan\.onboardingSteps\.map/);
  assert.match(source, /merchantConsolePlan\.apiKeyPolicy\.keyRefs\.map/);
  assert.match(source, /merchantConsolePlan\.webhookSetup\.events\.map/);
  assert.match(source, /merchantConsolePlan\.productionReviewGates\.slice/);
  assert.match(source, /const veyIdAdoptionCheck = merchantConsolePlan\.veyIdAdoptionCheck/);
  assert.match(source, /veyIdAdoptionCheck\.accountCreationProviders\.map/);
  assert.match(source, /veyIdAdoptionCheck\.requiredRoutes\.map/);
  assert.match(source, /veyIdAdoptionCheck\.requiredSdkPackages\.map/);
  assert.match(source, /veyIdAdoptionCheck\.requiredControls\.map/);
  assert.match(source, /veyIdAdoptionCheck\.verifierCommands\.map/);
  assert.match(source, /veyIdAdoptionCheck\.merchantVisibleRefs\.map/);
  assert.match(source, /veyIdAdoptionCheck\.browserOnlyRefs\.map/);
  assert.match(source, /veyIdAdoptionCheck\.serverOnlyRefs\.map/);
  assert.match(source, /veyIdAdoptionCheck\.walletRevocationRefs\.map/);
  assert.match(source, /veyIdAdoptionCheck\.blockedMaterial\.slice\(0, 8\)\.map/);
  assert.match(source, /merchantConsolePlan\.ecCreateShipmentExample\.sdkCall/);
  assert.match(source, /merchantConsolePlan\.ecCreateShipmentExample\.merchantVisibleRefs\.map/);
  assert.match(source, /merchantConsolePlan\.ecCreateShipmentExample\.merchantHiddenMaterial\.map/);
  assert.match(source, /merchantConsolePlan\.ecCreateShipmentExample\.hiddenBackendPipeline\.map/);
  assert.match(source, /buildMerchantConsoleLocalHexashipRequestFixture/);
  assert.match(source, /buildMerchantConsoleCarrierCapabilityPreflight/);
  assert.match(source, /buildMerchantConsoleGuidedShipmentStep/);
  assert.match(source, /buildMerchantConsoleLocalHexashipRequestFixtureCopyText/);
  assert.match(source, /buildMerchantConsoleLocalHexashipReplayPreview/);
  assert.match(source, /buildMerchantConsoleLocalHexashipIdempotencyLedgerRows/);
  assert.match(source, /buildMerchantConsoleLocalHexashipLedgerLayoutAudit/);
  assert.match(source, /buildMerchantConsoleLocalHexashipWebhookReplayFixture/);
  assert.match(source, /evaluateMerchantShipmentCreationReadiness/);
  assert.match(source, /runHexashipMvpV01Sandbox/);
  assert.match(source, /createLocalHexashipShipment/);
  assert.match(source, /readiness\.gatewayPreflight\.ok/);
  assert.match(source, /readiness\.gatewayPreflight\.requiredNextAction/);
  assert.match(source, /readiness\.gatewayPreflight\.missingAddressWalletRefs/);
  assert.match(source, /readiness\.gatewayPreflight\.missingCarrierRefs/);
  assert.match(source, /function CarrierCapabilityPreflightButton/);
  assert.match(source, /onRunCapabilityPreflight/);
  assert.match(source, /capabilityOverrides/);
  assert.match(source, /capabilityPreflightResults/);
  assert.match(source, /setCapabilityOverrides/);
  assert.match(source, /setCapabilityPreflightResults/);
  assert.match(source, /runCapabilityPreflight/);
  assert.match(source, /buildMerchantConsoleCarrierCapabilityPreflight\(readiness, selectedCountryCode, selectedCarrierCode\)/);
  assert.match(source, /\[selectedCarrierCode, selectedCountryCode\]/);
  assert.match(source, /capabilityPreflightResult\.carrierCapabilityRef/);
  assert.match(source, /const guidedShipmentStep = buildMerchantConsoleGuidedShipmentStep\(readiness, capabilityPreflightResult\)/);
  assert.match(source, /guidedShipmentStep\.currentStep/);
  assert.match(source, /guidedShipmentStep\.primaryAction/);
  assert.match(source, /guidedShipmentStep\.helperText/);
  assert.match(source, /guidedShipmentStep\.canRunCapabilityPreflight/);
  assert.match(source, /guidedShipmentStep\.canCreateShipment/);
  assert.match(source, /carrierCapabilityRef: capabilityOverrides\[blockedOrderRef\]/);
  assert.match(source, /type MerchantConsoleLocalHexashipShipmentRecord/);
  assert.match(source, /upsertMerchantConsoleLocalHexashipShipmentRecord/);
  assert.match(source, /localHexashipShipments/);
  assert.match(source, /localHexashipWebhookRows/);
  assert.match(source, /localHexashipIdempotencyLedgerRows/);
  assert.match(source, /buildMerchantConsoleLocalHexashipIdempotencyLedgerRows\(localHexashipShipments\)/);
  assert.match(source, /localHexashipLedgerLayoutAudit/);
  assert.match(source, /buildMerchantConsoleLocalHexashipLedgerLayoutAudit\(localHexashipIdempotencyLedgerRows\)/);
  assert.match(source, /localHexashipLedgerLayoutAudit\.usesCompactSummaryGrid/);
  assert.match(source, /localHexashipLedgerLayoutAudit\.maxSummaryColumns/);
  assert.match(source, /localHexashipLedgerLayoutAudit\.requiresWrappedRefs/);
  assert.match(source, /copiedLedgerWebhookRef/);
  assert.match(source, /copyLedgerWebhookRef/);
  assert.match(source, /navigator\.clipboard\?\.writeText\(eventRef\)/);
  assert.match(source, /row\.latestWebhookEventRef/);
  assert.match(source, /row\.webhookReplayStatus/);
  assert.match(source, /row\.safeWebhookReplayRef/);
  assert.match(source, /const webhookReplayFixture = buildMerchantConsoleLocalHexashipWebhookReplayFixture\(row\)/);
  assert.match(source, /webhookReplayFixture\.acceptedReplayKind/);
  assert.match(source, /webhookReplayFixture\.conflictReplayKind/);
  assert.match(source, /webhookReplayFixture\.safeBodyFingerprintRef/);
  assert.match(source, /<ReplayKindBadge kind=\{webhookReplayFixture\.acceptedReplayKind\}/);
  assert.match(source, /<ReplayKindBadge kind=\{webhookReplayFixture\.conflictReplayKind\}/);
  assert.match(source, /\['idempotency', row\.idempotencyKey\]/);
  assert.match(source, /\['webhook replay', row\.webhookReplayStatus\]/);
  assert.match(source, /Object\.values\(createdShipments\)/);
  assert.match(source, /record\.result\.webhookLedger\.map/);
  assert.match(source, /const requestFixture = buildMerchantConsoleLocalHexashipRequestFixture\(record\)/);
  assert.match(source, /const replayPreview = buildMerchantConsoleLocalHexashipReplayPreview\(record, requestFixture\)/);
  assert.match(source, /copyRequestFixture/);
  assert.match(source, /navigator\.clipboard\?\.writeText\(buildMerchantConsoleLocalHexashipRequestFixtureCopyText\(fixture\)\)/);
  assert.match(source, /merchantConsolePlan\.sampleShipmentHistory\.map/);
  assert.match(source, /readinessInputFromShipment/);
  assert.match(source, /addressFormVersion: `wallet_country_form_ref_/);
  assert.match(source, /function ShipmentCreateActionButton/);
  assert.match(source, /disabled=\{!readiness\.canCreateShipment\}/);
  assert.match(source, /aria-disabled=\{!readiness\.canCreateShipment\}/);
  assert.match(source, /onClick=\{\(\) => onCreateShipment\(readiness\)\}/);
  assert.match(source, /<ShipmentCreateActionButton readiness=\{readiness\} onCreateShipment=\{createShipment\}/);
  assert.match(source, /upsertMerchantConsoleLocalHexashipShipmentRecord\(current\[readiness\.orderRef\], readiness\.orderRef, result\)/);
  assert.match(source, /shipmentCreationReadiness\.map/);
  assert.match(source, /readiness\.disabledActions/);
  assert.match(source, /readiness\.missingRefs/);
  assert.match(source, /runSandboxCarrierGatewaySmoke/);
  assert.match(source, /buildAddressWalletCarrierCoverageMatrix/);
  assert.match(source, /buildAddressWalletCarrierLabelTransform/);
  assert.match(source, /buildAddressWalletCarrierPreflightPreview/);
  assert.match(source, /carrierCoverageMatrix/);
  assert.match(source, /activeCarrierPreflightPreview/);
  assert.match(source, /activeCarrierLabelTransform/);
  assert.match(source, /userEntryPolicy\.doNotAskForCarrierSpecificShape/);
  assert.match(source, /rawAddressExposedToMerchant/);
  assert.match(source, /setSelectedCarrierCode/);
  assert.match(source, /setSelectedCountryCode/);
  assert.match(source, /onChange=\{event => onCarrierChange/);
  assert.match(source, /onChange=\{event => onCountryChange/);
  assert.match(source, /<CarrierCountryPreflightSelector/);
  assert.match(source, /onCarrierChange=\{setSelectedCarrierCode\}/);
  assert.match(source, /onCountryChange=\{setSelectedCountryCode\}/);
  assert.match(source, /activeNextAction=\{activeCarrierPreflightPreview\.activeNextAction\}/);
  assert.match(source, /activeSelectionAction=\{activeCarrierPreflightPreview\.activeSelectionAction\}/);
  assert.match(source, /activeMissingRefs=\{activeCarrierPreflightPreview\.activeMissingRefs\}/);
  assert.match(source, /carrierCoverageMatrix\.carrierSummaries\.map\(summary => \(/);
  assert.match(source, /carrierCoverageMatrix\.countryCodes\.map\(countryCode => \(/);
  assert.match(source, /carrierPreflightPreviews/);
  assert.match(source, /includeCarrierCapabilityRef: selectedCarrierCode === 'dhl'/);
  assert.match(source, /buildAddressWalletCarrierPreflightPreview\(\{ carrier: 'ups', countryCode: 'US' \}\)/);
  assert.match(source, /carrierCoverageMatrix\.countryCodes\.map/);
  assert.match(source, /carrierCoverageMatrix\.continentCoverage/);
  assert.match(source, /carrierCoverageMatrix\.carrierSummaries\.map/);
  assert.match(source, /summary\.serverSideRuntimeChecksRequired/);
  assert.match(source, /preflight\.requiredNextAction/);
  assert.match(source, /selection\?\.requiredNextAction/);
  assert.match(source, /preflight\.missingRefs/);
  assert.match(source, /activeCarrierPreflightPreview\.activeNextAction/);
  assert.match(source, /activeCarrierPreflightPreview\.activeSelectionAction/);
  assert.match(source, /selection\?\.form\.carriers\[preflight\.carrier\]\.capabilityMode/);
  assert.match(source, /buildSkipshipMerchantConsoleWebhookLedger/);
  assert.match(source, /veyEcosystem\.buildUnits\.find/);
  assert.match(source, /veyEcosystem\.apiSurfaces/);
  assert.match(source, /commerce-and-delivery/);
  assert.match(source, /carrier-routing-api/);
  assert.match(source, /merchant-operator-console/);
  assert.match(source, /sandboxCarrierSmoke\.steps\.map/);
  assert.match(source, /sandboxCarrierSmoke\.merchantVisible/);
  assert.match(source, /sandboxCarrierSmoke\.blockedMaterial/);
  assert.match(source, /integration\.setupPreflight\.checks/);
  assert.match(source, /integration\.setupPreflight\.testVectorCommand/);
  assert.match(source, /integration\.requiredDashboardGates/);
  assert.match(source, /integration\.webhookEvents/);
  assert.match(source, /skipshipWebhookLedger\.rows\.map/);
  assert.match(source, /skipshipWebhookLedger\.totals\.retrying/);
  assert.match(source, /skipshipWebhookLedger\.privacyBoundary/);
  assert.match(source, /skipshipWebhookLedger\.source\.mode/);
  assert.match(source, /skipshipWebhookLedger\.source\.localOnly/);
  assert.match(source, /skipshipWebhookLedger\.source\.productionTraffic/);
  assert.match(source, /PLAYLIST_COMMERCE_WEBHOOK_ROUTES/);
  assert.match(source, /PLAYLIST_COMMERCE_WEBHOOK_SYNTHETIC_PING_PREFLIGHT/);
  assert.match(source, /playlistCommerceWebhookEvidenceFixture/);
  assert.match(source, /playlistCommerceWebhookPreflightFixture/);
  assert.match(source, /playlistCommerceWebhookPreflightHistoryFixture/);
  assert.match(source, /playlistCommerceWebhookPreflight\.passed/);
  assert.match(source, /playlistCommerceWebhookPreflight\.responseSummary\.acceptedStatus/);
  assert.match(source, /playlistCommerceWebhookPreflight\.responseSummary\.replayStatus/);
  assert.match(source, /playlistCommerceWebhookPreflight\.checks\.map/);
  assert.match(source, /playlistCommerceWebhookPreflightHistory\.summary\.totalRuns/);
  assert.match(source, /playlistCommerceWebhookPreflightHistory\.summary\.passedRuns/);
  assert.match(source, /playlistCommerceWebhookPreflightHistory\.summary\.replayBlockedRuns/);
  assert.match(source, /playlistCommerceWebhookPreflightHistory\.summary\.latestEvidenceRef/);
  assert.match(source, /playlistCommerceWebhookPreflightHistory\.operatorAction\.exportCommand/);
  assert.match(source, /playlistCommerceWebhookPreflightHistory\.operatorAction\.checkCommand/);
  assert.match(source, /playlistCommerceWebhookPreflightHistory\.operatorAction\.nextSafeStep/);
  assert.match(source, /playlistCommerceWebhookPreflightHistory\.runs\.map/);
  assert.match(source, /run\.evidenceRef/);
  assert.match(source, /latestPlaylistCommerceEvidence/);
  assert.match(source, /playlistCommerceWebhookEvidence\.records\.find/);
  assert.match(source, /latestPlaylistCommerceEvidence\?\.vaultRecordRef/);
  assert.match(source, /latestPlaylistCommerceEvidence\?\.commitments\.requestCommitmentRef/);
  assert.match(source, /latestPlaylistCommerceEvidence\?\.commitments\.responseCommitmentRef/);
  assert.match(source, /latestPlaylistCommerceEvidence\?\.commitments\.checkCommitmentRef/);
  assert.match(source, /playlistCommerceWebhookEvidence\.summary\.allRecordsRedacted/);
  assert.match(source, /playlistCommerceWebhookEvidence\.source\.managedServiceBoundary/);
  assert.match(source, /playlistCommerceWebhookRoute\.acceptedTopics/);
  assert.match(source, /playlistCommerceWebhookRoute\.requiredControls/);
  assert.match(source, /playlistCommerceSyntheticPing\.safeCommand/);
  assert.match(source, /responseSummary/);
  assert.match(source, /blockedMaterial/);
  assert.match(source, /webhookHmacValidator\.cases/);
  assert.match(source, /webhookHmacValidator\.negativeCaseId/);
  assert.match(source, /function WebhookHmacSection/);
  assert.match(source, /<WebhookHmacSection key="webhook-hmac" webhookHmacValidator=\{integration\.webhookHmacValidator\} \/>/);
  assert.match(source, /webhookKeyRotation\.phases/);
  assert.match(source, /webhookKeyRotation\.evidenceVectorIds/);
  assert.match(source, /webhookKeyRotation\.overlapSeconds/);
  assert.match(source, /function KeyRotationSection/);
  assert.match(source, /<KeyRotationSection key="key-rotation" webhookKeyRotation=\{webhookKeyRotation\} \/>/);
  assert.match(source, /merchantVisibleRedactionDisplayContract/);
  assert.match(source, /contract\.blockedClassCount/);
  assert.match(source, /contract\.nonClaimCount/);
  assert.match(source, /renderedMaterialPolicy\.showCountsOnly/);
  assert.match(source, /copyPayload\.clipboardText/);
  assert.match(source, /copiedHostedRedactionContract/);
  assert.match(source, /copyHostedRedactionContract/);
  assert.match(source, /copyHostedAddressLoginMerchantVisibleRedactionClipboardPayload\(/);
  assert.match(source, /text => navigator\.clipboard\?\.writeText\(text\)/);
  assert.match(source, /integration\.callbackContract\.canonicalParams/);
  assert.match(source, /integration\.safeCallbackPreview/);
});

test('Merchant Console keeps merchant-visible material redacted', () => {
  assert.match(source, /Merchant callbacks contain refs and claims only/);
  assert.match(source, /Carrier handoff is scoped and time-bound/);
  assert.match(source, /Logs use fingerprints and event refs/);
  assert.match(source, /Support review sees reason codes, not evidence bodies/);
  assert.match(source, /no raw address console/);
  assert.match(source, /webhookHmacValidator\.nonClaims/);
  assert.match(source, /webhookKeyRotation\.errors\.length/);
  assert.match(source, /payloadFingerprint/);
  assert.match(source, /signingKeyRef/);
  assert.match(source, /playlistCommerceWebhookRoute\.redactedFields/);
  assert.match(source, /playlistCommerceWebhookRoute\.nonClaims/);
  assert.match(source, /Never returned/);
  assert.match(source, /playlistCommerceSyntheticPing\.localOnly/);
  assert.match(source, /row\.safeRefs\.eventRef/);
  assert.match(source, /rows\[0\]\?\.blockedMaterial/);
  assert.match(source, /function MerchantConsoleMainColumn/);
  assert.match(source, /<MerchantConsoleMainColumn key="merchant-console-main-column">/);
  assert.match(source, /function MerchantConsoleRightRail/);
  assert.match(source, /<MerchantConsoleRightRail key="merchant-console-right-rail" integration=\{integration\} \/>/);
  assert.doesNotMatch(source, /rawTrackingPayloadValue|recipient_phone_value|carrier_secret_value|proof_witness_value/);
});

test('Merchant Console hosted redaction reader mirrors shared helper refs and counts', () => {
  const hostedContract = loadHostedAddressLoginMerchantVisibleRedactionDisplayContract();
  const adapter = createVeyIdCoreMerchantVisibleRedactionAdapterFixture();
  const expectedRefs = displayRefsFromMerchantVisibleRedactionContract(hostedContract);
  const { html, renderWarnings } = renderMerchantConsoleWithWarnings();
  const redactionHtml = extractHostedRedactionHtml(html);

  assertNoMerchantConsoleWarnings(renderWarnings);
  assert.equal(expectedRefs.length, hostedContract.displayFields.length);
  assert.equal(hostedContract.blockedClassCount, adapter.boundaryGate.requiredBlockedMaterial.length);
  assert.equal(hostedContract.nonClaimCount, adapter.boundaryGate.nonClaims.length);
  assert.equal(hostedContract.renderedMaterialPolicy.showCountsOnly, true);
  assert.equal(hostedContract.renderedMaterialPolicy.copyBlockedMaterialNames, false);
  assert.equal(hostedContract.renderedMaterialPolicy.copyNonClaimText, false);
  assert.match(redactionHtml, new RegExp(`visibleRefs: ${expectedRefs.length}`));
  assert.match(redactionHtml, new RegExp(`blockedClasses: ${adapter.boundaryGate.requiredBlockedMaterial.length}`));
  assert.match(redactionHtml, new RegExp(`nonClaims: ${adapter.boundaryGate.nonClaims.length}`));

  for (const ref of expectedRefs) {
    assert.ok(redactionHtml.includes(ref), `expected hosted redaction card to render ${ref}`);
  }
  for (const material of adapter.boundaryGate.requiredBlockedMaterial) {
    assert.ok(!redactionHtml.includes(material), `hosted redaction card must not render blocked material name ${material}`);
  }
  for (const nonClaim of adapter.boundaryGate.nonClaims) {
    assert.ok(!redactionHtml.includes(nonClaim), `hosted redaction card must not render non-claim text ${nonClaim}`);
  }
});

test('Merchant Console server render includes OpenAPI contract copy controls without private material', () => {
  const { html, renderWarnings } = renderMerchantConsoleWithWarnings();

  assert.match(html, /Merchant onboarding OpenAPI contract/);
  assert.match(html, /Callback preflight repair actions/);
  assert.match(html, /run_synthetic_test_vectors/);
  assert.match(html, /Negative fixture export/);
  assert.match(html, /merchant-console-callback-preflight-negative-v0\.1/);
  assert.match(html, /missing_address_login_boundary/);
  assert.match(html, /storeEcPlatform\.addressLoginCallbackPreflight/);
  assert.match(html, /replace_with_https_callback_url/);
  assert.match(html, /remove_forbidden_callback_params/);
  assert.match(html, /raw_address/);
  assert.match(html, /private_key/);
  assert.match(html, /proof_secret/);
  assert.match(html, /credential_ref/);
  assert.match(html, /callback_forbidden_value_negative/);
  assert.match(html, /npm run verify:merchant-console-ec-plugin/);
  assert.match(html, /Copy contract/);
  assert.match(html, /\/v1\/merchant-console\/onboarding/);
  assert.match(html, /docs\/specs\/fixtures\/merchant-console-onboarding-v0\.1\.json/);
  assert.match(html, /enabled carriers/);
  assert.match(html, /dhl \+ ups/);
  assert.match(html, /Vey ID client/);
  assert.match(html, /address_login_client_ref_synthetic_001/);
  assert.match(html, /Callback preflight/);
  assert.match(html, /address_login_callback_preflight_ref_[0-9a-f]{24}/);
  assert.match(html, /Callback contract/);
  assert.match(html, /veygrit-address-login-callback-v0\.1/);
  assert.match(html, /Callback preflight passed/);
  assert.match(html, /address form/);
  assert.match(html, /wallet_country_form_ref_us_en_v1/);
  assert.match(html, /productionTraffic: false/);
  assert.match(html, /rawAddressVisibleToEc: false/);
  assert.match(html, /Vey ID Core adoption check/);
  assert.match(html, /Google\/Apple account creation/);
  assert.match(html, /PKCE server exchange/);
  assert.match(html, /Wallet-side revocation/);
  assert.match(html, /@veygrit\/address-login-react/);
  assert.match(html, /@veygrit\/address-login-nextjs/);
  assert.match(html, /npm run verify:veygrit-id-core-openapi/);
  assert.match(html, /npm run verify:veygrit-address-login-react/);
  assert.match(html, /npm run verify:veygrit-address-login-nextjs/);
  assert.match(html, /authorizationCodeRef/);
  assert.match(html, /pairwiseSubjectAlias/);
  assert.match(html, /addressCredentialRef/);
  assert.match(html, /pkceVerifierRef/);
  assert.match(html, /revocationRef/);
  assert.match(html, /providerIdToken/);
  assert.match(html, /providerAccessToken/);
  assert.match(html, /rawProviderProfile/);
  assert.match(html, /Hosted \/test-vectors redaction/);
  assert.match(html, /Merchant-visible display contract/);
  assert.match(html, /guest_checkout_alias_synthetic_hosted_001/);
  assert.match(html, /carrier_blob_ref_synthetic_shipping_001/);

  const redactionHtml = extractHostedRedactionHtml(html);
  assert.match(redactionHtml, /visible refs/);
  assert.match(redactionHtml, /blocked classes/);
  assert.match(redactionHtml, /non-claims/);
  assert.match(redactionHtml, /counts-only/);
  assert.match(redactionHtml, /Hosted redaction safe refs/);
  assert.match(redactionHtml, /Copy safe refs/);
  assert.match(redactionHtml, /visibleRefs: 5/);
  assert.match(redactionHtml, /blockedClasses: 7/);
  assert.match(redactionHtml, /nonClaims: 1/);
  assert.match(redactionHtml, /guestCheckoutAlias: guest_checkout_alias_synthetic_hosted_001/);
  assert.match(redactionHtml, /carrierHandoffRef: carrier_blob_ref_synthetic_shipping_001/);
  assert.match(redactionHtml, /localOnly: true/);
  assert.match(redactionHtml, /productionTraffic: false/);
  assert.doesNotMatch(redactionHtml, /copyBlockedMaterialNames|copyNonClaimText|sourceFixture|sdkHelper/);

  const carrierCoverageHtml = extractCarrierCoverageMatrixHtml(html);
  assert.match(carrierCoverageHtml, /Address Wallet carrier coverage matrix/);
  assert.match(carrierCoverageHtml, /DHL\/UPS country forms before runtime capability checks/);
  assert.match(carrierCoverageHtml, /countries:/);
  assert.match(carrierCoverageHtml, /productionTraffic: false/);
  assert.match(carrierCoverageHtml, /MVP country forms/);
  assert.match(carrierCoverageHtml, /Carrier runtime boundary/);
  assert.match(carrierCoverageHtml, /Carrier form preflight next actions/);
  assert.match(carrierCoverageHtml, /serverSideRuntimeChecksRequired: true/);
  assert.doesNotMatch(carrierCoverageHtml, /Skipship webhook ledger/);
  assert.doesNotMatch(carrierCoverageHtml, /rawAddressValue|recipientPhoneValue|carrierApiKeyValue|proofSecretValue|privateKeyValue|webhookSecretValue/);

  assert.doesNotMatch(html, /rawAddressValue|recipientPhoneValue|carrierApiKeyValue|proofSecretValue|privateKeyValue|webhookSecretValue/);
  assertNoMerchantConsoleWarnings(renderWarnings);
});

test('Merchant Console is routed as a standalone commercial Address Login surface', () => {
  assert.match(rootSource, /MerchantConsoleScreen/);
  assert.match(rootSource, /isMerchantConsoleRoute/);
  assert.match(rootSource, /window\.location\.pathname === '\/merchant-console'/);
  assert.match(rootSource, /route\.merchantConsole/);
  assert.match(navigationSource, /id: 'merchant-console'/);
  assert.match(navigationSource, /route: '\/merchant-console'/);
  assert.match(navigationSource, /licenseProfile: 'commercial-private'/);
});
