import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import assert from 'node:assert';
import test from 'node:test';

test('POS terminal uses the shared AGID app language setting', () => {
  const screenSource = readFileSync(join(process.cwd(), 'src', 'components', 'PosAppScreen.tsx'), 'utf8');
  const panelSource = readFileSync(join(process.cwd(), 'src', 'components', 'PosTerminalPanel.tsx'), 'utf8');
  const sectionsSource = readFileSync(join(process.cwd(), 'src', 'components', 'pos', 'PosTerminalSections.tsx'), 'utf8');

  assert.match(screenSource, /APP_LANGUAGE_STORAGE_KEY/);
  assert.match(screenSource, /APP_LANGUAGES/);
  assert.match(screenSource, /normalizeAppLanguage/);
  assert.match(screenSource, /document\.documentElement\.lang/);
  assert.match(screenSource, /getLanguageDirection/);
  assert.doesNotMatch(screenSource, /languageSelectAria/);
  assert.doesNotMatch(screenSource, /languageLabel/);
  assert.doesNotMatch(screenSource, /APP_LANGUAGES\.map/);
  assert.doesNotMatch(screenSource, /<select/);
  assert.match(panelSource, /onAppLanguageChange/);
  assert.match(panelSource, /posPanelCopy/);
  assert.match(panelSource, /posPanelInlineCopy/);
  assert.match(panelSource, /posScannerMessage/);
  assert.match(panelSource, /settingsWorkspace/);
  assert.match(panelSource, /primaryFlow/);
  assert.match(panelSource, /operations/);
  assert.match(panelSource, /primaryLabel=\{panelT\('primaryFlow'\)\}/);
  assert.match(panelSource, /supportLabel=\{panelT\('operations'\)\}/);
  assert.match(panelSource, /grid-cols-\[200px_minmax\(0,1fr\)_390px\]/);
  assert.match(panelSource, /grid-cols-\[240px_minmax\(0,1fr\)_410px\]/);
  assert.match(panelSource, /PosTerminalCommandCenter/);
  assert.match(panelSource, /terminalCommand/);
  assert.match(panelSource, /readDestinationQr/);
  assert.match(panelSource, /safeEnvelope/);
  assert.match(panelSource, /queueTotal/);
  assert.match(panelSource, /workspaceAdmin/);
  assert.match(panelSource, /workspaceDecision/);
  assert.match(panelSource, /workspaceHandoff/);
  assert.match(panelSource, /PosHandoffBoardPanel/);
  assert.match(panelSource, /activeWorkspace[\s\S]*scan/);
  assert.match(panelSource, /primary: true, step: 1/);
  assert.match(panelSource, /primary: true, step: 4/);
  assert.match(sectionsSource, /POS_FIXED_PRIMARY_FLOW: PosWorkspaceId\[\] = \['scan', 'decision', 'handoff', 'report'\]/);
  assert.match(sectionsSource, /POS_FIXED_PRIMARY_FLOW[\s\S]*items\.find\(item => item\.id === id\)/);
  assert.match(sectionsSource, /supportItems = items\.filter\(item => !POS_FIXED_PRIMARY_FLOW\.includes\(item\.id\)\)/);
  assert.match(sectionsSource, /aria-label="Scan -> Decision -> Handoff -> Receipt"/);
  assert.match(sectionsSource, /Primary flow/);
  assert.match(sectionsSource, /Operations/);
  assert.match(sectionsSource, /Reject \/ review reasons/);
  assert.match(sectionsSource, /拒否・要確認理由/);
  assert.match(sectionsSource, /carrier-policy-rejects-address-defect/);
  assert.match(sectionsSource, /carrier-policy-rejects-undeliverable-region/);
  assert.match(sectionsSource, /carrier-policy-requires-aoid-access-profile/);
  assert.match(sectionsSource, /redacted codes only/);
  assert.match(sectionsSource, /buildPosDecisionReasonItems/);
  assert.match(sectionsSource, /PosDecisionReasonPanel/);
  assert.match(panelSource, /posStaffRoleDetail/);
  assert.match(panelSource, /posRegistryDetail/);
  assert.match(sectionsSource, /POS_SETTINGS_COPY/);
  assert.match(sectionsSource, /POS_MAIN_COPY/);
  assert.match(sectionsSource, /posInlineCopy/);
  assert.match(sectionsSource, /language\?: string/);
  assert.match(sectionsSource, /statusLabel\(currentStatus, preview, language\)/);
  assert.match(sectionsSource, /管理状態は正常/);
  assert.match(sectionsSource, /受付待機/);
  assert.match(sectionsSource, /端末を操作/);
  assert.match(sectionsSource, /信頼状態/);
  assert.match(sectionsSource, /判定ワークベンチ/);
  assert.match(sectionsSource, /引き渡しボード/);
  assert.match(sectionsSource, /Carrier and recipient evidence before release/);
  assert.match(sectionsSource, /posManagementMetricLabel/);
  assert.match(sectionsSource, /APP_LANGUAGES\.map/);
  assert.match(sectionsSource, /value=\{appLanguage\}/);
  assert.match(sectionsSource, /onChange=\{\(event\) => onAppLanguageChange\(event\.target\.value\)\}/);
  assert.match(sectionsSource, /getLanguageDirection\(appLanguage\)/);
  assert.match(sectionsSource, /表示言語/);
  assert.match(sectionsSource, /Display language/);
  assert.match(sectionsSource, /Production settings to confirm/);
  assert.match(sectionsSource, /例外監査/);
  assert.match(sectionsSource, /引き渡し後の再照合/);
  assert.match(sectionsSource, /オフラインキュー/);
  assert.match(sectionsSource, /送り状QR/);
  assert.match(sectionsSource, /AGID-S鍵/);
  assert.match(sectionsSource, /最新レシート/);
  assert.match(sectionsSource, /ローカルプレビュー/);
  assert.match(sectionsSource, /レシートログ/);
  assert.match(sectionsSource, /POS端末管理/);
  assert.match(sectionsSource, /権限マトリクス/);
  assert.match(sectionsSource, /診断コマンド/);
  assert.match(panelSource, /buildAddressTerminalFleetSnapshot/);
  assert.match(panelSource, /terminalFleetSnapshot/);
  assert.match(panelSource, /onPrinterTest/);
  assert.match(panelSource, /PosReaderShell[\s\S]*language=\{appLanguage\}/);
  assert.match(panelSource, /SecureAgidKeyPanel[\s\S]*language=\{appLanguage\}/);
  assert.match(panelSource, /LatestReceiptPanel[\s\S]*language=\{appLanguage\}/);
  assert.match(panelSource, /professionalCollaboration/);
  assert.match(panelSource, /職種別連携/);
  assert.match(panelSource, /buildPosProfessionReviews/);
  assert.match(panelSource, /cashierReview/);
  assert.match(panelSource, /handoffReview/);
  assert.match(panelSource, /supervisorReview/);
  assert.match(panelSource, /technicalOpsReview/);
  assert.match(panelSource, /securityReview/);
  assert.match(panelSource, /focusProfessionReview/);
  assert.match(panelSource, /setActiveWorkspace\(review\.workspace\)/);
  assert.doesNotMatch(panelSource, /rawAddress\s*:/);
});
