import assert from 'node:assert/strict';import {test,type TestContext} from 'node:test';
import {mkdtempSync,readFileSync,rmSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {buildMalaysiaObservationPack,materializeMalaysiaObservationPack} from './postal-context-my-pack';
import {sourceDigest} from './postal-context-source-probe.mjs';import {loadPostalContextPack} from '../../src/server/postalContextPackStore';
const csv=Buffer.from('state,city,postcode\nSynthetic State,Synthetic City,01234\nSynthetic State ,Synthetic City,01234\nSynthetic State,Other City,01234\nSynthetic State,Another City,01235\n');
const at='2026-08-28T00:00:00.000Z',receipt={observedAt:at,edition:'2026-06',synthetic:true,csvDigest:sourceDigest(csv),catalogDigest:sourceDigest('synthetic catalog'),termsDigest:sourceDigest('synthetic terms')};
function fixture(t:TestContext){const dir=mkdtempSync(join(tmpdir(),'agid-my-test-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const built=buildMalaysiaObservationPack(csv,receipt),out=join(dir,'pack');return {built,out,loaded:materializeMalaysiaObservationPack(out,built)};}
test('MY experiment is deterministic, opt-in, nonpromotable and geometryless',t=>{const {built,out}=fixture(t),again=buildMalaysiaObservationPack(csv,receipt);assert.equal(built.descriptorDigest,again.descriptorDigest);for(const [p,b]of built.files)assert.equal(b.compare(again.files.get(p)!),0);assert.equal(built.descriptor.promotionEligible,false);assert.ok(built.graph.nodes.every(n=>n.geometryType==='none'&&!['building','address_point','agid_cell'].includes(n.kind)));assert.throws(()=>loadPostalContextPack(join(out,'descriptor.json'),built.descriptorDigest,{expectedCountryCode:'MY'}));});
test('MY exact tuples coalesce while distinct locality contexts stay ambiguous',t=>{const {loaded}=fixture(t);const a=loaded.runtime.lookupPostalCode('01234',at,at,true),b=loaded.runtime.lookupPostalCode('01235',at,at,true);assert.equal(a.status,'ambiguous');assert.equal(a.alternatives.length,2);assert.equal(b.status,'unique');assert.ok(b.contexts.some(c=>c.label==='Another City'));assert.deepEqual(a.geometries,[]);assert.deepEqual(b.geometries,[]);});
test('MY observation date is not an invented live validity range',t=>{const {loaded}=fixture(t);assert.equal(loaded.runtime.lookupPostalCode('01235',new Date(Date.parse(at)+1).toISOString()).status,'no_match');assert.equal(loaded.runtime.lookupPostalCode('01235',at,new Date(Date.parse(at)-1).toISOString()).status,'no_match');assert.equal(loaded.runtime.resolvePublicCoordinate({latitude:3,longitude:101,purpose:'display',validAt:at}).resolvedLevel,'none');});
test('MY receipt and untouched output guards fail closed',t=>{const {built,out}=fixture(t);assert.throws(()=>materializeMalaysiaObservationPack(out,built),/EEXIST/);assert.throws(()=>buildMalaysiaObservationPack(csv,{...receipt,csvDigest:sourceDigest('other')}),/csv-digest/);assert.throws(()=>buildMalaysiaObservationPack(csv,{...receipt,observedAt:'bad'}),/time/);assert.throws(()=>buildMalaysiaObservationPack(csv,{...receipt,edition:'2027-06'}),/edition/);assert.throws(()=>buildMalaysiaObservationPack(csv,{...receipt,synthetic:false}),/unreviewed-source/);});
test('MY real loader detects tampering',t=>{const {built,out}=fixture(t),path=join(out,'graph.json'),s=readFileSync(path,'utf8');writeFileSync(path,s.replace('Another City','Altered City'));assert.throws(()=>loadPostalContextPack(join(out,'descriptor.json'),built.descriptorDigest,{expectedCountryCode:'MY',allowExperimental:true,allowSynthetic:true}),/digest-mismatch/);});
