import AMTPaperExtensions

/-!
Generated GIS validation certificate for AMT.

Source report:
  test-results/gis-validation/gis-warning-budget-report.json

This file is generated by scripts/export-gis-lean-certificate.ts.  Lean checks
the exported counts and budget implications; GIS software remains responsible
for the empirical geometry and source-registry checks.
-/

namespace AMT.GeneratedGisCertificate

def currentGisFeatureCount : Nat := 351
def currentGisErrorCount : Nat := 0
def currentGisWarningCount : Nat := 149
def currentGisMaxErrors : Nat := 0
def currentGisMaxWarnings : Nat := 149
def currentGisRegisteredSourceCount : Nat := 408
def currentGisMinFeatureCount : Nat := 351
def currentGisMinRegisteredSourceCount : Nat := 408

def currentGisCertificate : AMT.GisValidationCertificate := {
  featureCount := currentGisFeatureCount,
  errorCount := currentGisErrorCount,
  warningCount := currentGisWarningCount,
  maxErrors := currentGisMaxErrors,
  maxWarnings := currentGisMaxWarnings,
  registeredSourceCount := currentGisRegisteredSourceCount,
  minFeatureCount := currentGisMinFeatureCount,
  minRegisteredSourceCount := currentGisMinRegisteredSourceCount,
  geometryChecked := True,
  sourceRegistryChecked := True,
}

theorem current_gis_certificate_accepted :
    AMT.GisCertificateAccepted currentGisCertificate := {
  geometryChecked := True.intro,
  sourceRegistryChecked := True.intro,
  errorWithinBudget := by native_decide,
  warningWithinBudget := by native_decide,
  zeroErrorBudget := by native_decide,
  enoughFeatures := by native_decide,
  enoughSources := by native_decide,
}

theorem current_gis_certificate_has_no_errors :
    currentGisCertificate.errorCount = 0 :=
  AMT.accepted_gis_certificate_has_no_errors current_gis_certificate_accepted

theorem current_gis_feature_floor_met :
    currentGisMinFeatureCount <= currentGisFeatureCount := by
  native_decide

theorem current_gis_source_floor_met :
    currentGisMinRegisteredSourceCount <= currentGisRegisteredSourceCount := by
  native_decide

theorem current_gis_warning_budget_met :
    currentGisWarningCount <= currentGisMaxWarnings := by
  native_decide

end AMT.GeneratedGisCertificate
