import { mkdirSync,readFileSync,writeFileSync } from 'node:fs';
import { dirname,join } from 'node:path';

type GisWarningBudgetReport = {
  generatedAt: string;
  pass: boolean;
  summary: {
    features: number;
    errors: number;
    warnings: number;
  };
  registeredSources: number;
  budget: {
    maxErrors: number;
    maxWarnings: number;
    minFeatures: number;
    minRegisteredSources: number;
  };
  errors: string[];
};

const ROOT = process.cwd();
const reportPath = join(ROOT, 'test-results', 'gis-validation', 'gis-warning-budget-report.json');
const outputPath = join(ROOT, 'formal', 'GeneratedGisCertificate.lean');

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, 'utf8')) as T;
}

function assertNaturalNumber(name: string, value: number) {
  if (!Number.isInteger(value) || value < 0) {
    throw new Error(`${name} must be a non-negative integer, got ${value}`);
  }
}

function leanNat(value: number): string {
  assertNaturalNumber('Lean Nat value', value);
  return String(value);
}

function main() {
  const report = readJson<GisWarningBudgetReport>(reportPath);

  if (!report.pass || report.errors.length > 0) {
    throw new Error('GIS warning budget report did not pass; refusing to export a Lean certificate.');
  }

  const values = {
    featureCount: report.summary.features,
    errorCount: report.summary.errors,
    warningCount: report.summary.warnings,
    maxErrors: report.budget.maxErrors,
    maxWarnings: report.budget.maxWarnings,
    registeredSourceCount: report.registeredSources,
    minFeatureCount: report.budget.minFeatures,
    minRegisteredSourceCount: report.budget.minRegisteredSources,
  };

  Object.entries(values).forEach(([name, value]) => assertNaturalNumber(name, value));

  const content = `import AMTPaperExtensions

/-!
Generated GIS validation certificate for AMT.

Source report:
  test-results/gis-validation/gis-warning-budget-report.json

This file is generated by scripts/export-gis-lean-certificate.ts.  Lean checks
the exported counts and budget implications; GIS software remains responsible
for the empirical geometry and source-registry checks.
-/

namespace AMT.GeneratedGisCertificate

def currentGisFeatureCount : Nat := ${leanNat(values.featureCount)}
def currentGisErrorCount : Nat := ${leanNat(values.errorCount)}
def currentGisWarningCount : Nat := ${leanNat(values.warningCount)}
def currentGisMaxErrors : Nat := ${leanNat(values.maxErrors)}
def currentGisMaxWarnings : Nat := ${leanNat(values.maxWarnings)}
def currentGisRegisteredSourceCount : Nat := ${leanNat(values.registeredSourceCount)}
def currentGisMinFeatureCount : Nat := ${leanNat(values.minFeatureCount)}
def currentGisMinRegisteredSourceCount : Nat := ${leanNat(values.minRegisteredSourceCount)}

def currentGisCertificate : AMT.GisValidationCertificate := {
  featureCount := currentGisFeatureCount,
  errorCount := currentGisErrorCount,
  warningCount := currentGisWarningCount,
  maxErrors := currentGisMaxErrors,
  maxWarnings := currentGisMaxWarnings,
  registeredSourceCount := currentGisRegisteredSourceCount,
  minFeatureCount := currentGisMinFeatureCount,
  minRegisteredSourceCount := currentGisMinRegisteredSourceCount,
  geometryChecked := True,
  sourceRegistryChecked := True,
}

theorem current_gis_certificate_accepted :
    AMT.GisCertificateAccepted currentGisCertificate := {
  geometryChecked := True.intro,
  sourceRegistryChecked := True.intro,
  errorWithinBudget := by native_decide,
  warningWithinBudget := by native_decide,
  zeroErrorBudget := by native_decide,
  enoughFeatures := by native_decide,
  enoughSources := by native_decide,
}

theorem current_gis_certificate_has_no_errors :
    currentGisCertificate.errorCount = 0 :=
  AMT.accepted_gis_certificate_has_no_errors current_gis_certificate_accepted

theorem current_gis_feature_floor_met :
    currentGisMinFeatureCount <= currentGisFeatureCount := by
  native_decide

theorem current_gis_source_floor_met :
    currentGisMinRegisteredSourceCount <= currentGisRegisteredSourceCount := by
  native_decide

theorem current_gis_warning_budget_met :
    currentGisWarningCount <= currentGisMaxWarnings := by
  native_decide

end AMT.GeneratedGisCertificate
`;

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content, 'utf8');
  console.log(`[GIS Lean] Wrote ${outputPath}`);
}

main();
