import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
const root=new URL('../',import.meta.url);const ledger=JSON.parse(readFileSync(new URL('docs/postal-context-m2-rollout.json',root),'utf8'));const by=ledger.countries.find(country=>country.countryCode==='BY');const ch=ledger.countries.find(country=>country.countryCode==='CH');const manifest=JSON.parse(readFileSync(new URL('data/postal_country_packs/by/postal-context/repository-manifest.json',root),'utf8'));const digest=path=>'sha256:'+createHash('sha256').update(readFileSync(new URL(path,root))).digest('hex');
test('BY stays blocked under its assignment, zone rights and app visualization criterion',()=>{assert.equal(by.status,'blocked');assert.equal(by.attempts,1);assert.equal(by.evidence,null);assert.equal(by.m2Definition.id,'M2_current_belpost_assignment_and_rights_cleared_nca_postal_zone_visualization');assert.equal(manifest.promotion.target_stage,by.m2Definition.id);});
test('live assignment rows and public map references do not become postal polygons',()=>{assert.equal(by.blocker.evidence.belpostObservedPostcode,'220030');assert.equal(by.blocker.evidence.belpostSearchTotal,89);assert.equal(by.blocker.evidence.belpostRowsWithGeometry,0);assert.equal(by.blocker.evidence.postalPolygonOrMultiPolygonRecords,0);assert.equal(by.blocker.evidence.publicMapViewerUsedAsReusableVectorArtifact,false);});
test('ledger pins both reports and Switzerland is next',()=>{assert.equal(digest('reports/postal-context-m2/by-source-review-2026-08-29.json'),by.lastAttempt.reportDigest);assert.equal(digest('reports/postal-context-m2/by-checks-2026-08-29.json'),by.lastAttempt.engineeringReportDigest);assert.equal(ch.status,'pending');assert.equal(ch.region,'europe');});
test('shared visualization capability cannot promote BY without real area geometry and rights',()=>{assert.equal(by.blocker.evidence.sharedAppAreaPathVerified,true);assert.equal(by.blocker.evidence.realBelarusAgidPostalApiVerified,false);assert.equal(by.blocker.evidence.realBelarusAgidAppAreaVisualizationVerified,false);assert.match(by.blocker.retryPolicy,/Do not authenticate.*accept.*pay/i);});
