import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
const root=new URL('../',import.meta.url);const ledger=JSON.parse(readFileSync(new URL('docs/postal-context-m2-rollout.json',root),'utf8'));const ba=ledger.countries.find(country=>country.countryCode==='BA');const be=ledger.countries.find(country=>country.countryCode==='BE');const manifest=JSON.parse(readFileSync(new URL('data/postal_country_packs/ba/postal-context/repository-manifest.json',root),'utf8'));const digest=path=>'sha256:'+createHash('sha256').update(readFileSync(new URL(path,root))).digest('hex');
test('BA stays blocked under its three-operator assignment and area criterion',()=>{assert.equal(ba.status,'blocked');assert.equal(ba.attempts,1);assert.equal(ba.evidence,null);assert.equal(ba.m2Definition.id,'M2_current_three_operator_assignment_and_postal_area_visualization');assert.equal(manifest.promotion.target_stage,ba.m2Definition.id);});
test('points, prefixes, administrative and cadastral data do not become postal polygons',()=>{assert.equal(ba.blocker.evidence.authorizedPublicPostalOperators,3);assert.equal(ba.blocker.evidence.officeRecordsReviewed,1337);assert.equal(ba.blocker.evidence.officialPostalGeometryRecords,0);assert.equal(ba.blocker.evidence.officePointIsPostcodeArea,false);assert.equal(ba.blocker.evidence.postalRegionPrefixIsFullCodeArea,false);assert.equal(ba.blocker.evidence.administrativeOrCadastralGeometryIsPostcodeArea,false);});
test('ledger pins both reports and Belgium is next',()=>{assert.equal(digest('reports/postal-context-m2/ba-source-review-2026-08-29.json'),ba.lastAttempt.reportDigest);assert.equal(digest('reports/postal-context-m2/ba-checks-2026-08-29.json'),ba.lastAttempt.engineeringReportDigest);assert.equal(be.status,'pending');assert.equal(be.region,'europe');});
test('shared visualization capability cannot promote BA without real geometry',()=>{assert.equal(ba.blocker.evidence.sharedAppAreaPathVerified,true);assert.equal(ba.blocker.evidence.realBosniaAgidPostalApiVerified,false);assert.equal(ba.blocker.evidence.realBosniaAgidAppAreaVisualizationVerified,false);assert.match(ba.blocker.retryPolicy,/Do not authenticate.*accept.*pay/i);});
