import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
const root=new URL('../',import.meta.url);const ledger=JSON.parse(readFileSync(new URL('docs/postal-context-m2-rollout.json',root),'utf8'));const bg=ledger.countries.find(country=>country.countryCode==='BG');const by=ledger.countries.find(country=>country.countryCode==='BY');const manifest=JSON.parse(readFileSync(new URL('data/postal_country_packs/bg/postal-context/repository-manifest.json',root),'utf8'));const digest=path=>'sha256:'+createHash('sha256').update(readFileSync(new URL(path,root))).digest('hex');
test('BG stays blocked under its current assignment and area visualization criterion',()=>{assert.equal(bg.status,'blocked');assert.equal(bg.attempts,1);assert.equal(bg.evidence,null);assert.equal(bg.m2Definition.id,'M2_current_assignment_and_rights_cleared_postal_area_visualization');assert.equal(manifest.promotion.target_stage,bg.m2Definition.id);});
test('historical locality data and current postcode points do not become postal polygons',()=>{assert.equal(bg.blocker.evidence.bulgarianPostsDatasetYear,2020);assert.equal(bg.blocker.evidence.giscoBulgariaPointRecords,4880);assert.equal(bg.blocker.evidence.giscoMemberStatePostalDatasetRecords,0);assert.equal(bg.blocker.evidence.gisco2020Records,4359);assert.equal(bg.blocker.evidence.postalPolygonOrMultiPolygonRecords,0);assert.equal(bg.blocker.evidence.pointBufferVoronoiOrNutsUsedAsPostalArea,false);});
test('ledger pins both reports and Belarus is next',()=>{assert.equal(digest('reports/postal-context-m2/bg-source-review-2026-08-29.json'),bg.lastAttempt.reportDigest);assert.equal(digest('reports/postal-context-m2/bg-checks-2026-08-29.json'),bg.lastAttempt.engineeringReportDigest);assert.equal(by.status,'pending');assert.equal(by.region,'europe');});
test('shared visualization capability cannot promote BG without real area geometry',()=>{assert.equal(bg.blocker.evidence.sharedAppAreaPathVerified,true);assert.equal(bg.blocker.evidence.realBulgariaAgidPostalApiVerified,false);assert.equal(bg.blocker.evidence.realBulgariaAgidAppAreaVisualizationVerified,false);assert.match(bg.blocker.retryPolicy,/Do not authenticate.*accept.*pay/i);});
