import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  ADDRESS_INFORMATION_AXIOMS,
  ADDRESS_INFORMATION_ENGINEERING_FOUNDATIONS_VERSION,
  ADDRESS_INFORMATION_KINDS,
  ADDRESS_INFORMATION_LAYER_CONTRACTS,
  ADDRESS_INFORMATION_OPERATIONS,
  ADDRESS_INFORMATION_STANDARD_BRIDGES,
  buildAddressInformationEngineeringFoundationsReport,
  validateAddressInformationEngineeringFoundations,
} from '../src/lib/addressInformationEngineeringFoundations';

const ADDRESS_RESEARCH_REPO_URL = 'https://github.com/dawnportinfo-design/address-research.git';
const npmExecPath = process.env.npm_execpath;

type CommandResult = {
  stdout: string;
  stderr: string;
};

function runCommand(command: string, args: string[], cwd: string): CommandResult {
  const result = spawnSync(command, args, {
    cwd,
    encoding: 'utf8',
    shell: false,
  });

  const stdout = result.stdout ?? '';
  const stderr = result.stderr ?? '';

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    throw new Error([
      `command failed: ${command} ${args.join(' ')}`,
      `cwd: ${cwd}`,
      stdout.trim(),
      stderr.trim(),
    ].filter(Boolean).join('\n'));
  }

  return { stdout, stderr };
}

function runNpm(args: string[], cwd: string): CommandResult {
  if (npmExecPath) {
    return runCommand(process.execPath, [npmExecPath, ...args], cwd);
  }

  return runCommand('npm', args, cwd);
}

function renderJavaScriptModule(): string {
  return `// Generated by AGID's address-research port preview verifier.
// The source registry lives in src/lib/addressInformationEngineeringFoundations.ts.

export const ADDRESS_INFORMATION_ENGINEERING_FOUNDATIONS_VERSION = ${JSON.stringify(ADDRESS_INFORMATION_ENGINEERING_FOUNDATIONS_VERSION)};

export const ADDRESS_INFORMATION_KINDS = ${JSON.stringify(ADDRESS_INFORMATION_KINDS, null, 2)};

export const ADDRESS_INFORMATION_AXIOMS = ${JSON.stringify(ADDRESS_INFORMATION_AXIOMS, null, 2)};

export const ADDRESS_INFORMATION_OPERATIONS = ${JSON.stringify(ADDRESS_INFORMATION_OPERATIONS, null, 2)};

export const ADDRESS_INFORMATION_LAYER_CONTRACTS = ${JSON.stringify(ADDRESS_INFORMATION_LAYER_CONTRACTS, null, 2)};

export const ADDRESS_INFORMATION_STANDARD_BRIDGES = ${JSON.stringify(ADDRESS_INFORMATION_STANDARD_BRIDGES, null, 2)};

export function validateAddressInformationEngineeringFoundations() {
  const errors = [];
  const kindSet = new Set(ADDRESS_INFORMATION_KINDS);
  const axiomIds = new Set();
  const operationNames = new Set();
  const layerIds = new Set();
  const standards = new Set();

  for (const required of ['expression', 'referent', 'identifier', 'proof', 'receipt']) {
    if (!kindSet.has(required)) errors.push(\`missing-kind:\${required}\`);
  }

  for (const axiom of ADDRESS_INFORMATION_AXIOMS) {
    if (axiomIds.has(axiom.id)) errors.push(\`duplicate-axiom:\${axiom.id}\`);
    axiomIds.add(axiom.id);
    if (axiom.protects.length === 0) errors.push(\`axiom-missing-protects:\${axiom.id}\`);
    if (!axiom.failureMode || !axiom.nonClaim) errors.push(\`axiom-missing-safety-text:\${axiom.id}\`);
  }

  for (const operation of ADDRESS_INFORMATION_OPERATIONS) {
    if (operationNames.has(operation.name)) errors.push(\`duplicate-operation:\${operation.name}\`);
    operationNames.add(operation.name);
    if (operation.inputKinds.length === 0 || operation.outputKinds.length === 0) {
      errors.push(\`operation-missing-kind:\${operation.name}\`);
    }
    if (operation.nonClaims.length === 0) errors.push(\`operation-missing-non-claim:\${operation.name}\`);
    if (operation.name === 'prove' && !operation.nonClaims.some(nonClaim => /does not repair/i.test(nonClaim))) {
      errors.push('prove-missing-non-repair-boundary');
    }
    if (operation.name === 'normalize' && !operation.nonClaims.some(nonClaim => /not referent resolution/i.test(nonClaim))) {
      errors.push('normalize-missing-non-identity-boundary');
    }
  }

  for (const layer of ADDRESS_INFORMATION_LAYER_CONTRACTS) {
    if (layerIds.has(layer.id)) errors.push(\`duplicate-layer:\${layer.id}\`);
    layerIds.add(layer.id);
    if (layer.failureStates.length < 2) errors.push(\`layer-too-few-failure-states:\${layer.id}\`);
    if (layer.nonClaims.length === 0) errors.push(\`layer-missing-non-claim:\${layer.id}\`);
  }

  for (const bridge of ADDRESS_INFORMATION_STANDARD_BRIDGES) {
    if (standards.has(bridge.standard)) errors.push(\`duplicate-standard:\${bridge.standard}\`);
    standards.add(bridge.standard);
    if (bridge.mappedKinds.length < 2) errors.push(\`standard-too-few-kinds:\${bridge.standard}\`);
    if (bridge.nonClaims.length === 0) errors.push(\`standard-missing-non-claim:\${bridge.standard}\`);
  }

  if (ADDRESS_INFORMATION_LAYER_CONTRACTS.length !== 8) errors.push('expected-eight-layer-contracts');
  if (ADDRESS_INFORMATION_AXIOMS.length !== 8) errors.push('expected-eight-axioms');

  return errors;
}

export function buildAddressInformationEngineeringFoundationsReport() {
  return {
    version: ADDRESS_INFORMATION_ENGINEERING_FOUNDATIONS_VERSION,
    kindCount: ADDRESS_INFORMATION_KINDS.length,
    axiomCount: ADDRESS_INFORMATION_AXIOMS.length,
    operationCount: ADDRESS_INFORMATION_OPERATIONS.length,
    layerCount: ADDRESS_INFORMATION_LAYER_CONTRACTS.length,
    standardBridgeCount: ADDRESS_INFORMATION_STANDARD_BRIDGES.length,
    safetyBoundaries: {
      typeSeparation: ADDRESS_INFORMATION_AXIOMS.some(axiom => axiom.id === 'A1-type-separation'),
      nonRepairProof: ADDRESS_INFORMATION_OPERATIONS.some(operation => (
        operation.name === 'prove' && operation.nonClaims.some(nonClaim => /does not repair/i.test(nonClaim))
      )),
      safeNonEmission: ADDRESS_INFORMATION_AXIOMS.some(axiom => axiom.id === 'A8-safe-non-emission'),
      noUniversalValidation: ADDRESS_INFORMATION_AXIOMS.some(axiom => (
        axiom.id === 'A2-context-dependence' && /universal address-valid/i.test(axiom.nonClaim)
      )),
    },
    validationErrors: validateAddressInformationEngineeringFoundations(),
  };
}
`;
}

function renderJavaScriptTest(): string {
  return `import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import {
  ADDRESS_INFORMATION_AXIOMS,
  ADDRESS_INFORMATION_KINDS,
  ADDRESS_INFORMATION_LAYER_CONTRACTS,
  ADDRESS_INFORMATION_OPERATIONS,
  ADDRESS_INFORMATION_STANDARD_BRIDGES,
  buildAddressInformationEngineeringFoundationsReport,
  validateAddressInformationEngineeringFoundations,
} from '../src/addressInformationEngineeringFoundations.js';

test('address information engineering foundations validate as a safe registry', () => {
  const report = buildAddressInformationEngineeringFoundationsReport();

  assert.deepEqual(validateAddressInformationEngineeringFoundations(), []);
  assert.equal(report.kindCount, 10);
  assert.equal(report.axiomCount, 8);
  assert.equal(report.layerCount, 8);
  assert.equal(report.validationErrors.length, 0);
  assert.equal(report.safetyBoundaries.typeSeparation, true);
  assert.equal(report.safetyBoundaries.safeNonEmission, true);
  assert.equal(report.safetyBoundaries.noUniversalValidation, true);
});

test('foundation keeps expression, referent, identifier, proof, and receipt distinct', () => {
  const kinds = new Set(ADDRESS_INFORMATION_KINDS);
  const typeSeparation = ADDRESS_INFORMATION_AXIOMS.find(axiom => axiom.id === 'A1-type-separation');

  for (const required of ['expression', 'referent', 'identifier', 'proof', 'receipt']) {
    assert.ok(kinds.has(required), \`\${required} should be a first-class kind\`);
  }
  assert.ok(typeSeparation);
  assert.match(typeSeparation.nonClaim, /does not make expression, referent, identifier, proof, and receipt the same type/);
});

test('operations preserve non-identity and non-repair boundaries', () => {
  const normalize = ADDRESS_INFORMATION_OPERATIONS.find(operation => operation.name === 'normalize');
  const prove = ADDRESS_INFORMATION_OPERATIONS.find(operation => operation.name === 'prove');
  const render = ADDRESS_INFORMATION_OPERATIONS.find(operation => operation.name === 'render');

  assert.match(normalize?.nonClaims.join(' ') ?? '', /not referent resolution/);
  assert.match(prove?.nonClaims.join(' ') ?? '', /does not repair a bad address resolution/);
  assert.match(render?.nonClaims.join(' ') ?? '', /not the inverse/);
});

test('layers and standard bridges declare non-claims', () => {
  assert.equal(ADDRESS_INFORMATION_LAYER_CONTRACTS.length, 8);
  assert.ok(ADDRESS_INFORMATION_LAYER_CONTRACTS.every(layer => layer.failureStates.length >= 2));
  assert.ok(ADDRESS_INFORMATION_LAYER_CONTRACTS.every(layer => layer.nonClaims.length > 0));
  assert.ok(ADDRESS_INFORMATION_STANDARD_BRIDGES.every(bridge => bridge.nonClaims.length > 0));
});

test('foundations document states the raw-address-free safety boundary', () => {
  const doc = readFileSync('docs/foundations/address-information-engineering-foundations.md', 'utf8');

  assert.match(doc, /surface expression != referent != identifier != credential != proof != receipt/);
  assert.match(doc, /ZK proof が住所解決の誤りを修復すると言わない/);
  assert.match(doc, /Do not port raw address examples/);
});
`;
}

function writePortPreview(repoDir: string): void {
  const sourceDir = join(repoDir, 'src');
  const testDir = join(repoDir, 'tests');
  const foundationsDir = join(repoDir, 'docs', 'foundations');
  mkdirSync(sourceDir, { recursive: true });
  mkdirSync(testDir, { recursive: true });
  mkdirSync(foundationsDir, { recursive: true });

  writeFileSync(join(sourceDir, 'addressInformationEngineeringFoundations.js'), renderJavaScriptModule(), 'utf8');
  writeFileSync(join(testDir, 'addressInformationEngineeringFoundations.test.js'), renderJavaScriptTest(), 'utf8');

  const sourceDoc = readFileSync(
    'docs/research/address-information-engineering-foundations-for-address-research-ja.md',
    'utf8',
  );
  const previewDoc = [
    '# Address Information Engineering Foundations',
    '',
    'This file is generated in a temporary address-research clone by AGID port preview verification.',
    'Do not port raw address examples, recipients, private keys, proof witnesses, or production credentials.',
    '',
    sourceDoc,
  ].join('\n');
  writeFileSync(join(foundationsDir, 'address-information-engineering-foundations.md'), previewDoc, 'utf8');

  const summaryPath = join(repoDir, 'SUMMARY.md');
  if (existsSync(summaryPath)) {
    const summary = readFileSync(summaryPath, 'utf8');
    const link = '- [Address Information Engineering Foundations](docs/foundations/address-information-engineering-foundations.md)';
    if (!summary.includes(link)) {
      writeFileSync(summaryPath, `${summary.trimEnd()}\n\n## Address Information Engineering\n\n${link}\n`, 'utf8');
    }
  }

  const packagePath = join(repoDir, 'package.json');
  const packageJson = JSON.parse(readFileSync(packagePath, 'utf8')) as {
    type?: string;
    scripts?: Record<string, string>;
  };
  packageJson.type = 'module';
  packageJson.scripts = {
    ...(packageJson.scripts ?? {}),
    'verify:address-information-engineering-foundations': 'node --test tests/addressInformationEngineeringFoundations.test.js',
  };
  writeFileSync(packagePath, `${JSON.stringify(packageJson, null, 2)}\n`, 'utf8');
}

function verifyAddressResearchFoundationsPortPreview(): void {
  const localErrors = validateAddressInformationEngineeringFoundations();
  if (localErrors.length > 0) {
    throw new Error(`local foundations registry failed validation: ${localErrors.join(', ')}`);
  }

  const localReport = buildAddressInformationEngineeringFoundationsReport();
  const repoDir = mkdtempSync(join(tmpdir(), 'address-research-foundations-port-'));

  runCommand('git', ['clone', '--depth', '1', ADDRESS_RESEARCH_REPO_URL, repoDir], process.cwd());
  const remoteHead = runCommand('git', ['rev-parse', 'HEAD'], repoDir).stdout.trim();

  writePortPreview(repoDir);

  runNpm(['test'], repoDir);
  runNpm(['run', 'evaluate'], repoDir);
  runNpm(['run', 'verify:address-information-engineering-foundations'], repoDir);

  console.log(JSON.stringify({
    status: 'pass',
    repo: 'dawnportinfo-design/address-research',
    remoteHead,
    tempRepo: repoDir,
    generatedFiles: [
      'src/addressInformationEngineeringFoundations.js',
      'tests/addressInformationEngineeringFoundations.test.js',
      'docs/foundations/address-information-engineering-foundations.md',
    ],
    localReport,
    safety: {
      remoteMutations: false,
      productionTraffic: false,
      rawAddressFixtures: false,
    },
  }, null, 2));
}

verifyAddressResearchFoundationsPortPreview();
